### PR TITLE
fix(yaml) - correct escaping behavior in single-quoted YAML strings

### LINKED ISSUE #4068: (YAML) Handling of '\'
Highlight.js seems to treat `'\'` in YAML as escaping the `'` but with `'` quoting the backslash does not escape the apostrophe in YAML.

image

### PR DESCRIPTION
**Pull request by guuido**
Fixes wrong escaping behavior in single-quoted strings

Resolves #4068 

### Changes
Before, backslashes in single-quoted strings were incorrectly treated as escape characters:

image

Now single-quoted strings follow YAML specification where only single quotes can be escaped (by doubling them):

image

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/yaml.js [hunk 1]
```diff
@@ -42,14 +42,28 @@ export default function(hljs) {
       }
     ]
   };
-  const STRING = {
+
+  const SINGLE_QUOTE_STRING = {
     className: 'string',
     relevance: 0,
     variants: [
```
Comment (joshgoebel) [inline src/languages/yaml.js:49]: We no longer need variants if there is only one.

File: src/languages/yaml.js [hunk 2]
```diff
@@ -42,14 +42,28 @@ export default function(hljs) {
...
       {
         begin: /'/,
         end: /'/
-      },
+      }
+    ],
+    contains: [
+      {
+        begin: /''/,
```
Comment (joshgoebel) [inline src/languages/yaml.js:57]: I wonder if this should be `char.escape` scoped?

**Comment by joshgoebel** [comment]
Lets also make sure we add a single quote escaping to our markup tests - esp if we go with `char.escape`.

File: src/languages/yaml.js (hunk 2 above)
Comment (guuido) [reply src/languages/yaml.js:57]: if we use `char.escape` scope both quotes are included
```
<span class="hljs-char escape_">&#x27;&#x27;</span>
```
should I change the pattern to target only the first quote in the pair?

Comment (joshgoebel) [reply src/languages/yaml.js:57]: > both quotes are included

Makes sense to me, I'd say both quotes are the entire escape sequence - which is what we're wanting to make stand out...

**Review by joshgoebel — APPROVED** [review]
