### PR TITLE
fix(nix) Support escaped dollar sign in strings

### LINKED ISSUE #3635: (nix) Escaped dollar sign not highlighted correctly
**Describe the issue**

Nix allows escaping antiquotes like this:

```nix
{
  a = ''
    Antiquote: ${x}
    Escaped dollar sign: ''${y}
  '';
}
```

**Which language seems to have the issue?**

nix

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**

```nix
{
  a = ''
    Antiquote: ${x}
    Escaped dollar sign: ''${y}
  '';
}
```

**Expected behavior**

See the github highlighting

**Additional context**

### PR DESCRIPTION
**Pull request by h7x4**
Added a rule that escapes `''$` in strings.

Resolves #3635

### Checklist

- [X] Added markup tests
- [X] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/nix.js [hunk 1]
```diff
@@ -45,6 +45,10 @@ export default function(hljs) {
     end: /\}/,
     keywords: KEYWORDS
   };
+  const ESCAPED_DOLLAR = {
+    className: 'char.escape',
+    begin: /''\$\{/,
```
Comment (joshgoebel) [inline src/languages/nix.js:50]: Is `''` escaping the `$` or `${`... your issue seems to indicate it's escaping `$`, so I'm a little confused at seeing the { here.

Comment (h7x4) [reply src/languages/nix.js:50]: I think I've confused myself here a little. The only reason you would ever want to escape the dollar, is to escape an antiquote. But it is indeed the dollar itself that should be escaped. Updating now.

**Review by joshgoebel — APPROVED** [review]
