### PR TITLE
Python self

### LINKED ISSUE #4024: Highlighting the self variable in Python
**Describe the issue**
Many syntax highlighters identify `self` in python as a distinct identifier, similar to `$this` in PHP. Highlight.js does not currently do this.

**Which language seems to have the issue?**
python

**Are you using `highlight` or `highlightAuto`?**
Both

**Sample Code to Reproduce**
```
class SelfTest:
    def __init__(self):
        self.text = True

    def method(self):
        pass
```

**Expected behavior**
(From Sublime Text)
image

**Actual behavior**
image

**Additional context**
While the python grammar definition [recognizes self](https://github.com/highlightjs/highlight.js/blob/8a3c8d5861f31ec0eb92cf092fc3a85cb9315fd6/src/languages/python.js#L376), it does not assign it a scope. In contrast, the PHP definition [assigns](https://github.com/highlightjs/highlight.js/blob/8a3c8d5861f31ec0eb92cf092fc3a85cb9315fd6/src/languages/php.js#L514) the `variable.language` scope to `$this`.

### PR DESCRIPTION
**Pull request by lfalin**
This change assigns a scope to the `self` variable in Python, similar to the PHP definition. This variable was already identified in the grammar parser (presumably for recognition), but no scope was assigned. 

Resolves #4024 

### Changes
- Assigns a scope to the `self` variable in the python language definition.
- Adds a markup test for the above change. 

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/python.js [hunk 1]
```diff
@@ -373,6 +373,7 @@ export default function(hljs) {
       NUMBER,
       {
         // very common convention
+        scope: 'variable.language',
         begin: /\bself\b/
```
Comment (joshgoebel) [inline src/languages/python.js:377]:
```suggestion
        match: /\bself\b/
```

**Review by joshgoebel — APPROVED** [review]
