### PR TITLE
fix(javascript,scala) Resolves various highlighting issues with comments

### LINKED ISSUE #1559: (scala) comment rendered as class title
Given input

```
class A  // Something goes here
{
}
```

Comment words (including `//`) are rendered as titles:

```
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">A</span>  <span class="hljs-title">//</span> <span class="hljs-title">Something</span> <span class="hljs-title">goes</span> <span class="hljs-title">here</span></span>
{
}
```

On the other hand if curly bracket is in the same line:

```
class A {  // Something goes here
}
```

Output is rendered as expected:

```
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">A</span> </span>{  <span class="hljs-comment">// Something goes here</span>
}
```

I used `hljs.highlight('Scala', rawSourceCode)` for the formatting.

Highlight.js version: `9.12.0`

### LINKED ISSUE #2702: (javascript) Comments are not highlighted if inside params
**Describe the issue**

Comments do not seem to be detected inside params for Javascript.

**Which language seems to have the issue?**

Javascript.

**Sample Code to Reproduce**

```
f = (                // f is a recursive function taking:
  [c,                //   c   = next digit character
      ...a],         //   a[] = array of remaining digits
  o = '',            //   o   = output string
  S = new Set        //   S   = set of solutions
) =>                 //
  c ?                // if c is defined:
    f(               //   do a recursive call:
      a,             //     pass a[]
      o + c,         //     append c to o
      o ?            //     if o is non-empty:
        f(           //       do another recursive call
          a,         //         pass a[]
          o + [, c], //         append a comma followed by c to o
          S          //         pass S
        )            //       end of recursive call (returns S)
      :              //     else:
        S            //       just pass S as the 3rd argument
    )                //   end of recursive call (returns S)
  :                  // else:
    S.add(           //   add to the set S:
      o.replace(     //     the string o with ...
        /\d+/g,      //       ... all numeric strings
        n => +n      //       coerced to integers to remove leading zeros
                     //       (and coerced back to strings)
      )              //     end of replace()
    )                //   end of add() (returns S)
```

From: https://meta.stackexchange.com/questions/353983/goodbye-prettify-hello-highlight-js-swapping-out-our-syntax-highlighter

**Expected behavior**

Comments should be highlighted.

**Additional context**

Some other languages have this same issue (or very similar)
G5sz3

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2702.
Resolves #1559.

### CODE REVIEW

File: src/languages/javascript.js [hunk 1]
```diff
@@ -78,14 +78,21 @@ export default function(hljs) {
...
+      end: /\)/,
+      contains: ["self"].concat([
+          hljs.C_BLOCK_COMMENT_MODE,
+          hljs.C_LINE_COMMENT_MODE
+        ],
+        SUBST.contains
+      )
+    }
+  ], SUBST.contains);
   var PARAMS = {
```
Comment (joshgoebel) [inline src/languages/javascript.js:96]: This is just flipped the order and moving the comment modes to the top of the contains list for both PARAMS_CONTAINS and it's recursive sub expression matcher.

**Review by allejo — APPROVED** [review]
