### PR TITLE
enh(java) add `sealed` and `non-sealed` keywords

### LINKED ISSUE #3346: (Java) Java 17 sealed keywords not implemented
With the release of Java 17 being an **LTS**, it seems proper to support the new `sealed` keyword.
However, the new `non-sealed` keyword brings some issues, that [while I have attempted to fix](https://github.com/thiccaxe/highlight.js/commit/e285198f222a48a363338b54e3c077b6a18db18d), seem best suited for someone more familiar with the highlightjs library.

**Sample Code or Instructions to Reproduce**
[sample js fiddle](https://jsfiddle.net/Lv2hmbpt/2/)

**Expected behavior**
the `sealed` keyword should be highlighted, and as more hyphenated keywords may come to java in the future, some structure
 may be useful for `non-sealed` and the like.

### PR DESCRIPTION
**Pull request by bradleymackey**
Adds support for these missing keywords, using a different matching pattern for hyphenated keywords as a workaround. [Source for suggested workaround](https://github.com/thiccaxe/highlight.js/commit/e285198f222a48a363338b54e3c077b6a18db18d#r57401045).

### Changes

- Adds `sealed` and `non-sealed` keywords
- Fixes #3346

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/java.js [hunk 1]
```diff
@@ -179,6 +180,15 @@ export default function(hljs) {
...
       },
+      {
+        // Exceptions for hyphenated keywords
+        match: [
+          /non-sealed/
+        ],
+        className: {
+          1: "keyword"
+        }
+      },
```
Comment (joshgoebel) [inline src/languages/java.js:191]: Lets use the simple form?
```suggestion
        match:  /non-sealed/,
        scope: "keyword"
      },
```

**Review by joshgoebel — APPROVED** [review]
Looks good but lets make the one change suggested.

File: src/languages/java.js (hunk 1 above)
Comment (bradleymackey) [reply src/languages/java.js]: Got it.

**Review by joshgoebel — APPROVED** [review]
