### PR TITLE
enh(parser): Better errors when one language requires another

### LINKED ISSUE #1899: error registering arduino language
I am trying to register arduino language like this:
```js
import arduinoHljs from 'highlight.js/lib/languages/arduino';

hljs.registerLanguage('arduino', arduinoHljs);
hljs.configure({
  languages: [arduinoHljs]
});
```
But I am getting this error:
```
Uncaught TypeError: Cannot read property 'exports' of undefined
    at module.exports (arduino.js:2)
    at Object.registerLanguage (highlight.js:694)
...
``` 

Reading issue #1235 i understood that arduino relies on cpp language, and the order of the languages could mess things up, so I tried to register cpp too like this:
```js
import cppHljs from 'highlight.js/lib/languages/cpp';
import arduinoHljs from 'highlight.js/lib/languages/arduino';

hljs.registerLanguage('cpp', cppHljs);
hljs.registerLanguage('arduino', arduinoHljs);
hljs.configure({
  languages: [arduinoHljs]
});
```
and it went well.
But this still feels a little weird. Why do I have to import a language when it is already specified elsewhere that arduino relies on cpp? I believe this should be done automatically when registering a derived language. But maybe I am missing something, am I?

### PR DESCRIPTION
**Pull request by yyyc514**
Closes #1899.

### CODE REVIEW

**Comment by yyyc514** [comment]
Screen Shot 2019-12-06 at 3 23 08 PM

**Comment by yyyc514** [comment]
@egor-rogov Simply makes requires explicit rather than implicit so we can provide better errors when something goes wrong vs some generic error.

**Comment by yyyc514** [comment]
Since this typically happens in registerLanguage it benefits from all the new safe mode stuff... ie you get the helpful errors in the console (shown above), but overall usage of Highlight.js continues to work (other than say the Arduino language, which would be broken).

File: src/languages/arduino.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ function(hljs) {
         'DEFAULT OUTPUT INPUT HIGH LOW'
   };
 
-  var ARDUINO = hljs.getLanguage('cpp').rawDefinition();
+  var ARDUINO = hljs.requireLanguage('cpp').rawDefinition();
```
Comment (egor-rogov) [inline src/languages/arduino.js]: Shouldn't this go to v.10 as a breaking change?

Comment (yyyc514) [reply src/languages/arduino.js]: Except it's not a breaking change.   Unless you're talking about using languages compiled for 9.17 with 9.16... that wouldn't work... but otherwise there is no breakage here... we're adding a new API, not renaming it.

Comment (egor-rogov) [reply src/languages/arduino.js]: Ah, right. If you have no cpp, arduino won't work anyway (:

Comment (yyyc514) [reply src/languages/arduino.js]: My new build system resolves dependencies (so asking for `arduino` will always also get you `cpp`)... but still people requiring languages one at a time with NPM or something can get bitten by this... not sure how to prevent people from shooting themselves in the foot.
