### PR TITLE
env(perl) Much improved regex detection

### LINKED ISSUE #2952: (Perl) No support for `m` style regex with arbitrary delimiters
**Describe the issue**
Regex detection after keyword `m` fails if having a slash f.ex.  `$d .= '/' if $d !~ m(/$);`

**Which language seems to have the issue?**
Perl

**Are you using `highlight` or `highlightAuto`?**
initHighlightingOnLoad 

**Sample Code to Reproduce**
https://jsfiddle.net/0t6zh59g/

```
my %domain_data;
foreach my $d (@domains) {
    my $label = $d;
    $d .= '/' if $d !~ m(/$);
    $label =~ s#^https?://##;
    $label =~ s#[^A-Za-z]#_#g;
    next if $label eq "_";
    $domain_data{$d} = [ $label, 0 ];
}
```
Screenshot
2021-01-07 14 00 59 jsfiddle net ff0b47f76bf6

**Expected behavior**
Only `/$` is hilighted as regex.

**Additional context**
Perl's match operator allows a unescaped /  , the regex parser of HLJS should detect this. 
More valid regex are f.ex. `m|/$|` or `m#/$#` or `m{/$}`
Same issue happens with `$d .= '/' if $d !~ qr(/$);` and other regexes as parameters for [Regexp Quote Like Operators](https://perldoc.perl.org/perlop#Regexp-Quote-Like-Operators)

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2952.

### Changes

Added many more common regex variants to `perl`.

This does not attempt to solve:

```
say ("fee" =~ s aeaoagr . "bar");
```

Regex with entirely arbitrary characters are a pain because they
could potentialy match so many languages, and slow down auto-detect
so we will try to avoid them for now.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

File: src/languages/perl.js [hunk 1]
```diff
@@ -9,29 +9,244 @@ import * as regex from '../lib/regex.js';
...
-    'getsockopt getpriority rindex wantarray hex system getservbyport endservent int chr ' +
-    'untie rmdir prototype tell listen fork shmread ucfirst setprotoent else sysseek link ' +
-    'getgrgid shmctl waitpid unpack getnetbyname reset chdir grep split require caller ' +
-    'lcfirst until warn while values shift telldir getpwuid my getprotobynumber delete and ' +
-    'sort uc defined srand accept package seekdir getprotobyname semop our rename seek if q|0 ' +
-    'chroot sysread setpwent no crypt getc chown sqrt write setnetent setpriority foreach ' +
-    'tie sin msgget map stat getlogin unless elsif truncate exec keys glob tied closedir ' +
-    'ioctl socket readlink eval xor readline binmode setservent eof ord bind alarm pipe ' +
-    'atan2 getgrent exp time push setgrent gt lt or ne m|0 break given say state when'
+    keyword: KEYWORDS.join(" ")
```
Comment (allejo) [inline src/languages/perl.js:249]: I know this PR was made before #2961 was merged, but now it can be used

**Review by allejo — APPROVED** [review]

File: src/languages/perl.js (hunk 1 above)
Comment (joshgoebel) [reply src/languages/perl.js:249]: If you'd made a mini-diff I'd have committed. :)  This can be fixed whenever, but good catch.
