### PR TITLE
WIP: enh(bash) allow nested params

### LINKED ISSUE #2730: (Bash) Nested parameter expansion not detected
**Describe the issue**
Nested parameter expansions are not detected. In this case, it causes a problem with the quoting. Screenshots from [this Stack Overflow answer](https://stackoverflow.com/a/3352015/4518341):
Screenshot showing code highlighting Screenshot showing "variable" token
Notice how the last close-brace is white as if it's unquoted, and the following lines are green as if they're part of a string.

**Which language seems to have the issue?**
bash/lang-sh - I'm not sure if they're equivalent or what. If it helps, the HTML class is `"lang-sh s-code-block hljs bash"`

**Are you using `highlight` or `highlightAuto`?**
I don't know what that means. I assume it's about how highlight.js is deployed, but I'm an end user, not a Stack Exchange dev.

**Sample Code to Reproduce**
```bash
# remove leading whitespace characters
var="${var#"${var%%[![:space:]]*}"}"
# remove trailing whitespace characters
var="${var%"${var##*[![:space:]]}"}"
```

**Expected behavior**
GitHub gets it right.
As well, here's Atom:
Screenshot showing code highlighting in Atom

**Additional context**
none

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2730

### CODE REVIEW

File: src/languages/bash.js [hunk 1]
```diff
@@ -10,9 +10,14 @@ Category: common
 export default function(hljs) {
   const VAR = {};
   const BRACED_VAR = {
-    begin: /\$\{/, end:/\}/,
+    begin: /\$\{/,
+    end:/\}/,
     contains: [
-      { begin: /:-/, contains: [VAR] } // default values
+      "self",
```
Comment (joshgoebel) [inline src/languages/bash.js:16]: Actual change on this line!

**Review by allejo — APPROVED** [review]
