### PR TITLE
fix(Go): improve function matching

### LINKED ISSUE #2177: Go highlighting bug with `func`
This piece of code:

```go
TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler), 0),
```

Seems to cause issues with further parsing. A good example of this in action can be seen here:
https://ssl-config.mozilla.org/#server=golang&server-version=1.13.1&config=intermediate

Where the comment about ECDHE is red and bolded, instead of muted and gray. If you replace `func` with `foo`, everything seems to work correctly.

### PR DESCRIPTION
**Pull request by cdbax**
Fixes #2177 

The existing implementation ended function matching at the opening of the function body `{`.
This approach didn't work for function type declarations.

Neither implementation is perfect, as the function body should probably be wrapped by the function tags. A shortcoming of this implementation is that it doesn't wrap the return type in the function tag, and for some reason it isn't detecting the return type as 'params'.

I'll keep trying things to improve it further. Suggestions would be welcome.

### CODE REVIEW

File: src/languages/go.js [hunk 1]
```diff
@@ -45,14 +45,15 @@ function(hljs) {
       },
       {
         className: 'function',
-        beginKeywords: 'func', end: /\s*\{/, excludeEnd: true,
+        beginKeywords: 'func', end: /\B\b/,
```
Comment (yyyc514) [inline src/languages/go.js]: If this is still goin to be a single line you’d just do {|$

Bracket or end of line.

File: src/languages/go.js [hunk 2]
```diff
@@ -45,14 +45,15 @@ function(hljs) {
...
         contains: [
           hljs.TITLE_MODE,
           {
             className: 'params',
             begin: /\(/, end: /\)/,
             keywords: GO_KEYWORDS,
-            illegal: /["']/
+            illegal: /["']/,
+            endsParent: true
```
Comment (yyyc514) [inline src/languages/go.js]: This will end the parent mode after you’d see a single set of parents. So that’s why it will never match a second set of parents.

**Comment by cdbax** [comment]
That's much nicer. Thanks!

File: src/languages/go.js (hunk 1 above)
Comment (yyyc514) [reply src/languages/go.js]: I’d still gobble up the white space first though.

Comment (cdbax) [reply src/languages/go.js]: Would you still use `\s*`? I'm guessing it won't matter that that includes newlines, as the `$` would presumably match first.

Comment (yyyc514) [reply src/languages/go.js]: I’m not sure it does. Try it and see what the tests do.

**Comment by cdbax** [comment]
Updated. It's still not ideal, as I'd prefer to get it so the function tag wrapped the body as well, but fixing that is a much deeper rabbit hole. I think this is an improvement for now that fixes the original issue, and I'll keep the bigger fix as an exercise for another day.

Also - I discovered the question about newlines was moot as that would be invalid Go.

**Comment by yyyc514** [comment]
> Updated. It's still not ideal, as I'd prefer to get it so the function tag wrapped the body as well, but fixing that is a much deeper rabbit hole.

None of the other grammars (that I'm aware of do this) and I'm not entirely sure whether it's "in scope"... I'm afraid it would make the parsers much more complex if added to all of them and therefore increase the size significantly.  Take a look at the grammars for something like VS Code and you'll see they are usually very large.  That's the price of trying actually parse the full grammar vs just looking for useful patterns to highlight.

@egor-rogov Do you have any thoughts on this?  Surely if the size/complexity was small I think it'd be great if our parsers were smarter... so I wouldn't think we'd object... but if the code/patterns got **significantly** more complex, or the size became 500% larger, would that be a reason to reject a change a long these lines?

**Comment by yyyc514** [comment]
Does my last commit still look good to you?

File: test/markup/go/functions.txt [hunk 3]
```diff
@@ -0,0 +1,9 @@
+func name()
+
+func name(int32, *somePointer)(string)
+
+map[string]func(int32, string)
+
+func name (x int32) int32 {
```
Comment (yyyc514) [inline test/markup/go/functions.txt]: Good addition.

**Comment by cdbax** [comment]
Yeah that looks great. 👍

**Comment by yyyc514** [comment]
Merging after tests run again..  @cdbax Thanks!
