### PR TITLE
(java): #2507 added support for hexadecimal floating point literals

### LINKED ISSUE #2507: (java) Support for Hexadecimal Floating Point Literals
**Describe the issue**

**Which language seems to have the issue?**

According to [Oracle Blog](https://blogs.oracle.com/darcy/hexadecimal-floating-point-literals) Hexadecimal Floating Point Literals are supported in Java.

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

Cases _a-h_ are all legal literals in Java, tested on JShell Version 13.0.2

https://jsfiddle.net/ohqapxnc/

```java
a = 0x4fa6p2; // 81560.0
b = 0x.4p2; // 1.0
c = 0xa.ffp3f; // 87.96875
d = 0x1.0p2F; // 4.0
d2 = 0x1.p2; // 4.0
e = 0x1.0p2f; // 4.0
f = 0x1p1; // 2.0
g = 0x.3p4d; // 3.0
h = 0x1.2ep5D; // 37.75
```

**Expected behavior**

I would expect that all legal literals are highlighted as numbers.

### LINKED ISSUE #2508: (java) Scientific notation numbers are only legal for floating points
**Describe the issue**

HighlightJS highlights illegal number literals

**Which language seems to have the issue?**

java

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

Case _a_ and _b_ should be illegal, case _c_ and _d_ are fine.

https://jsfiddle.net/e1xnqskb/

```java
a = 2e4L;
b = 2e3l;
c = 2e3f;
d = 1.2e4D;
```

**Expected behavior**

I would expect that illegal number literals are not highlighted

**Additional context**

It's a similar issue to #2507

### PR DESCRIPTION
**Pull request by 0xflotus**
Resolves #2507.
Resolved #2508.

### CODE REVIEW

**Comment by yyyc514** [comment]
Why does this not include all the test cases from the issue?

**Comment by 0xflotus** [comment]
> Why does this not include all the test cases from the issue?

I'm not sure which ones you want, all from the issue?

**Comment by yyyc514** [comment]
> I'm not sure which ones you want, all from the issue?

Sure, if they were valid test cases.

File: src/languages/java.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ Category: common, enterprise
 Website: https://www.java.com/
 */
 
-export default function(hljs) {
+export default function (hljs) {
```
Comment (yyyc514) [inline src/languages/java.js:8]: Did the linter flag this?  pretty sure I turned that off as we prefer no space.

Comment (0xflotus) [reply src/languages/java.js:8]: My VSCode did this, when I hit the save button I think...

Comment (yyyc514) [reply src/languages/java.js:8]: If you can configure it to not rewrite the whole file (for the future) we'd appreciate it.

**Comment by yyyc514** [comment]
You need to update the expect side of the tests also... are you running the tests locally?

**Comment by 0xflotus** [comment]
> You need to update the expect side of the tests also... are you running the tests locally?

No, when I run `node test/markup` I got an error `Cannot find module '../../build'` :(

**Comment by yyyc514** [comment]
Did you build first?  There are docs on building and testing...

**Comment by 0xflotus** [comment]
> Did you build first? There are docs on building and testing...

I did `node tools/build.js java`, thought this was the build script. Had to look closer 👀

**Comment by yyyc514** [comment]
You need to build `-t node`, and not just java, the test suite requires all languages be built.

**Comment by 0xflotus** [comment]
> You need to build `-t node`, and not just java, the test suite requires all languages be built.

So when I hit `node tools/build.js -t node && node test/markup` I get an error `ReferenceError: describe is not defined`. This should be a problem with dependency of the test suite, but I installed all node_modules 🤔

**Comment by yyyc514** [comment]
`npm test`

**Comment by 0xflotus** [comment]
> `npm test`

It's late -.- Ok, sorry without `npm run build` I did not expect the `npm test`

**Comment by yyyc514** [comment]
We could add build but there are 3 different ways to build, so it's not clear which? Should it default to node for maintainers?

**Comment by 0xflotus** [comment]
> We could add build but there are 3 different ways to build, so it's not clear which? Should it default to node for maintainers?

That's up to you. `npm run build:node` could be the one for the maintainers e.g.

**Comment by 0xflotus** [comment]
Bildschirmfoto 2020-04-25 um 04 20 52

Maybe I need some help with this

**Comment by yyyc514** [comment]
Sounds like perhaps you broken some number detection that worked before... making Java less effective so now angelscript wins...?

**Comment by yyyc514** [comment]
You can compare the Java highlighting in the developer tool before and after your patch...

`tools/developer.html`

**Comment by 0xflotus** [comment]
> Sounds like perhaps you broken some number detection that worked before... making Java less effective so now angelscript wins...?

Ok, urgh so maybe others will have more luck with this regex stuff :D 
I didn't get it. Should we close this PR?

**Comment by yyyc514** [comment]
No, I think this is close... these things often are complex and require precision.

**Comment by yyyc514** [comment]
If you run the markup tests you'll see how you aren't handling the prevous tests the same as before:

`./node_modules/.bin/mocha  -b false  --globals document test/markup/`

That's probably part of the issue.

**Comment by 0xflotus** [comment]
With following variants in tools/developer.html it looks good, but what a regex mess 🙈

```javascript
variants: [
      { begin: '\\b(0[bB][01]+)[lL]?' }, // binary
      { begin: '\\b(0[0-7]+)[dDfFlL]?' }, // octal
      { begin: '\\b0[xX]((([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[\\.])?([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[pP]-?([\\d]+)[dDfF]?|([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+))' },
      { begin: '(-?)(\\b0[xX][a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)' + '[dDfFlL]?' }, // hexadecimal, decimal and scientific notation
    ]
```

and the angelscript error is still alive

**Comment by yyyc514** [comment]
You're still not matching the underscores, did you look at the output from running the markup tests?

**Comment by 0xflotus** [comment]
> You're still not matching the underscores, did you look at the output from running the markup tests?

3rd and 4th variant cchecks for underscores, don't they? I'm not sure, this is too omplex, will try it later.

**Comment by yyyc514** [comment]
Run the markup test, look at what fails.  You don't handle `1234_5678_9012_3456L`, for example.

**Comment by 0xflotus** [comment]
With following variants we're almost there

```javascript
variants: [
      { begin: '\\b(0[bB][01]+[01_]*[01]+)[lL]?' }, // binary
      { begin: '\\b(0[0-7]+[0-7_]*[0-7]+)[dDfFlL]?' }, // octal
      { begin: '\\b[\\d]+[\\d_]*[\\d]+[lL]?' }, // decimal
      { begin: '\\b[\\d]+[\\.][\\d_]*[\\d]+[dDfF]?' }, // floating point
      { begin: '\\b([\\d]*[\\.][\\d_]*[\\d]+|[\\d]+[\\d_]*)[eE][+-]?[\\d]+[dDfF]?' }, // scientific notation
      { begin: '\\b0[xX]([a-fA-F0-9]+[a-fA-F0-9_]*[a-fA-F0-9]+)[lL]?' }, // hexadecimal
      { begin: '\\b0[xX]((([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[\\.]?)?([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[pP][+-]?([\\d]+)[dDfF]?|([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+))[fFdD]?' }, // hexadecimal floating point
    ]
```

If I copy the tests in tools/developer.html I get following markup

```html
<span class="hljs-keyword">long</span> creditCardNumber = <span class="hljs-number">1234_5678_9012_3456L</span>;
<span class="hljs-keyword">long</span> socialSecurityNumber = <span class="hljs-number">999_99_9999L</span>;
<span class="hljs-keyword">float</span> pi = <span class="hljs-number">3.14_15F</span>;
<span class="hljs-keyword">long</span> hexBytes = <span class="hljs-number">0xFF_EC_DE_5E</span>;
<span class="hljs-keyword">long</span> hexWords = <span class="hljs-number">0xCAFE_BABE</span>;
<span class="hljs-keyword">long</span> maxLong = <span class="hljs-number">0x7fff_ffff_ffff_ffffL</span>;
<span class="hljs-keyword">byte</span> nybbles = <span class="hljs-number">0b0010_0101</span>;
<span class="hljs-keyword">long</span> bytes = <span class="hljs-number">0b11010010_01101001_10010100_10010010</span>;
<span class="hljs-keyword">int</span> n = <span class="hljs-number">1234</span> + Contacts._ID;
<span class="hljs-keyword">float</span> f = <span class="hljs-number">0x1.4p2f</span>;
<span class="hljs-keyword">double</span> d = <span class="hljs-number">0x.ep-6</span>;
<span class="hljs-keyword">int</span> octal = <span class="hljs-number">0777</span>;
<span class="hljs-keyword">float</span> f = <span class="hljs-number">2e3f</span>;
<span class="hljs-keyword">double</span> d = <span class="hljs-number">1.2</span>e4D;
a = <span class="hljs-number">0x4fa6</span>p2; 
b = <span class="hljs-number">0x.4p2</span>; 
c = <span class="hljs-number">0xa.ffp3f</span>; 
d = <span class="hljs-number">0x1.0p2F</span>; 
e = <span class="hljs-number">0x1.0p2f</span>; 
f = <span class="hljs-number">0x1p1</span>; 
g = <span class="hljs-number">0x.3p4d</span>; 
h = <span class="hljs-number">0x1.2ep5D</span>; 
i = <span class="hljs-number">0x1.p2</span>;
```

for following tests:

```java 
long creditCardNumber = 1234_5678_9012_3456L;
long socialSecurityNumber = 999_99_9999L;
float pi = 3.14_15F;
long hexBytes = 0xFF_EC_DE_5E;
long hexWords = 0xCAFE_BABE;
long maxLong = 0x7fff_ffff_ffff_ffffL;
byte nybbles = 0b0010_0101;
long bytes = 0b11010010_01101001_10010100_10010010;
int n = 1234 + Contacts._ID;
float f = 0x1.4p2f;
double d = 0x.ep-6;
int octal = 0777;
float f = 2e3f;
double d = 1.2e4D;
a = 0x4fa6p2; 
b = 0x.4p2; 
c = 0xa.ffp3f; 
d = 0x1.0p2F; 
e = 0x1.0p2f; 
f = 0x1p1; 
g = 0x.3p4d; 
h = 0x1.2ep5D; 
i = 0x1.p2; 
```

So I miss something. For instance

```java
double d = 1.2e4D;
a = 0x4fa6p2; 
```

But I'm not sure why, can you spot the bug?

**Comment by yyyc514** [comment]
Please check the checkbox that allows me to push to your branch.

**Comment by 0xflotus** [comment]
> Please check the checkbox that allows me to push to your branch.

Where can I find this checkbox?

**Comment by yyyc514** [comment]
Never mind. I got it. Pull my changes. Now you need to look carefully at the rule ordering. The first matching rule wins.

**Comment by yyyc514** [comment]
This might be useful: https://regex101.com/

**Comment by yyyc514** [comment]
Ping.

**Comment by 0xflotus** [comment]
> This might be useful: https://regex101.com/

Yes I used this before. Will try to work on it later today or tomorrow.

File: src/languages/java.js [hunk 2]
```diff
@@ -18,32 +18,25 @@ export default function(hljs) {
...
-        '\\.([\\d]+[\\d_]+[\\d]+|[\\d]+)' +
-      ')' +
-      '([eE][-+]?\\d+)?' + // octal, decimal, float
-    ')' +
-    '[lLfF]?';
   var JAVA_NUMBER_MODE = {
     className: 'number',
-    begin: JAVA_NUMBER_RE,
+    variants: [
+      { begin: '\\b(0[bB][01]+[01_]*[01]+)[lL]?' }, // binary
```
Comment (yyyc514) [inline src/languages/java.js:32]: Please add tests for single digit variants of all these... I'm pretty sure you aren't handling that now.  For example:

`0b0` and `0b1` both fails with this regex.

Octal looks to have the same issue, I didn't look closely at the others.

Comment (yyyc514) [reply src/languages/java.js:32]: I think you just need to make the following part optional:

`\\b(0[bB][01]+([01_]*[01]+)?)[lL]?`

Or some such...

**Comment by yyyc514** [comment]
Ping.  This is a great improvement, just needs a little more work.

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
I'd consider adding tests first... ie, add all the single number combos for the different types you can think of... then see if they are highlighted properly - that way you're less likely to miss anything and this keep going back and forth. :-)

File: test/markup/java/numbers.txt [hunk 3]
```diff
@@ -21,3 +21,5 @@ f = 0x1p1;
 g = 0x.3p4d;
 h = 0x1.2ep5D;
 i = 0x1.p2;
+int i = 23;
+byte mask = 0x0f;
```
Comment (yyyc514) [inline test/markup/java/numbers.txt:25]: Don't we all need single digit test cases?

Comment (0xflotus) [reply test/markup/java/numbers.txt:25]: you are right, we're close

**Comment by 0xflotus** [comment]
I think of all other cases...

File: test/markup/java/numbers.txt [hunk 4]
```diff
@@ -7,3 +7,24 @@ long maxLong = 0x7fff_ffff_ffff_ffffL;
...
+g = 0x.3p4d;
+h = 0x1.2ep5D;
+i = 0x1.p2;
+int i = 23;
+byte mask = 0x0f;
+int i = 4;
+byte mask = 0xa;
+float f = 5.4;
+float f = 2e3;
+int n = 0b1;
```
Comment (yyyc514) [inline test/markup/java/numbers.txt:30]: Are things like:

```
float f = .2;
float f = 3.;
```

...allowed in Java?

File: src/languages/java.js [hunk 5]
```diff
@@ -31,7 +31,7 @@ export default function (hljs) {
     variants: [
       { begin: '\\b(0[bB][01]+([01_]*[01]+)?)[lL]?' }, // binary
       { begin: '\\b(0[0-7]+([0-7_]*[0-7]+)?)[dDfFlL]?' }, // octal
-      { begin: '\\b[\\d]+([\\d_]*[\\d]+)?[lL]?' }, // decimal
+      { begin: '\\b[\\d]+[\\d_]*[\\d]+[lL]?' }, // decimal
```
Comment (yyyc514) [inline src/languages/java.js:34]: Doesn't this require all decimals be 2 digits long now?

File: test/markup/java/numbers.txt (hunk 4 above)
Comment (0xflotus) [reply test/markup/java/numbers.txt:30]: yes it is, you're right

File: src/languages/java.js (hunk 5 above)
Comment (0xflotus) [reply src/languages/java.js:34]: It was only a test for me, will add this again now

Comment (yyyc514) [reply src/languages/java.js:34]: You don't have to push your tests. :-)

Comment (0xflotus) [reply src/languages/java.js]: I use Travis at the moment to test, because I haven't the repository checked out on this machine. Developing online with Github. Strange I know...

**Comment by 0xflotus** [comment]
Ok I have no idea how to handle this actually failing test cases. I will come back maybe later

File: src/languages/java.js (hunk 5 above)
Comment (yyyc514) [reply src/languages/java.js]: Oh yeah, that's going to be MUCH harder...

**Comment by yyyc514** [comment]
@0xflotus  What do you think?  Does this look decent?

I'm giving up on leading `.` notation for now, we can circle back to that later.  It's harder because there is no word boundary between space and `.` so `\b` won't match the beginning anymore... so you might need a whole new set of regexes. 

What would be nice is look-behind for a space, but we can't do that yet.

**Comment by 0xflotus** [comment]
Looks good to me. 

Maybe you are right. Dot Notation can also be a future feature.

**Comment by yyyc514** [comment]
Sweet.

Requesting additional review since I pretty much refactored this completely so now my code should really have more eyeballs on it.

File: src/languages/java.js [hunk 6]
```diff
@@ -18,32 +20,53 @@ export default function(hljs) {
...
+          /([pP][+-]?(\d+))?/,
+          /[fFdDlL]?/ // decimal & fp mixed for simplicity
+        )
+      },
+      // scientific notation
+      { begin: regex.concat(
+        /\b/,
+        regex.either(
+          /\d*\.[\d_]*\d+/, // 3.3e2
+          /\d+[\d_]*/ // 3e2
```
Comment (egor-rogov) [inline src/languages/java.js:57]: On these two lines `e2` in the comment doesn't look right, 'cause the regexps are for the numeric part only.
Also I'd change them to use `SEQUENCE_ALLOWING_UNDERSCORES(/\d/)` to be consistent with everything else.
Btw, is it correct that the first regex doesn't allow underscores before the dot?..

Comment (yyyc514) [reply src/languages/java.js:57]: I'm a little bit past caring at this point. :-)  I'll take a quick look but I'm not sure these are the same pattern as SEQUENCE_ALLOWING_UNDERSCORES (or should be).

I'll take a look at the comments also and see if anything occurs to me on improving them.

Comment (yyyc514) [reply src/languages/java.js]: You were right, they could be simplified.

**Comment by yyyc514** [comment]
@0xflotus Thanks for your hard work on this!
