### PR TITLE
(swift) New string grammar

### LINKED ISSUE #2819: (Swift) Incorrect highlighting of raw strings
[Editor: Dropping some notes for whoever picks this up] 

This needs to also take into account: 

- [x] SUBST (inline code) inside raw strings
- [x] the different forms of escaping inside raw strings
- [x] the different syntax of variable substitution (we should probably highlight this, right?)
- [x] extend the string markup tests quite a bit to go along with this
- [ ] could we handle arbitrary number of #### with END_SAME_AS_BEGIN? Worth it?

---

The following is a single raw string:

```swift
##"Use #" and "# to delimit a raw string."##
```

However, it's incorrectly highlighted as two separate strings. My guess is that highlight.js thinks the quotes in the middle close a string, then start a new one?

In general, the hashes around raw strings aren't highlighted in the same color as the string, so perhaps raw strings aren't supported at all yet?

### PR DESCRIPTION
**Pull request by svanimpe**
This is a rewrite of the grammar for strings in Swift. I’ve implemented the official grammar (https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#grammar_string-literal) and included support for raw strings with up to three hash signs.

I’m submitting this PR as a WIP to get some early feedback, as this is my first contribution. If the grammar looks good, I'll add a suite of unit tests and update the changelog/contributor list.

Fixes #2819 and replaces #2820.

### CODE REVIEW

File: src/languages/swift.js [hunk 1]
```diff
@@ -96,7 +82,114 @@ export default function(hljs) {
...
+    contains: [RAW3_ESCAPED_CHARACTER, RAW3_INTERPOLATION]
+  };
+  var STRING = {
+    className: 'string',
+    variants: [
+      MULTILINE_STRING,
+      RAW1_MULTILINE_STRING,
+      RAW2_MULTILINE_STRING,
+      RAW3_MULTILINE_STRING,
+      SINGLE_LINE_STRING,
```
Comment (joshgoebel) [inline src/languages/swift.js:182]: We'd really want to do this a bit more programmatically though:

```suggestion
    variants: [
      MULTILINE_STRING,
      RAW_MULTILINE_STRING("#"),
      RAW_MULTILINE_STRING("##"),
      RAW_MULTILINE_STRING("###"),
      SINGLE_LINE_STRING,
```

Etc. Then if we needed to support more or less of these in the future it would be a one line change... This same thinking would apply to single line string as well.

File: src/languages/swift.js [hunk 2]
```diff
@@ -96,7 +82,114 @@ export default function(hljs) {
...
+    className: 'subst',
+    begin: /\\##[0\\tnr"']|\\##u\{[0-9a-fA-F]{1,8}\}/
+  };
+  var RAW3_ESCAPED_CHARACTER = {
+    className: 'subst',
+    begin: /\\###[0\\tnr"']|\\###u\{[0-9a-fA-F]{1,8}\}/
+  };
+  var ESCAPED_NEWLINE = {
+    className: 'subst',
+    begin: /\\[\u0009\u0020]*(?:[\u000a\u000d]|\u000d\u000a)/
```
Comment (joshgoebel) [inline src/languages/swift.js:105]: Is this just `\r` and `\n`?  If so leets please use those common expressions instead.

I'm not sure what the 9 and 20 are? Can you clarify?

File: src/languages/swift.js [hunk 3]
```diff
@@ -96,7 +82,114 @@ export default function(hljs) {
...
+    className: 'subst',
+    begin: /\\[0\\tnr"']|\\u\{[0-9a-fA-F]{1,8}\}/
+  };
+  var RAW1_ESCAPED_CHARACTER = {
+    className: 'subst',
+    begin: /\\#[0\\tnr"']|\\#u\{[0-9a-fA-F]{1,8}\}/
+  };
+  var RAW2_ESCAPED_CHARACTER = {
+    className: 'subst',
+    begin: /\\##[0\\tnr"']|\\##u\{[0-9a-fA-F]{1,8}\}/
```
Comment (joshgoebel) [inline src/languages/swift.js:97]: Could we use `variants` to make these entirely different syntaxes a little more visible?

File: src/languages/swift.js (hunk 1 above)
Comment (joshgoebel) [reply src/languages/swift.js:182]: You may find `regex.concat` useful to help build your children regexes you'll need (see `regex.js`).

**Review by joshgoebel — CHANGES_REQUESTED** [review]
Awesome.  Already looking much better than the first pass! :-)

**Comment by svanimpe** [comment]
@joshgoebel I've pushed a new version that incorporates your feedback.

File: src/languages/swift.js [hunk 4]
```diff
@@ -120,7 +153,7 @@ export default function(hljs) {
           },
           {
             className: 'params',
-            begin: /\(/, end: /\)/, endsParent: true,
+            begin: /\(/, end: /\)/,
```
Comment (joshgoebel) [inline src/languages/swift.js:156]: What is the context here again?

File: src/languages/swift.js [hunk 5]
```diff
@@ -96,7 +84,52 @@ export default function(hljs) {
...
+    ]
+  });
+  var ESCAPED_NEWLINE = (rawDelimiter = "") => ({
+    className: 'subst',
+    begin: concat(/\\/, rawDelimiter, /[\t ]*(?:[\r\n]|\r\n)/)
+  });
+  var INTERPOLATION = (rawDelimiter = "") => ({
+    className: 'subst',
+    begin: concat(/\\/, rawDelimiter, /\(/),
+    end: /\)/
```
Comment (joshgoebel) [inline src/languages/swift.js:103]:
```suggestion
    className: 'subst',
    keywords: SWIFT_KEYWORDS,
    begin: concat(/\\/, rawDelimiter, /\(/),
    end: /\)/
```

Don't we need keywords here?

File: src/languages/swift.js [hunk 6]
```diff
@@ -96,7 +84,52 @@ export default function(hljs) {
...
+  var ESCAPED_CHARACTER = (rawDelimiter = "") => ({
+    className: 'subst',
+    variants: [
+      { begin: concat(/\\/, rawDelimiter, /[0\\tnr"']/) },
+      { begin: concat(/\\/, rawDelimiter, /u\{[0-9a-fA-F]{1,8}\}/) }
+    ]
+  });
+  var ESCAPED_NEWLINE = (rawDelimiter = "") => ({
+    className: 'subst',
+    begin: concat(/\\/, rawDelimiter, /[\t ]*(?:[\r\n]|\r\n)/)
```
Comment (joshgoebel) [inline src/languages/swift.js:98]: Much easier to read.

Is this variation and nuance in ordering necessary though? Is the order truly sometimes \n\r?  Or could this be simplified to `\r?\n` as is more common?

File: src/languages/swift.js (hunk 5 above)
Comment (svanimpe) [reply src/languages/swift.js:103]: That's something I was wondering too. The current grammar is a bit too general when it comes to keywords, and often misidentifies them. In this case, String interpolation only supports expressions, not statements, so most of the keywords in `SWIFT_KEYWORDS` shouldn't occur here.

File: src/languages/swift.js (hunk 6 above)
Comment (svanimpe) [reply src/languages/swift.js:98]: That's just what the official grammar says:

```
line-break → U+000A
line-break → U+000D
line-break → U+000D followed by U+000A
```

So `\r?\n` is not correct, as a single `\r` is allowed too.

File: src/languages/swift.js (hunk 5 above)
Comment (joshgoebel) [reply src/languages/swift.js:103]: Yes, I was flagging the obvious change in behavior this will have.

>  String interpolation only supports expressions, not statements, so most of the keywords in SWIFT_KEYWORDS shouldn't occur here.

If that's the case then this removal sounds reasonable...  (although if it breaks any of the existing tests it'll need to be looked at more carefully).

**Comment by joshgoebel** [comment]
> If the grammar looks good, I'll add a suite of unit tests and update the changelog/contributor list.

I think this is looking pretty good, feel free to finish it up.

**Comment by svanimpe** [comment]
Ready for a final review!

File: CHANGES.md [hunk 7]
```diff
@@ -7,6 +7,7 @@ New Languages:
 Language improvements:
 
 - enh(makefile): Add `make` as an alias (#2883) [tripleee][]
+- enh(swift) Improved grammar for strings (#2819) [Steven Van Impe][]
```
Comment (joshgoebel) [inline CHANGES.md:10]: You need to add link on line ~25 also.

Comment (svanimpe) [reply CHANGES.md:10]: Done

**Comment by svanimpe** [comment]
Is anything blocking this? I see "Changes requested" but no unresolved conversations.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
@svanimpe Nope. All good!
