### PR TITLE
enh(llvm) Improve grammar and align assembly like grammars

### LINKED ISSUE #2782: (llvm) types and blocks are parsed incorrectly
**Describe the issue**

The LLVM types and blocks are parsed incorrectly.

**Which language seems to have the issue?**
LLVM

**Are you using `highlight` or `highlightAuto`?**
No

**Sample Code to Reproduce**

```llvm
;; foooo
define i32 @mul_add(i32 %x, i32 %y, i32 %z) {
  entry:
    %tmp = mul i32 %x, %y
    %tmp2 = add i32 %tmp, %z
    %tmp3 = add i32 %tmp, 0
    ret i32 %tmp3
}
```

**Expected behavior**
I expect:

- [x] `define` to be a `.hljs-keyword` 
- [ ] `i32` to be a `.hljs-type` (its parsed as a keyword, all types are described here:  https://llvm.org/docs/LangRef.html#type-system)
- [x] `@mul_add` to be a `.hljs-title` (its a function name)
- [x] all the `%...` to be `.hljs-symbol` 
- [ ] `0` to be a `.hljs-literal`
- [x] `mul`, `add`, `ret` to be `.hljs-built_in` or `.hljs-keyword` (these are parsed as keywords)
- [ ] `entry:` is a block, so i'd expect this to be maybe a `.hljs-section` ? not sure 
- [x] `;; fooo` to be a comment

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2782.

### Changes

- [x] Variables are now highlighted as `variable`
- [x] `i8`, `i32`, etc now highlighted as `type` 
- [x] Labels are now highlighted as `symbol` (matching our other grammars)
- [x] Better comment detection
- [x] Restore relevance to strings
- [x] prevent false positives on `;` line endings as "comments"
- [x] Add very minimal `operator` and `punctuation` support

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

File: src/languages/llvm.js [hunk 1]
```diff
@@ -49,48 +96,28 @@ export default function(hljs) {
...
-      },
-      hljs.COMMENT(
-        ';', '\\n', {relevance: 0}
+      TYPE,
+      hljs.COMMENT(/;\s*$/,
+        // this matches "empty comments"...
+        // ...because it's far more likely this is a statement terminator in
+        // another language than an actual comment
+        { relevance: 0 }
       ),
```
Comment (allejo) [inline src/languages/llvm.js:105]: I think this regex might be a bit too greedy?

image

GitHub highlighting for reference

```llvm
;
;; foooo
define i32 @mul_add(i32 %x, i32 %y, i32 %z) {
  entry:
    %tmp = mul i32 %x, %y
    %tmp2 = add i32 %tmp, %z
    %tmp3 = add i32 %tmp, 0
    ret i32 %tmp3
}
```

**Review by allejo — CHANGES_REQUESTED** [review]

File: src/languages/llvm.js (hunk 1 above)
Comment (joshgoebel) [reply src/languages/llvm.js:105]: Better?

**Review by allejo — APPROVED** [review]
