### PR TITLE
fix(c/cpp) line continuation in single-line comments

### LINKED ISSUE #2757: (C) \ not respected
**Describe the issue**

**Which language seems to have the issue?**

`C`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**

https://jsfiddle.net/gm16s8nf/
```c
// this is a comment, but since I added a slash, \
this is part of it too
```

**Expected behavior**

In C, a '\\' character extends the current lined (effectively negating the following `\n` )
Since the second line is also part of the comment, it should be highlighted as such.

**Additional context**

### PR DESCRIPTION
**Pull request by klmr**
Resolves #2757 

### Changes

Use a custom definition for single-line comments in `c-like` instead of deferring to `hljs.C_LINE_COMMENT_MODE`. The only difference is a new nested mode that eats `\\\n`.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

File: src/languages/c-like.js [hunk 1]
```diff
@@ -18,6 +18,9 @@ export default function(hljs) {
   function optional(s) {
     return '(?:' + s + ')?';
   }
+  var C_LINE_COMMENT_MODE = hljs.COMMENT('//', '$', {
+    contains: [{begin: /\\\n/}]
```
Comment (joshgoebel) [inline src/languages/c-like.js:22]: Should this be `\\$` since we're always in multi-line mode?

File: src/languages/c-like.js [hunk 2]
```diff
@@ -18,6 +18,9 @@ export default function(hljs) {
   function optional(s) {
     return '(?:' + s + ')?';
   }
+  var C_LINE_COMMENT_MODE = hljs.COMMENT('//', '$', {
```
Comment (joshgoebel) [inline src/languages/c-like.js:21]:
```suggestion
  }
  // added for historic reasons because `hljs.C_LINE_COMMENT_MODE` does 
  // not include such support nor can we be sure all the grammars depending
  // on it would desire this behavior
  var C_LINE_COMMENT_MODE = hljs.COMMENT('//', '$', {
```

File: src/languages/c-like.js (hunk 1 above)
Comment (klmr) [reply src/languages/c-like.js:22]: `$` doesn’t work here (presumably since it’s a zero-width assertion, and the newline isn’t consumed?)

Comment (joshgoebel) [reply src/languages/c-like.js:22]: Duh. :-)

Comment (klmr) [reply src/languages/c-like.js:22]: In fact, `\\(?=$).` would work — but only in single-line mode, since `.` otherwise fails to match a newline.

**Review by joshgoebel — APPROVED** [review]
