### PR TITLE
enh(armasm) support // and # style line comments

### LINKED ISSUE #2408: (armasm) Line comments do not seem to be handled correctly
I was referred to make this bug report by Discord support after seeing this behavior in Discord, which uses highlight.js.

When highlighting ARM assembly, `# comments` and `// comments` are not treated as comments but instead as live code. This leads to incorrect highlighting that can span the entirety of the code, see the included screenshot.

[Example (from Discord)](https://i.imgur.com/o2DKPtC.png)

### PR DESCRIPTION
**Pull request by yyyc514**
Fixes #2408.

### CODE REVIEW

File: src/languages/armasm.js [hunk 1]
```diff
@@ -7,6 +7,16 @@ Category: assembler
 
 export default function(hljs) {
     //local labels: %?[FB]?[AT]?\d{1,2}\w+
+
+  const COMMENT = {
+    variants: [
+      hljs.COMMENT('^[ ]*(?=#)', '$', {relevance: 0, excludeBegin: true }),
```
Comment (egor-rogov) [inline src/languages/armasm.js]: Why just spaces, why not `\s`?

File: src/languages/armasm.js [hunk 2]
```diff
@@ -87,8 +96,8 @@ export default function(hljs) {
       {
         className: 'symbol',
         variants: [
+            {begin: '^[ ]*[a-z_\\.\\$][a-z0-9_\\.\\$]+:'}, //GNU ARM syntax
```
Comment (egor-rogov) [inline src/languages/armasm.js]: The same question about white-spaces here.

File: src/languages/armasm.js (hunk 1 above)
Comment (yyyc514) [reply src/languages/armasm.js]: `\s` eats new lines also and results in weirdness like the divs opening on the line before because the comment "includes" the newline.

File: src/languages/armasm.js (hunk 2 above)
Comment (yyyc514) [reply src/languages/armasm.js]: Same answer.

File: src/languages/armasm.js (hunk 1 above)
Comment (egor-rogov) [reply src/languages/armasm.js]: Ok. How about adding `\t` then?

Comment (yyyc514) [reply src/languages/armasm.js]: We could do that.  Are we good to go if we add support for tabs?

Comment (egor-rogov) [reply src/languages/armasm.js]: Yep.
