### PR TITLE
enh(sql) newer more generic, less context dependent SQL grammar

### LINKED ISSUE #2744: Rebooting the generate purpose "SQL" grammar
**Is your request related to a specific problem you're having?**

Lots of people on StackOverflow (which recently switched to HLJS for highlighting) are having a myriad of issues with our SQL grammar:

- too context sensitive, doesn't highlight partial statements (so it appears very random and haphazard)
- Considers `#` comments, despite that only being true in MySQL (
A clear and concise description of the problem itself. Ex. I'm always frustrated when [...]
- Doesn't highlight variables

Upon further inspection the grammar has just become hugely bloated with "everything and the kitchen sink" thrown into it.  I found a few keywords not related to major database vendors at all but rather other software that uses a SQL like query language, etc...

**The solution you'd prefer / feature you'd like to see added...**

The SQL grammar should be minimal (maintainable) and support "common" SQL... if all SQL variants support a feature commonly it should be included.  It should not be a dumping ground for every random SQL keyword.  We should leave vendor specific grammars for handling more complex things. (and vendor specific variants like MySQL's `#` commenting)

Just "fixing" the grammar (to ignore context and highlight keywords more broadly) BADLY breaks auto-detect for many languages since SQL has so many common keywords. It also does not solve the commenting issue with MySQL comments...
Rather than tuning all (or many of) these keywords to 0 (and still not being entirely sure what effect this might have in the real world) simply rebooting the grammar (and reducing 2 letter keywords to relevance 0) solves this problem nicely.

The PR in question pairs down the "sql" grammar and deprecates the old grammar into "sql_more" and adds "mysql" and "oraclesql" aliases, paving the way for long-term splitting these out into maintained 3rd party grammars.  Someone wanting the "old" behavior can get it back with 2-3 lines of code (load the sql_more grammar, registerAlias it back to `sql`).

**Any alternative solutions you considered...**

None.  I wanted to do this before but we decided not to but the recent discussions on StackOverflow brought me back to this.  I'd like to find a way to do this in the 10.x series.  It does alter the behavior of `SQL` but since it still does highlight SQL (just fewer keywords) and is also an improvement in many other ways I think it's valid to slip into a minor release.

**To restore prior behavior**

```ts
let sql = hljs.getLanguage("sql_more");
sql.disableAutodetect = false
hljs.registerAliases("sql",sql);
```

### LINKED ISSUE #2876: (sql) highlight.js is breaking on quote escape sequences
**Describe the issue**

It looks like things start to go awry after a string escape sequence at the end of some dynamic SQL:
```tsql
IF @overwrite = 1
BEGIN	
    -- Generate the dynamic SQL that will drop the view on the remote database
    DECLARE @DropViewStatement NVARCHAR(MAX) =
        'EXEC ' + QUOTENAME(@DatabaseName) + '.sys.sp_executesql N''DROP VIEW IF EXISTS ' + QUOTENAME(@ViewName) + ';'';'
    EXEC (@DropViewStatement);
END
```

**Which language seems to have the issue?**
I've tried both "sql" and "tsql" - not sure which is most appropriate here, but both behave the same.

**Are you using `highlight` or `highlightAuto`?**
highlight, as far as I know (whatever is used on stackoverflow when you explicitly set the code block language).
...

**Sample Code to Reproduce**
I've created a codepen example here: https://codepen.io/alainbryden/pen/LYZvBXz

image

**Expected behavior**
It looks like GitHub gets it right, so it might serve as an example to get things corrected. (Also, a good excuse to drop the full example in this ticket):
```tsql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:        Alain Bryden
-- Create date: 2020-11-17
-- Description:    Copy a view from the current database to another one
-- =============================================
ALTER PROCEDURE [dbo].[usp_Copy_View_To_Database]
    @ViewName SYSNAME, -- The name of the view to copy over
    @DatabaseName SYSNAME, -- The name of the database to copy the view to    
    @overwrite bit = 1 -- Whether to overwrite any existing view
AS
    IF DB_ID(@DatabaseName) IS NULL  /*Validate the database name exists*/
    BEGIN
       RAISERROR('Invalid Destination Database Name passed',16,1)
       RETURN
    END
    
    SET NOCOUNT ON

    IF @overwrite = 1
    BEGIN    
        -- Generate the dynamic SQL that will drop the view on the remote database
        DECLARE @DropViewStatement NVARCHAR(MAX) =
            'EXEC ' + QUOTENAME(@DatabaseName) + '.sys.sp_executesql N''DROP VIEW IF EXISTS ' + QUOTENAME(@ViewName) + ';'';'
        EXEC (@DropViewStatement);
    END

    DECLARE @ViewDefinition NVARCHAR(MAX);
    SELECT @ViewDefinition = definition FROM sys.sql_modules WHERE [object_id] = OBJECT_ID(@ViewName);
    -- Check for a mismatch between the internal view name and the expected name (TODO: Resolve this automatically?)
    IF @ViewDefinition NOT LIKE ('%' + @ViewName + '%')
    BEGIN
       DECLARE @InternalName NVARCHAR(MAX) = SUBSTRING(@ViewDefinition, 3, CHARINDEX(char(10), @ViewDefinition, 3)-4);
       PRINT ('Warning: The view named '+@ViewName+' has an internal definition name that is different ('+@InternalName+'). This may have been caused by renaming the view after it was created. You will have to drop and recreate it with the correct name.')
    END
    -- Substitute any hard-coded references to the current database with the destination database
    SET @ViewDefinition = REPLACE(@ViewDefinition, db_name(), @DatabaseName); 
    -- Generate the dynamic SQL that will create the view on the remote database
    DECLARE @CreateViewStatement NVARCHAR(MAX) =
        'EXEC ' + QUOTENAME(@DatabaseName) + '.sys.sp_executesql N''' + REPLACE(@ViewDefinition,'''','''''') + ''';'
    --PRINT '@CreateViewStatement: ' + @CreateViewStatement -- Can be used for debugging
    -- Execute the create statement
    EXEC (@CreateViewStatement);
```

**Additional context**
Originally discovered when posting an answer on stackoverflow here: https://stackoverflow.com/a/64880979/529618

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2744. 

- much simpler SQL grammar
- less context dependent so SQL snippets can be better highlighted
- adds variable support
- adds operator support
- bloated SQL grammar moved to `sql_more` and aliased as "mysql" and "oraclesql"
- reduces scope of the SQL grammar to "common" SQL
- moves prior SQL support into `sql_more` and adds `mysql` and `oraclesql` aliases

---

- Resolves #2876.

### CODE REVIEW

File: src/languages/sql_more.js [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+- Oracle SQL should be factored into it's own 3rd party grammar.
+- MySQL should be factored out into it's own 3rd party grammar.
+
+*/
+
+export default function(hljs) {
+  var COMMENT_MODE = hljs.COMMENT('--', '$');
+  return {
+    name: 'SQL (more)',
+    aliases: ["mysql", "oraclesql"],
```
Comment (egor-rogov) [inline src/languages/sql_more.js:23]: I'd suggest `oracle`, because `MySQL` and `Oracle` are the names of the database systems.

**Review by egor-rogov — COMMENTED** [review]
Yes. this work is long needed... Although it brings a lot of questions.

First of all: what should be the criteria? You wrote
> If pretty much every single SQL server includes supports, then it's a canidate.

But should we consider the SQL Standard?

Second. Should we highlight known function names? If yes, which ones? I thought of it in the context of `pgsql` grammar and decided not to highlight function calls at all. PostgreSQL has tons of functions and you can of course write your own. Highlighting just some of function calls looks ugly to me. And we unfortunately cannot tell function call from, say, table declaration.

Third. List of keywords must be checked carefully. For example, `varchar2` is Oracle-only datatype, `last_insert_rowid` is SQLite-only function etc. I'll try to check them all but it needs time.

**Comment by joshgoebel** [comment]
> But should we consider the SQL Standard?

It doesn't help that the "standard" isn't really available for viewing that I know of... am I wrong?

> Should we highlight known function names? If yes, which ones?

The ones in the standard?

> Highlighting just some of function calls looks ugly to me. 

That's where I think we're helped if this is scoped to the "standard"... that should limit the number of functions significantly I'd think.  And if you're really just talking about user defined vs built-ins... I'm not sure why that's an issue... in many grammars we highlight built-in functions but not user defined ones...

> And we unfortunately cannot tell function call from, say, table declaration.

Can't we?  `CREATE TABLE` is pretty clear. :-)  There may indeed be too many contexts to properly detect function dispatch, I haven't given it much thought.

> For example, varchar2 is Oracle-only datatype

I specifically left the list of datatypes "wide".  I have no idea what data types might be in the "standard"

> Third. List of keywords must be checked carefully. For example ... [snip] ... last_insert_rowid is SQLite-only function etc. 

Well, again the lack of available docs on an actual "standard" is really an issue... so I actually based this off of SQLite as a "lowest common denominator"... I was fully expecting we'd grown and improve this slightly after the first pass.  Is there actual free/public documentation somewhere of the actual SQL standard?

**Comment by joshgoebel** [comment]
Honestly I'm a little less interested in the "purity" of this rather than the reduction in scope and having some idea what's in it (plus making it easier to maintain)... just googling 1000 keywords from the existing SQL one by one to figure out what was from what was NOT on my bucket list.

I definitely would like to avoid "keyword of the week" contributions (from random SQL variants) to the grammar going forward though. :-)  I kind of imagined something like:

- keyword is proposed/suggested
- do all major DBs support?
- If yes, then add.
- If no, add to vendor specific grammar.

**Comment by egor-rogov** [comment]
> It doesn't help that the "standard" isn't really available for viewing that I know of... am I wrong?

Full document is available for $$$. But e.g. https://modern-sql.com/standard gives a great list of freely available resources, including BNF grammar and working drafts of the standard. It is enough for sure.

>> And we unfortunately cannot tell function call from, say, table declaration.
>
> Can't we? `CREATE TABLE` is pretty clear. :-) There may indeed be too many contexts to properly detect function dispatch, I haven't given it much thought.

Right, too many contexts. I remember I gave up when working on `pgsql`.

> Honestly I'm a little less interested in the "purity" of this rather than the reduction in scope and having some idea what's in it (plus making it easier to maintain)...

Well, I see a problem in it. If the `sql` grammar is purified down to the standard + "common denominator", it is easy to reject complains like "this is highlighted incorrectly for my database system". But if you left, e.g. `varchar2`, but get rid of `CONNECT BY`, it is more difficult to justify. It will look like we simply messed up Oracle support for no reason.

"Common denominator" is also needed in addition to the standard. E. g. there is no such thing as index in the standard (and hence no `CREATE INDEX`), although it is supported by each and every DBMS.

> I definitely would like to avoid "keyword of the week" contributions

Absolutely agree.

**Comment by joshgoebel** [comment]
>  If the sql grammar is purified down to the standard + "common denominator", it is easy to reject complains like "this is highlighted incorrectly for my database system".

Yeah... I follow.  I was just laying out my thoughts.  If this ends up just LCD that's fine...

**Comment by joshgoebel** [comment]
@egor-rogov I think this is not going to be super easy... For example I'm familiar with BLOB, but not "BINARY LARGE OBJECT"... so it seems there may be a lot of cases where the standard says one thing but then the implementation is totally different... so having "BINARY LARGE OBJECT" in our grammar wouldn't accomplish much at all.

I think I could get a handle on the datatypes and AGG functions, but that still leaves other built in functions and then the large list of "keywords" in general.

**Comment by joshgoebel** [comment]
And just to make it harder there is Google's "Standard SQL": https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting

No idea how standard it is.

**Comment by joshgoebel** [comment]
@egor-rogov I'm fine dropping all the non-aggregate functions for a first pass if you think that's simpler... but how do you want to handle the keyword list?  I did some googling plus my knowledge of SQL and took a quick pass and flagged almost half of the keywords as "good to go"...  would you want to do the same?

Then at the end we just remove those we are unsure of?

Any chance we could have this cleaned up in the next week?  I was hoping to release 10.3 around mid-month, but I suppose I could push it off a bit further.

**Comment by egor-rogov** [comment]
> And just to make it harder there is Google's "Standard SQL": https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting
> No idea how standard it is.

It is not.

>  I did some googling plus my knowledge of SQL and took a quick pass and flagged almost half of the keywords as "good to go"...  would you want to do the same?

Yes I'm going to do the same. Not sure how much time will it take, let's see.

**Comment by egor-rogov** [comment]
Some thoughts on keywords.

SQL has so-called _reserved words_, most of which can go straight to our `keywords`: https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#reserved-word
Although there are such words as `AVG`, `COUNT` etc, which should rather be `built-ins`.

Also SQL has so-called _non-reserved words_, which can have special meaning in some contexts, while can be used freely in other contexts: https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#non-reserved-word

The latter are harder ones... E. g. `KEY` is a non-reserved word. In `PRIMARY KEY` it is a keyword, but you can rightfully create a table with `key` column.

**Comment by egor-rogov** [comment]
I made a quick pass through the datatypes.
The following are non-standard: `bool` (?), `void` (PostgreSQL), `number` (Oracle).

What class should we use for datatypes? We have `type` class, which seems to be a better choice to me than `built-in`.

Now, the standard has the following large range of datatypes (a lot of nultiword combos):
```
-- character

character
char
character varying
char varying
varchar

national character
national char
nchar
national character varying
national char varying
nchar varying

-- LOBs

character large object
char large object
clob
national character large object
nchar large object
nclob
binary large object
blob

-- binary

binary
binary varying
varbinary

-- numbers

numeric
decimal
dec
smallint
integer
int
bigint

float
real
double precision

decfloat

-- boolean

boolean

-- date & time

date
time
timestamp
time
time ... with timestamp
time ... without timestamp
timestamp
timestamp ... with timestamp
timestamp ... without timestamp

-- others

interval
row
ref
scope
array
multiset
```

Note that character types can have length specifier in form of `\d+ CHARACTERS` or `\d+ OCTETS`. How these two keywords should be highlighted?..

**Comment by joshgoebel** [comment]
```
time ... with timestamp
time ... without timestamp
```

Do you mean timezone?

**Comment by joshgoebel** [comment]
```
row
ref
scope
array
multiset
```

I'm not very familiar with these...  do you think they all should be built-in/datatypes rather than keywords?

**Comment by joshgoebel** [comment]
> The latter are harder ones... E. g. KEY is a non-reserved word. In PRIMARY KEY it is a keyword, but you can rightfully create a table with key column.

I'm ok with special casing these "pairs" if there aren't too many... that way we decrease false positives in auto-detect against other languages as well as making the grammar smarter.

**Comment by joshgoebel** [comment]
> Also SQL has so-called non-reserved words, which can have special meaning in some contexts, while can be used freely in other contexts:

Ok, yikes, that's a ton.  I think I'm in favor of just leaving almost all of these out of the grammar...  maybe pull in a few that are SUPER common (like KEY in FOREIGN KEY, PRIMARY KEY, etc) that we can specify contextual rules... I didn't see a lot of others that jumped out at me though.

**Comment by joshgoebel** [comment]
> The latter are harder ones... E. g. KEY is a non-reserved word. In PRIMARY KEY it is a keyword, but you can rightfully create a table with key column.

You only mean unquoted without context?  Surely I can name a column some of these reserved words if it was properly quoted, yes?

**Comment by egor-rogov** [comment]
> Do you mean timezone?

Oh, of course.

>> ```
>> row
>> ref
>> scope
>> array
>>multiset
>>```
>
> I'm not very familiar with these... do you think they all should be built-in/datatypes rather than keywords?

Hmm... Looks like we don't really want any of those except `ROW`. They are intended for use in procedural languages like Ada, PL/I etc. I don't think we want to support all of those languages inside sql grammar (:

`ROW` is a datatype, like `INTERVAL`.

>  I think I'm in favor of just leaving almost all of these [non-reserved keywords] out of the grammar...

I don't think so. Probably we'd better add them as keywords by default and move some of them to "combos"... But don't hurry, give me some time to have a look.

> You only mean unquoted without context? Surely I can name a column some of these reserved words if it was properly quoted, yes?

Sure. Quoted identifiers are easy.

**Comment by egor-rogov** [comment]
As `TIMEZONE` not in the keywords list, I think `WITH TIMEZONE` and `WITHOUT TIMEZONE` should be in MULTI_WORD_BUILT_INS.

**Comment by egor-rogov** [comment]
I've identified the following functions (or expressions that are not technically functions, but otherwise look like functions) in the list of reserved keywords:
```
ABS
ACOS
ARRAY_AGG
ASIN
ATAN
AVG
CAST
CEIL
CEILING
COALESCE
COS
COSH
COVAR_POP
COVAR_SAMP
CUME_DIST
DENSE_RANK
DEREF
ELEMENT
EXP
FIRST_VALUE
FLOOR
JSON_ARRAY
JSON_ARRAYAGG
JSON_EXISTS
JSON_OBJECT
JSON_OBJECTAGG
JSON_QUERY
JSON_TABLE
JSON_TABLE_PRIMITIVE
JSON_VALUE
LAG
LAST_VALUE
LISTAGG
LN
LOG
LOG10
LOWER
MAX
MIN
MOD
NTH_VALUE
NTILE
NULLIF
PERCENT_RANK
PERCENTILE_CONT
PERCENTILE_DISC
POSITION
POSITION_REGEX
POWER
RANK
REGR_AVGX
REGR_AVGY
REGR_COUNT
REGR_INTERCEPT
REGR_R2
REGR_SLOPE
REGR_SXX
REGR_SXY
REGR_SYY
ROW_NUMBER
SIN
SINH
SQRT
STDDEV_POP
STDDEV_SAMP
SUBSTRING
SUBSTRING_REGEX
SUM
TAN
TANH
TRANSLATE
TRANSLATE_REGEX
TREAT
TRIM
TRIM_ARRAY
UNNEST
UPPER
VALUE_OF
VAR_POP
VAR_SAMP
WIDTH_BUCKET
```

Maybe there are more. What about them? Should we highlight them as function calls?

Also there are some expressions that also look like functions, but don't require `()` after them. Those are mainly `CURRENT_*`. And what about them?..

**Comment by joshgoebel** [comment]
> As TIMEZONE not in the keywords list, I think WITH TIMEZONE and WITHOUT TIMEZONE should be in MULTI_WORD_BUILT_INS.

Sure.

> What about them? Should we highlight them as function calls?

Sure.

> Also there are some expressions that also look like functions, but don't require () after them. Those are mainly CURRENT_*. And what about them?..

Why not just keywords?  Are you saying you're now in favor of only CURRENT_* and this list and letting any others in the non-reserved just fall to the floor?

**Comment by egor-rogov** [comment]
> Why not just keywords? Unless you're saying the functions should be built-ins... moving the data types to "type". So if that was the question then I'm fine with CURRENT_* being built-in...

Hm... Standard calls them "functions". And some of them can be used either with or without parens. E. g. `current_time` or `current_time(3)` (time precision).

Here is the list of strictly-no-parens to start with:
```
CURRENT_CATALOG
CURRENT_DATE
CURRENT_DEFAULT_TRANSFORM_GROUP
CURRENT_PATH
CURRENT_ROLE
CURRENT_SCHEMA
CURRENT_TRANSFORM_GROUP_FOR_TYPE
CURRENT_USER
SESSION_USER
SYSTEM_TIME
SYSTEM_USER
```
And here are the others:
```
CURRENT_TIME
LOCALTIME
CURRENT_TIMESTAMP
LOCALTIMESTAMP
```

**Comment by egor-rogov** [comment]
Now, let's decide what to do with expressions like `extract`.
The syntax is like follows:
```
EXTRACT ( field FROM expression )
```
Here "field" is one of the following:
```
TIMEZONE_HOUR
TIMEZONE_MINUTE
YEAR
MONTH
DAY
HOUR
MINUTE
SECOND
```

Okay, `FROM` is a keyword for sure. What about `EXTRACT` and field names?
Looks like `EXTRACT` should be a `function`, just like `SUBSTRING`, which also has the fancy syntax like `SUBSTRING ( expression FROM start_position FOR length USING units )`.
And field names maybe built-ins? Or keywords? They all are reserved keywords, but intuitively I'd like to "draw a line" somewhere, as you suggested.

**Comment by joshgoebel** [comment]
> Standard calls them "functions". And some of them can be used either with or without parens.

I'm lost, what are we talking about?  Are you talking about whether we color them `built_in` or `keyword`?  I'm inclined to just leave them in the original groups (per the reference page) and see if anyone cares about the distinction later.

**Comment by joshgoebel** [comment]
> What do you think about leaving SQL/XML and SQL/JSON out of scope? Both are languages in themselves...

HAHA, I'm fine with this... sounds like sublanguages or submode problem anyways.

**Comment by joshgoebel** [comment]
I'm tempted to just remove the separate lists and have ONLY a single reserved word list... and do it all contextually... thoughts?

```
[word]      # must be keyword (no dispatch)
[word](    # built_in/func
[word] (   # built_in/func
```

**Comment by joshgoebel** [comment]
@egor-rogov The COMBOS are potentially for relevance though I haven't gone there yet. "create table" screams SQL where-as "table create" not so much.

**Comment by joshgoebel** [comment]
I'm really temped to add a UPPERCASE = keyword rule as well since this is our generic grammar...

**Comment by joshgoebel** [comment]
> And field names maybe built-ins? Or keywords? 

I say just leave them keywords for now.

**Comment by joshgoebel** [comment]
@egor-rogov Any thoughts on last pass?

**Comment by egor-rogov** [comment]
I really want to get back to it, but I won't have enough time to concentrate in the next 3 weeks or so.

**Comment by joshgoebel** [comment]
@egor-rogov  Probably going to push 10.5 soon, any chance you have any time to revisit this?

File: src/languages/sql.js [hunk 2]
```diff
@@ -1,168 +1,647 @@
...
+    className: 'string',
+    variants: [
+    {
+      begin: '\'', end: '\'',
+      contains: [{begin: '\'\''}]
+    },
+    {
+      begin: '"', end: '"',
+      contains: [{begin: '""'}]
+    },
```
Comment (egor-rogov) [inline src/languages/sql.js:37]: Double quoted text is not a string, it is an identifier. Like `CREATE TABLE "my table" ( ...)`.

File: src/languages/sql.js [hunk 3]
```diff
@@ -1,168 +1,647 @@
...
+    {
+      begin: '`', end: '`'
+    }
```
Comment (egor-rogov) [inline src/languages/sql.js:40]: Backticks don't have any special meaning in SQL.

File: src/languages/sql.js [hunk 4]
```diff
@@ -1,168 +1,647 @@
...
+    "upper",
+    "value_of",
+    "var_pop",
+    "var_samp",
+    "width_bucket",
+  ];
+
+  const COMBOS = [
+    "create table", // no need, both are keywords
+    "insert into", // no need, both are keywords
```
Comment (egor-rogov) [inline src/languages/sql.js:556]: As written in the comments, there's no need in these two combos.
\+ `alter table` below.
\+ `add constraint` also, as long as `add` is in the keywords.

File: src/languages/sql.js [hunk 5]
```diff
@@ -1,168 +1,647 @@
...
+  const FUNCTIONS = RESERVED_FUNCTIONS;
+
+  const KEYWORDS = [...RESERVED_WORDS, ...NON_RESERVED_WORDS].filter((keyword) => {
+    return !RESERVED_FUNCTIONS.includes(keyword);
+  });
+
+  const VARIABLE = {
+    className: "variable",
+    begin: /@[a-z0-9]+/,
+  };
```
Comment (egor-rogov) [inline src/languages/sql.js:582]: It's not in the standard. Looks like MSSQL?

**Review by egor-rogov — CHANGES_REQUESTED** [review]
Here are some comments regarding the code. I'll have to recheck some more keywords etc, and will give more feedback later.

**Comment by egor-rogov** [comment]
> > Standard calls them "functions". And some of them can be used either with or without parens.
>
> I'm lost, what are we talking about? Are you just talking about whether we color them built_in or keyword?

I am trying to say that it's natural (to me at least) to highlight, say, `extract(...)` as function call, like any other functions like `count()` etc. Currently it's `built_in` (but perhaps we'll need another class for function calls someday).
Disagree?

File: src/languages/sql.js (hunk 2 above)
Comment (joshgoebel) [reply src/languages/sql.js:37]: Wait, what...

```
select "hey what is this if not a stirng"
```

Is that not a string?  We don't have a CSS class for 'identifer'... we have `variable`.  But you're just confusing me here.  Or are you saying in SOME cases it's an identifier... because right now at first glance it seems "ok" to just highlight all these as strings.

File: src/languages/sql.js (hunk 3 above)
Comment (joshgoebel) [reply src/languages/sql.js:40]: Again, this isn't pure SQL... the idea is to also support common things (variables, etc) that are easy to support (for  a slightly more well rounded SQL grammar) IF those things don't cause problems across different engines.  So if backticks are strings in some engines and never used in others, this is a nice to have.

The problem comes with like `#` comments, which mean one thing in MySQL and something else in Oracle, etc... so they can't be part of this grammar, but I think backticks can.

File: src/languages/sql.js (hunk 4 above)
Comment (joshgoebel) [reply src/languages/sql.js:556]: _This is to prevent false positives and improve auto-detect._  `create table` is VERY different from `table create`...

File: src/languages/sql.js (hunk 5 above)
Comment (joshgoebel) [reply src/languages/sql.js:582]: Again, see comment on supporting simple things to improve the grammar that are not incompatible across engines.

**Comment by joshgoebel** [comment]
> I am trying to say that it's natural (to me at least) to highlight, say, extract(...) as function call

We do already, it's in RESERVED_FUNCTIONS.

> Currently it's built_in 

Right, that's what we typically highlight functions as...

> (but perhaps we'll need another class for function calls someday).

We need a "function dispatch" which is mention in other threads... and that would prevent the hard coded list entirely and we could just match any `BLAH()` pattern as a function.  I'm not sure there is a strong need to highlight functions as functions if they have no ()... but we could cross that bridge when we get there.

Personally I feel like this is "good enough" to merge and we can continue to tweak over time.  Otherwise it's going to miss 10.5 and get pushed to 2021. :(

File: src/languages/sql.js (hunk 4 above)
Comment (egor-rogov) [reply src/languages/sql.js:556]: Got it.

File: src/languages/sql.js (hunk 2 above)
Comment (egor-rogov) [reply src/languages/sql.js:37]: It is _not_ a string (:

```
postgres=# select "hey what is this if not a stirng";
ERROR:  column "hey what is this if not a stirng" does not exist
```

The same is true for Oracle (and from the standard's perspective).
AFAIK MySQL accepts strings in double quotes. and MSSQL has a switch for this behavior.

Comment (egor-rogov) [reply src/languages/sql.js:37]: It is an identifier, so it shouldn't be highlighted.

Comment (joshgoebel) [reply src/languages/sql.js:37]: Ah, you're saying it's another MySQL ism...

```sql
-- identifier
select "hey what is this if not a stirng";
-- string
select 'hey what is this if not a stirng';
```

yes?

Comment (joshgoebel) [reply src/languages/sql.js:37]: Lack of standards across databases is so annoying. :)

File: src/languages/sql.js (hunk 3 above)
Comment (egor-rogov) [reply src/languages/sql.js:40]: I really can see no point in this.
Following this logic, you can easily justify addition of _some_ non-standard keywords, popular in _some_ db engines. It doesn't cause problems, ugh?
And this takes us back to our discussion: https://github.com/highlightjs/highlight.js/pull/2740#issuecomment-706697239

File: src/languages/sql.js (hunk 5 above)
Comment (egor-rogov) [reply src/languages/sql.js:582]: And there are also things like `$1` or `:A`... In _some_ databases.

Comment (joshgoebel) [reply src/languages/sql.js:582]: If someone mentions them later we can review whether they make sense. :)  This has been pending far too long given how badly broken SQL is now.

File: src/languages/sql.js (hunk 3 above)
Comment (joshgoebel) [reply src/languages/sql.js:40]: > I really can see no point in this.

The point is a grammar that "just works" in more situations.  A simple rule to handle quoting (if there are no other conflicts) is not at all the same as the murky swamp that is adding random keywords (since they cause real problems with auto-detect, WRONG highlighting, etc).  If one popular DB uses backtick for quoting but no others then I don't see the harm is supporting it (though perhaps we should add a comment).

See my comment at the top of the file:

```
SQL is intended to highlight basic/common SQL keywords and expressions

- If pretty much every single SQL server includes supports, then it's a canidate.
- It is NOT intended to include tons of vendor specific keywords (Oracle, MySQL,
  PostgreSQL) although the list of data types is purposely a bit more expansive.
```

The PRIMARY goal was to simplify the grammar and get us away from the unmaintained swamp of vendor specific keywords AND _vendor specific features that cause conflicts across different SQL engines._

The goal never was to draw a hard line in the sand and say "only the SQL standard, period".  Having an expanded list of datatypes makes this more useful for highlighting CREATE TABLE across multiple databases... but datatypes is scope a lot tighter than "any and all keywords", so I'm ok if it includes VARCHAR2, etc...

**Comment by joshgoebel** [comment]
> Following this logic, you can easily justify addition of some non-standard keywords, popular in some db engines. It doesn't cause problems, ugh?

**Also, just to be 100% clear the problem was never non-standard keywords.**  The problem was that the current list was unmaintainable and would take HOURS to google/sort them... Now I don't want to start adding a ton of keywords back to this - I think it should stay simple (and encourage 3rd party grammars) - but if the vendor-specific keywords had all been nicely grouped into ORACLE_KEYWORDS, MYSQL_KEYWORDS, etc... I would have had far less issue and there would have been far less need for this reboot.

**Comment by egor-rogov** [comment]
> > I am trying to say that it's natural (to me at least) to highlight, say, extract(...) as function call
> 
> We do already, it's in RESERVED_FUNCTIONS.

Yeah, great. And what about, say, `localtime`? According to the standard, you can use it as `localtime(3)` or `localtime` (no parens). Should it be built_in in the first case? And in the second case?
(My answer is _yes_ for both.)

> We need a "function dispatch" which is mention in other threads... and that would prevent the hard coded list entirely and we could just match any `BLAH()` pattern as a function. I'm not sure there is a strong need to highlight functions as functions if they have no ()... but we could cross that bridge when we get there.

Consider `CREATE TABLE foo(a integer);`. I can't see a (easy) way to tell `foo` from function call. And I'm afraid there are other cases like this.

**Comment by joshgoebel** [comment]
> Consider CREATE TABLE foo(a integer);. I can't see a (easy) way to tell foo from function call.

Well it's immediately proceeded by CREATE TABLE for one, but this is a problem for another day.

**Comment by joshgoebel** [comment]
> According to the standard, you can use it as localtime(3) or localtime (no parens). Should it be built_in in the first case? And in the second case?
(My answer is yes for both.)

That's just adding `built_in: FUNCTIONS` to `keywords`... I'm find with doing that.

File: src/languages/sql.js (hunk 2 above)
Comment (egor-rogov) [reply src/languages/sql.js:37]: Yes.
It's annoying, right...

Comment (joshgoebel) [reply src/languages/sql.js]: Ok, removed highlighting of quoted identifers.

File: src/languages/sql.js (hunk 3 above)
Comment (egor-rogov) [reply src/languages/sql.js]: And again, as soon you add `varchar2` to the list of datatypes, someone from Oracle world will come crying "Hey, I still see varchar2, so where are all the other Oracle stuff you had"?
What is the benefit of having `varchar2` but not `prior` or `rownum`?

Comment (joshgoebel) [reply src/languages/sql.js]: If you insist I'll remove it from v1 of this, but I'm much more in favor of "causes no harm" rather than "exactly the SQL spec only, period".  Long lists of unmaintainable keywords do cause harm and muddle the auto-detect.

File: src/languages/sql.js [hunk 6]
```diff
@@ -27,18 +27,24 @@ export default function(hljs) {
...
+      {
+        begin: /`/,
+        end: /`/
+      }
+    ]
+  };
+  const QUOTED_IDENTIFIER = {
+    begin: /"/,
+    end: /"/,
+    contains: [ { begin: /""/ } ]
```
Comment (joshgoebel) [inline src/languages/sql.js:46]: @egor-rogov Any idea if this escaping is a thing for quoted identifiers or if it can be removed?

**Comment by egor-rogov** [comment]
> Now I don't want to start adding a ton of keywords back to this - I think it should stay simple (and encourage 3rd party grammars) - but if the vendor-specific keywords had all been nicely grouped into ORACLE_KEYWORDS, MYSQL_KEYWORDS, etc... I would have had far less issue and there would have been far less need for this reboot.

You contradict yourself (: 
Having vendor-specific keywords/types/etc does _not_ encourage 3rd party grammars. It encourages complaints on poor support of XXX database.

File: src/languages/sql.js (hunk 6 above)
Comment (egor-rogov) [reply src/languages/sql.js:46]: The escaping is correct. But since identifiers are not to be highlighted, you can safely remove all this.

**Comment by egor-rogov** [comment]
> That's just adding `built_in: FUNCTIONS` to `keywords`... I'm fine with doing that. But if the problem is it's only "some" functions (which I believe is correct) then are you wanting to provide me with that list of WHICH ones?

https://github.com/highlightjs/highlight.js/pull/2740#issuecomment-707861055

> Do we really want to maintain that list long-term if there is no official list of these but we're doing it "by sight"?

I think the list is pretty static.

File: src/languages/sql.js (hunk 3 above)
Comment (egor-rogov) [reply src/languages/sql.js]: I rather try to reason. Sure you can leave it, but be ready to answer questions...

**Comment by joshgoebel** [comment]
> Having vendor-specific keywords/types/etc does not encourage 3rd party grammars. It encourages complaints on poor support of XXX database.

I wasn't making an argument to go backwards, just saying that just having the keywords wasn't the _biggest_ problem with SQL...  I also think it can be BOTH.  Just having a slightly enhanced list of types makes SQL super useful for CREATE TABLE style snippets for example.  But if someone is writing super complex queries then yes, they will always be better served by a more specific grammar.

Like almost everything in life I don't think this is black and white.

File: src/languages/sql.js (hunk 3 above)
Comment (joshgoebel) [reply src/languages/sql.js]: I removed it.  Less is more.  If someone argues for its' inclusing in the future then we'll have more information at that time and can revisit.

File: src/languages/sql.js (hunk 6 above)
Comment (joshgoebel) [reply src/languages/sql.js:42]: _We need still to match to avoid false positives on keywords._

Comment (egor-rogov) [reply src/languages/sql.js:42]: Yes, you're right of course.

File: src/languages/sql.js [hunk 7]
```diff
@@ -1,168 +1,672 @@
...
+    "system_time",
+    "system_user",
+    "current_time",
+    "localtime",
+    "current_timestamp",
+    "localtimestamp"
+  ];
+
+  // those exist to boost relevance making these very
+  // "SQL like" keyword combos worth +1 extra relevance
```
Comment (egor-rogov) [inline src/languages/sql.js:576]: Right, but there is another obvious purpose: to add context for some non-reserved keywords. Like `key` in `primary key` is a keyword, although you can e. g. `create table key(...)`.
Probably it's worth mentioning.

Comment (egor-rogov) [reply src/languages/sql.js:576]: Oops. It doesn't work that way, but it should.

**Comment by egor-rogov** [comment]
I've made some kinda real-life tests. Generally everything looks decent.

Some more tweaks:
1. Add `count` and `lead` to `RESERVED_FUNCTIONS`.
4. Both words from combos must be highlighted as keywords.
2. I'd add `desc`, `asc`, and `view` to `NON_RESERVED_WORDS`.
3. I'd remove `null` from `LITERALS` (it's in `RESERVED_WORDS`). Not sure it's correct to call NULL literal, and clauses like `IS [NOT] NULL` look strange that way.

File: src/languages/sql.js (hunk 7 above)
Comment (joshgoebel) [reply src/languages/sql.js:576]: > although you can e. g. create table key(...).

Which is why key is also still a keyword (or should be).

> Oops. It doesn't work that way, but it should.

What?

**Comment by joshgoebel** [comment]
> Both words from combos must be highlighted as keywords.

Are we just simply missing some words from `keywords` you mean?

**Comment by joshgoebel** [comment]
Done and done.  Anything else? :)

File: src/languages/sql.js (hunk 7 above)
Comment (egor-rogov) [reply src/languages/sql.js:582]: I think you got it right.
"Combos" is a great way to bind non-reserved keywords to the context in which they must appear as keywords. It's very strightforward and can reduce false positives to 0 - if only you can isolate all the suitable contexts.
It is easy for e. g. `key`, but you can't do it for, say, `asc` or `desc`. That's why we always treat them as keywords, even though it can lead to mistakes. Hopefully no one will name tables or columns like `asc`.

**Review by egor-rogov — APPROVED** [review]
Looks like it is in a good shape for v1, LGTM!
I'll update `pgsql` to make its style closer to this.

File: src/languages/sql.js (hunk 7 above)
Comment (joshgoebel) [reply src/languages/sql.js:582]: Problem for another day. :)

Comment (yakov116) [reply src/languages/sql.js:582]: I have a column called `desc` but yeah it comes to byte me in others ways.

Side note this PR looks awesome!

Comment (joshgoebel) [reply src/languages/sql.js:582]: You can always quote it in SQL snippets you highlight.
