### PR TITLE
fix(kotlin) class false positives

### LINKED ISSUE #3557: (Kotlin) Short description of issue...
**1. Which language seems to have the issue?** 

- Kotlin

<br>

**2. Describe the issue**

[Actual Preview in VSCode]
image

[What I've expected]
image

<br>

**3. Are you using `highlight` or `highlightAuto`?**
- I'm not sure but this issue occurs in Visual Studio Code markdown preview.

<br>

**4. Sample Code to Reproduce**

````
```kotlin
object Validators {
  private val valiators = mutableMapOf<KClass<*>, FieldValidator<*>>()

  fun <T: Any> registerValidator(kClass: KClass<T>, fieldValidator: FieldValidator<T>) {
    validators[kClass] = fieldValidator
  }
}

Validators.registerValidator(String::class, DefaultStringValidator)
Validators.registerValidator(Int::class, DefaultIntValidator)
```
````

### LINKED ISSUE #3567: (Kotlin) Bracket highlighted with different color in class inheritance context.
**Describe the issue**

- Bracket highlighted with different color in class inheritance context.
- I found this issue in VSCode markdown preview, and reproduced it in JSFiddle.

<br>

**Which language seems to have the issue?** 

- Kotlin

<br>

**Sample Code to Reproduce**

````
```kotlin
open class Tag

class TABLE: Tag {
  fun tr(init: TR.() -> Unit)
}

class TR: Tag {
  fun td(init: TD.() -> Unit)
}

class TD: Tag
```
````

- Reproduced in JSFiddle  https://jsfiddle.net/kkangmj/e7h48w36/7/

<br>

**Expected behavior**

- Bracket highlighted with same color.

<br>

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolve #3557. Resolve #3567.

### Changes

Makes the class detection a bit more robust not leading to false positives that break things.

### Checklist
- [x] Added markup tests, or they don't apply here because simple change, i'm in a rush.
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/kotlin.js [hunk 1]
```diff
@@ -222,7 +229,7 @@ export default function(hljs) {
           {
             className: 'type',
             begin: /[,:]\s*/,
-            end: /[<\(,]|$/,
+            end: /[<\(,)]|$/,
```
Comment (allejo) [inline src/languages/kotlin.js:232]:
```suggestion
            end: /[<\(,)\s]|$/,
```

Since you're touching this to improve class detection, here's a minor finding. Not sure if this is the best way to fix it though.

Given the example code,

```kotlin
class MyView : View {
    constructor(ctx: Context) : super(ctx)
    constructor(ctx: Context, attrs: AttributeSet) : super(ctx, attrs)
}
```

I get this, (notice the `View {` being highlighted together)

image

When it should be this,

image

**Review by allejo — APPROVED** [review]
Other than the minor finding, lgtm :+1:
