### PR TITLE
(yaml) add support for timestamps

### LINKED ISSUE #2475: (yaml) add support for dates/timestamps
**Describe the issue**
Highlighting of YAML date/datetime objects is inconsistent.

Screen Shot 2020-03-30 at 12 31 59

Some things that are parsed by YAML as dates get highlighted partly as strings, some things that are parsed by YAML as strings get highlighted as dates (or maybe numbers).

**Which language seems to have the issue?**
yaml

**Are you using `highlight` or `highlightAuto`?**
`initHighlightingOnLoad` with a language classname (see codepen below).

**Sample Code to Reproduce**
https://codepen.io/tamlyn/pen/mdJvMYv

**Expected behavior**
I expect the highlighting to be consistent with YAML's complex datatype parsing. But given the highlighting rules are based on regexes, maybe I expect too much.

### PR DESCRIPTION
**Pull request by pplantinga**
Add support for timestamps to YAML. Closes #2475.

### CODE REVIEW

File: src/languages/yaml.js [hunk 1]
```diff
@@ -44,6 +44,15 @@ export default function(hljs) {
     ]
   };
 
+  var DATE_RE = '[0-9]{4}(-[0-9][0-9]){0,2}';
+  var TIME_RE = '([Tt \\t][0-9][0-9]?(:[0-9][0-9]){2})?';
+  var FRAC_RE = '(\\.[0-9]*)?';
```
Comment (yyyc514) [inline src/languages/yaml.js:49]: Please no abbreviations.

File: src/languages/yaml.js [hunk 2]
```diff
@@ -44,6 +44,15 @@ export default function(hljs) {
...
+  var ZONE_RE = '([ \\t])*(Z|[-+][0-9][0-9]?(:[0-9][0-9])?)?';
+  var TIMESTAMP = {
+    className: 'number',
+    begin: DATE_RE + TIME_RE + FRAC_RE + ZONE_RE + '\\b',
```
Comment (yyyc514) [inline src/languages/yaml.js:53]: Why only a boundary at the end and not the beginning?

**Comment by yyyc514** [comment]
Only those two notes, otherwise this looks great.  Told ya it'd be easier. :)
