### PR TITLE
(dart) highlight built-in nullable types

### LINKED ISSUE #2550: (Dart) Support Dart's new Null Safety type system
**Describe the issue**

Dart's new [Null Safety language feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) introduces some new keywords and a new way to specify types:

* `late` and `required` are new keywords
* `Never` is a new type found in `dart:core`
* (almost) all types can be suffixed with a `?` to indicate a nullable type. For example, in:

  ```dart
  f(int x) { ... }
  g(int? x) { ... }
  ```

  `f` is a function which accepts a non-null `int` parameter, and `g` accepts a nullable `int` parameter.

**Which language seems to have the issue?**

Dart.

**Are you using `highlight` or `highlightAuto`?**

Either.

**Sample Code to Reproduce**

```dart
late int x;
f({required int? y}) {}
const List<Never> z = [];
```

**Expected behavior**

`late` and `required` should be highlighted as keywords. `int?` should highlight the same as `int`. `Never` should be highlighted like the other built-in types.

**Additional context**

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #2550 

This change separates the "built-ins" into those which can be marked nullable (like `int` and `String`) and those which cannot (like `dynamic` and `window`). Nullable built-in types like `int?` are highlighted as such.

### CODE REVIEW

File: src/languages/dart.js [hunk 1]
```diff
@@ -72,17 +72,28 @@ export default function(hljs) {
     hljs.C_NUMBER_MODE, STRING
   ];
 
+  var BUILT_IN_TYPES =
```
Comment (yyyc514) [inline src/languages/dart.js:75]: Please just go ahead and explode this into an array with one item per line.  We need to start doing this anyways and it will clean up the logic below.

File: src/languages/dart.js [hunk 2]
```diff
@@ -72,17 +72,28 @@ export default function(hljs) {
...
   var KEYWORDS = {
     keyword: 'abstract as assert async await break case catch class const continue covariant default deferred do ' +
       'dynamic else enum export extends extension external factory false final finally for Function get hide if ' +
       'implements import in inferface is late library mixin new null on operator part required rethrow return set ' +
       'show static super switch sync this throw true try typedef var void while with yield',
     built_in:
+      // non-nullable built-in types
+      BUILT_IN_TYPES + ' ' +
+      // nullable built-in types
+      BUILT_IN_TYPES.split(' ').map((e) => { e + '?' }).join(' ') + ' ' +
```
Comment (yyyc514) [inline src/languages/dart.js:91]: Use template literal?

File: src/languages/dart.js (hunk 1 above)
Comment (srawlins) [reply src/languages/dart.js]: Done

File: src/languages/dart.js (hunk 2 above)
Comment (srawlins) [reply src/languages/dart.js]: Done

**Comment by yyyc514** [comment]
@srawlins Does this still look good to you?

**Comment by srawlins** [comment]
Looks great, thanks!

**Comment by yyyc514** [comment]
Can you add a changes.md entry, please?

**Comment by srawlins** [comment]
I just edited the existing line, is that good?

**Comment by yyyc514** [comment]
Good enough.

File: src/languages/dart.js [hunk 3]
```diff
@@ -72,17 +72,59 @@ export default function(hljs) {
...
+    'ElementList',
+  ];
+  const NULLABLE_BUILT_IN_TYPES = BUILT_IN_TYPES.map((e) => `${e}?`);
+
+  const KEYWORDS = {
     keyword: 'abstract as assert async await break case catch class const continue covariant default deferred do ' +
       'dynamic else enum export extends extension external factory false final finally for Function get hide if ' +
       'implements import in inferface is late library mixin new null on operator part required rethrow return set ' +
-      'show static super switch sync this throw true try typedef var void while with yield',
+      'show static super switch sync this throw true try typedef const void while with yield',
```
Comment (yyyc514) [inline src/languages/dart.js:111]:
```suggestion
      'show static super switch sync this throw true try typedef var void while with yield',
```

Comment (yyyc514) [reply src/languages/dart.js:111]: Fixing this back.

**Comment by yyyc514** [comment]
@srawlins Thanks for putting in the time!
