### PR TITLE
fix(verilog) Fix directive handling

### LINKED ISSUE #3283: (Verilog) Incorrect `meta` scope
**Describe the issue**
In Verilog, from backquotes (`` ` ``) to end-of-line are treated as `meta` scope, which is not correct.

**Which language seems to have the issue?**
highlight.js: `11.1.0`
Language: `verilog`
Theme: `github`

**Are you using `highlight` or `highlightAuto`?**
Both.

**Sample Code to Reproduce**
For example, comments following `` `define`` are not highlighted correctly.
Also, Verilog requires a backquote (`` ` ``) when using defined values, so the text following it is not highlighted correctly.

Code:
```verilog
`define CONSTANT value // this is a comment
wire result = `CONSTANT + variable; // comment
```
Screenshot:
image

**Expected behavior**
It should be highlighted like C.
image
(Of course, `#` is not necessary in C when using `CONSTANT`, I simply want to compare with Verilog).

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #3283

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

File: src/languages/verilog.js [hunk 1]
```diff
@@ -76,30 +499,30 @@ export default function(hljs) {
...
       hljs.C_LINE_COMMENT_MODE,
       hljs.QUOTE_STRING_MODE,
       {
-        className: 'number',
+        scope: 'number',
         contains: [ hljs.BACKSLASH_ESCAPE ],
         variants: [
           {
-            begin: '\\b((\\d+\'(b|h|o|d|B|H|O|D))[0-9xzXZa-fA-F_]+)'
+            begin: /\b((\d+'(b|h|o|d|B|H|O|D))[0-9xzXZa-fA-F_]+)/
```
Comment (allejo) [inline src/languages/verilog.js:512]:
```suggestion
            begin: /\b((\d+'([bhodBHOD]))[0-9xzXZa-fA-F_]+)/
```

Since we're touching this regex; might as well simplify it a tad

File: src/languages/verilog.js [hunk 2]
```diff
@@ -76,30 +499,30 @@ export default function(hljs) {
...
           },
           {
-            begin: '\\B((\'(b|h|o|d|B|H|O|D))[0-9xzXZa-fA-F_]+)'
+            begin: /\B(('(b|h|o|d|B|H|O|D))[0-9xzXZa-fA-F_]+)/
```
Comment (allejo) [inline src/languages/verilog.js:515]:
```suggestion
            begin: /\B(('([bhodBHOD]))[0-9xzXZa-fA-F_]+)/
```

File: src/languages/verilog.js [hunk 3]
```diff
@@ -6,67 +6,490 @@ Description: Verilog is a hardware description language used in electronic desig
...
+    "ifndef",
+    "include",
+    "line",
+    "nounconnected_drive",
+    "pragma",
+    "resetall",
+    "timescale",
+    "unconnected_drive",
+    "undef",
+    "undefineall"
```
Comment (allejo) [inline src/languages/verilog.js:491]:
```suggestion
    "begin_keywords",
    "celldefine",
    "default_nettype",
    "default_decay_time",
    "default_trireg_strength",
    "define",
    "delay_mode_distributed",
    "delay_mode_path",
    "delay_mode_unit",
    "delay_mode_zero",
    "else",
    "elsif",
    "end_keywords",
    "endcelldefine",
    "endif",
    "ifdef",
    "ifndef",
    "include",
    "line",
    "nounconnected_drive",
    "pragma",
    "resetall",
    "timescale",
    "unconnected_drive",
    "undef",
    "undefineall"
```

Added some missing directives according to [UMBC](https://www.csee.umbc.edu/portal/help/VHDL/verilog/compiler.html) and removed a duplicate.

**Review by allejo — APPROVED** [review]
LGTM 👍 Few minor suggestions
