### PR TITLE
enh(latex) complete ground up rewrite of the LaTeX grammar

### LINKED ISSUE #2708: (LaTeX) Backslashes should be highlighted as part of the control sequence
**Describe the issue**
In LaTeX, backslashes (`\`) are used to denote control sequences like macro names. highlight.js does not include the backslash into the resulting control sequence, i.e. the backslash in `\foo` does not receive the same markup as the `foo` does. This is confusing, because in the language, `\foo` is _one token_, the backslash is not a separate thing. The confusion gets especially bad with the macro `\\`, where highlight.js styles the second backslash differently from the first.

Here are some screenshots showing the issue on the [official demo][demo]:

demo-output

[demo]: https://highlightjs.org/static/demo/

**Sample Code to Reproduce**
Here's the code from the demo site:

```latex
\documentclass{article}
\usepackage[koi8-r]{inputenc}
\hoffset=0pt
\voffset=.3em
\tolerance=400
\newcommand{\eTiX}{\TeX}
\begin{document}
\section*{Highlight.js}
\begin{table}[c|c]
$\frac 12\, + \, \frac 1{x^3}\text{Hello \! world}$ & \textbf{Goodbye\~ world} \\\eTiX $ \pi=400 $
\end{table}
Ch\'erie, \c{c}a ne me pla\^\i t pas! % comment \b
G\"otterd\"ammerung~45\%=34.
$$
    \int\limits_{0}^{\pi}\frac{4}{x-7}=3
$$
\end{document}
```

**Expected behavior**
The whole token should be parsed together, i.e. including the leading backslash.

**Additional context**
highlight.js has recently been adopted by the Stack Exchange network. [TeX - LaTeX Stack Exchange][tex.se] has been _the_ place to get support around TeX and TeX-adjacent software. This design decision (I suppose the current behavior is by design) makes reading some of the answers there much harder and I believe the tex.sx community would be very thankful for a change.

[tex.se]: https://tex.stackexchange.com/

### LINKED ISSUE #2709: (LaTeX) There is no code highlighting inside braces (most of the time)
**Describe the issue**
It seems like braces in LaTeX are treated like string literals by highlight.js, i.e. their content is treated as one group that is highlighted uniformly, regardless of content. This is _not correct_! While braces are an important syntactical element in TeX, their content is normal TeX code, just like outside of braces. They can contain anything that is allowed in the language. Consequently, their content should be highlighted normally.

Since braces are such a frequent occurrence in TeX, this behavior can easily leave half the code that should be highlighted un-highlighted.

Here is a part of the [official demo][demo]. The macros `\eTiX` and `\TeX` in the first line as well as `\!` and `\~` in the last are not recognizable as such. As I said above, syntactically there is no need to treat the content of braces any different from normal code at all.

output

Here are some examples from [a tex.sx post][tex.sx-post]. Somehow, the behavior is not totally consistent here as some things in the braces are highlighted. It may have something to do with the fact that `\hbox` is a primitive command and may be treated as a "reserved word". However, the same should not be true about `\,`. Maybe it's just a bug in a bug.

tex.sx-output-1

tex.sx-output-2

[demo]: https://highlightjs.org/static/demo/
[tex.sx-post]: https://tex.stackexchange.com/a/22375/48973

**Sample Code to Reproduce**
The code from the demo page (with two more lines than the screenshot in order to complete the `table` and `document` environments):
```latex
\newcommand{\eTiX}{\TeX}
\begin{document}
\section*{Highlight.js}
\begin{table}[c|c]
$\frac 12\, + \, \frac 1{x^3}\text{Hello \! world}$ & \textbf{Goodbye\~ world} \\\eTiX $ \pi=400 $
\end{table}
\end{document}
```

The code from the tex.sx post:
```latex
\newcommand{\opncls}[2]{%
  \ooalign{$#1\subseteq$\cr
  \hidewidth\raisefix{#1}\hbox{$#1#2\mkern.5mu$}\cr}}
```
```latex
$
\mathcal{F}_x:=
  \frac{\bigsqcup\{\mathcal{F}(U);\, x\in U \opn X\}}
  {\exists x\in W \opn U\cap U'\!:s|_W=s'|_W}
$
```

**Expected behavior**
Parse code inside of braces the same as code outside them.

### PR DESCRIPTION
**Pull request by schtandard**
Resolves #2708. Resolves #2709.

---

This is a complete redo of the LaTeX language parser. It aims to solve #2708 and #2709 as well as some other problems not reported in the issue tracker but collected on [tex.sx][meta-question]. Since TeX is a macro expansion language, its syntax has some peculiarities compared to other programming languages that require special handling by a syntax highlighter. I will try to outline the main issues and my approach to tackling them here.

[meta-question]: https://tex.meta.stackexchange.com/q/8665/48973

## The Problem: Category Codes
Every character in a TeX program has a so-called category code (catcode for short). Characters with special catcodes like `%`, `{`, `}`, `#`, `&`, `$`, `^` or `_` can be recognized by a syntax parser easily enough. It gets a bit difficult when it comes to control sequences, though.

Recognizing control sequences (these are tokens representing macros or primitive commands) is the main task of any (La)TeX syntax highlighter. They consist of a backslash `\` followed by either an arbitrary number of letters or a single non-letter. If a character is a letter is decided by its catcode. Usually, letters are what one would expect: `a-zA-Z`. However, catcodes can differ between files and even change in the middle of a program. It is impossible to determine the correct catcodes of every character in a program without executing it (using TeX). However, there are two very common and standardized ways of changing which characters are considered letters:
1. The character `@` is usually not a letter, but is commonly made one in order to use it in internal macro names. This done using `\makeatletter`. `\makeatother` makes it a non-letter again. An example:
    ```latex
    \@gobble \foo@bar
    \makeatletter
      \@gobble \foo@bar
    \makeatother
    ```
    Assuming that the default LaTeX catcodes are in effect, the first line contains the control sequences `\@` and `\foo`. (The rest of the line consist of normal text.) After making `@` a letter, the third line contains the control sequences `\@gobble` and `\foo@bar`.
    (As you can see, the GitHub syntax highlighter always treats `@` as a letter, which is not always correct but a better choice than never treating it as one.

2. The long term future of LaTeX is called LaTeX3 (the current version is called LaTeX2e). It provides a collection of macros that greatly simplify writing TeX programs which is also known as `expl3` ("experimental LaTeX3"). In order to use this programming layer, one has to enter a category code regime where (among some other changes) `_` and `:` are letters. It is entered using `\ExplSyntaxOn` and left using `\ExplSyntaxOff`. An example:
    ```latex
    \tl_set_eq:NN \l_tmpa_tl \l_tmpb_tl
    \ExplSyntaxOn
      \tl_set_eq:NN \l_tmpa_tl \l_tmpb_tl
    \ExplSyntaxOff
    ```
    With the default LaTeX catcodes, the first line contains the control sequences `\tl`, `\l` and `\l`. It is also utter nonsense and would in fact cause an error when compiling (due to `_` being used outside math mode). After an `\ExplSyntaxOn` however, it consists of the control sequences `\tl_set_eq:NN`, `\l_tmpa_tl` and `\l_tmpb_tl`.
    (As you can see, the GitHub syntax highlighter does not know about this.)

    Importantly, while it is an okay choice to just always treat `@` as a letter when highlighting syntax, this is not true for `:` and `_`. Unlike `@`, these characters commonly occur in normal LaTeX code, often directly after control sequences.

Both of these cases (and in fact their combination) are already present in many LaTeX packages and online posts, where `\makeatletter` and `\ExplSyntaxOn` may not be present.

I write all of this to try and convince you of the following:
- `highlight.js` should support both the "normal" LaTeX and LaTeX3.
- In order to support LaTeX3, we need a separate language file `latex3.js` and we need to support switching to and from that language using `\ExplSyntaxOn` and `\ExplSyntaxOff`.
- If we are already at it, we can do the same for `\makeatletter` and `\makeatother`. Apart from providing correct highlighting, this would also help beginners finding code snippets online (for example on [tex.sx]) by correctly pointing out where control sequences end. (Not understanding `\makeatletter` and forgetting to use it are common problems among LaTeX newbies.)

[tex.sx]: https://tex.stackexchange.com/

### I decided the parser should be able to recognize the following elements:
- Control sequences (as described above)
- Macro parameters: These consist of one or more `#` usually followed by a digit.

  (Actually, the number of `#` should be `2^n` for some `n`, but the parser doesn't have to know this, in my opinion.)
- Comments: These start with `%` and contain the rest of the line.
- Characters with special catcodes (that have not yet been covered): Namely `{`, `}`, `$`, `&`, `^` and `_`.

### I decided not to include (for now):
- The `^^` syntax: A double `^` followed by any character should be recognized as a single character.
- Tagging the different elements of LaTeX macro names: The LaTeX3 programming layer follows a strict naming scheme. For example `\hljs_do_somehthing:Ncx` is a function in the module `hljs` with the name `do_something` and the signature `Ncx`, whereas `\l_hljs_some_value_tl` is a local (`l`) variable of the module `hljs` of type `tl` with the name `some_value`.

  I'm not sure if this should be inside or outside the scope of `highlight.js`.
- Units, stretch values and the like: These are impossible to differentiate from normal text and the value added by highlighting them is very limited.
- Math mode: The same is true. While it would be feasible to cover the most common macros that contain / switch to math mode, there will always be non-edge cases that are not recognized. It is clearer to not differentiate at all.

## How to parse control sequences
I settled on the following method for detecting control sequences and switching languages ("changing catcodes"):
- Upon finding a backslash `\`, enter the mode `control_sequence`.
  - Now, first check if the control sequence is one that indicates that this is in fact LaTeX (with special catcodes)
  - If so, give it a high relevance.
  - Otherwise, scan for any other control sequence and give it the relevance 0.
- After the control sequence is complete, check if it was one that changes catcodes.
  - If it was, switch to the corresponding language for the rest of the code.

## Which classes to use
In this first draft, I have not yet decided which [CSS classes][css-classes] to use for highlighting. Since LaTeX does not have the same syntax elements as most other languages, there is quite some room for interpretation here. I guess, one should survey the existing color schemes and select keywords that make LaTeX look "right" in most of those.

Any notes on this?

[css-classes]: https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html

## What I'm unclear on
As I am new to `highlight.js`, there are some things I am not totally clear on:
### Does the circular dependency of the languages work?
When I remove the `Requires:` line from the header of all four language files and compile them with
```shell
node ./tools/build.js -n latex latex@ latex3 latex3@
```
everything works fine.

Adding the `Requires:` line leads to an error as described in #2725.

However, when I try to compile everything
```shell
node ./tools/build.js
```
the script complains about a circular reference.

Are circular references not allowed at all? That would greatly complicate the task at hand, since LaTeX2e can occur inside LaTeX3 and vice versa.

### Could nesting the languages lead to problems?
In my current approach, the parser does not switch back from a sublanguage before the end of the code. After saying `\ExplSyntaxOn\ExplSyntaxOff`, there is a `latex` sublanguage inside a `latex3` sublanguage.

Avoiding this is not trivial, as `\ExplSyntaxOn\makeatletter\ExplsyntaxOff` is possible: `\ExplSyntaxOff` reverts the changes done by `\ExplSyntaxOn` but not those done by `\makeatletter`.

### Could we instead change the grammar dynamically?
Having an array containing all "letters" that is used when scanning for control sequences and that can be changed when one of the category code changing macros is found would be somewhat more natural. (I guess we would still need several languages for the state at the start of parsing to differ.) Is this possible?

### Is `@` in the language name legal?
The language names `latex` and `latex3` are fairly obvious. I decided to append an `@` to the name for those langauges where it is a letter. Is this safe or is that character not allowed in language names? (I did not experience any problems in my tests.)

### Can control sequences have a relevance of 1 (instead of 0)?
In the existing `latex.js` placeholder[*][stub-comment], control sequences were given a relevance of 0. I left it that way for now.

I would consider it more natural to give them a relevance of 1 in order to also support auto-detection in short code snippets that do not contain any of the more obvious macros that are given high relevance. This is not very pressing, though, I believe, since sites where LaTeX is to be expected can set it as the default language.

I guess the decision was made because the backslash can also appear in paths or as an escape character. I don't feel I have a good sense of how often other code snippets would be falsely identified as LaTeX if it got a relevance of 1 for every backslash.

### Should I worry about efficiency?
Every time a backslash is found, `latex.js` checks for 34 known control sequences for language detection. Is this a lot? Should this be reduced in order not to slow down the parser? I have no idea how fast this thing runs / should run.

----

I look forward to any feedback or advice!

[stub-comment]: https://github.com/highlightjs/highlight.js/issues/2709#issuecomment-699072143

### CODE REVIEW

**Comment by joshgoebel** [comment]
Let me try and take a quick very high level pass, and then I'll tackle the questions.  I'm not sure this first approach is what we'd want (too specific, too complex)... our goal is to highlight well "most of the time" not be an entirely accurate parser for complex languages (I'm starting to think LaTex might fall under this category).  I definitely do not think we want 4 variants and all this interconnectivity.  If that's truly the best way to go this might be better as a 3rd party module (where you're free to do things however you see fit).  But first lets tackle the questions and see if we can simplify all this.

First one high level question of my own:

- What are the real differences between Latex 2 and 3?  What is the harm in just assuming everything is version 3 and highlighting accordingly?

---

> Which classes to use... Any notes on this?

We need to try and map things semantically the best possible... that might mean `\\blah` becomes a `keyword`, etc... ie, map to the existing CSS classes.  You're welcome to look at the styles when doing this, but I still think it's best to try for the best semantic match vs visual matching.  It might be possible LaTex requires custom CSS to get the most benefit if it's so very different from most languages.   You're welcome to make a list of which classes are "missing" and we can add that to the larger discussion (same discussion it taking place with Mathematica).

I'm open to new classes in the future but the problem with adding new classes is we have 100+ themes that would then be "broken"... so we're stuck with the existing classes (or aliasing to them) for the most part until a great solution is found for this.  So short-term having a grammar that only works with one "blessed theme" is a no-no.  But always open to ideas here.

> Does the circular dependency of the languages work? When I remove the Requires: line from the header of all four language files and compile them with

**True dependencies cannot be circular.** Dependencies spell out "this language CANNOT load without this other language".  But "sublanguage" is not a hard dependency... if a sublanguage is not loaded, it is simply ignored and will not be highlighted... so you would see no errors until you tried to highlight and did not get the expected result.  Of course if you manually build ALL the variants then this would "just work".

> Are circular references not allowed at all?  That would greatly complicate the task at hand, since LaTeX2e can occur inside LaTeX3 and vice versa.

They are not, but again hopefully we can simplify all this.  But again if the dependencies are not "hard" then this may not be a HUGE issue... you just have to make sure someone always builds all the variants.

> Could nesting the languages lead to problems? In my current approach, the parser does not switch back from a sublanguage before the end of the code. After saying \ExplSyntaxOn\ExplSyntaxOff, there is a latex sublanguage inside a latex3 sublanguage.

I don't follow this... All tags should be properly closed... the very last that that should happen... But if a sublanguage is still running when the end of content is hit that it should process everything (I think) and then the final closing tags will be added to terminate any nested modes.

> Avoiding this is not trivial, as \ExplSyntaxOn\makeatletter\ExplsyntaxOff is possible: \ExplSyntaxOff reverts the changes done by \ExplSyntaxOn but not those done by \makeatletter.

I think you may be trying to make the grammar more complex than is possible/recommended.  Generally we're just a pattern highlighter... we do not make huge efforts to "understand" mode and "parse" the languages as you're trying to do here.

> Could we instead change the grammar dynamically? Having an array containing all "letters" that is used when scanning for control sequences and that can be changed when one of the category code changing macros is found would be somewhat more natural. (I guess we would still need several languages for the state at the start of parsing to differ.) Is this possible?

You only dynacism within the parser currently is our `on:begin` and `on:end` callbacks... they can dynamically choose to `skip` a match... so you could say match ALL identifiers (including "@") and then choose to "skip" matches that are found to have a "@" if you aren't in that "mode".  You may want to explore this.   Again I worry the complexity might be more than we want, but I'd have to see it in order to judge - and I think if it worked well it'd be preferable to this 4 variant version.

> Is @ in the language name legal? The language names latex and latex3 are fairly obvious. I decided to append an @ to the name for those langauges where it is a letter. Is this safe or is that character not allowed in language names? (I did not experience any problems in my tests.)

I think so, but again I'm not really comfortable with all these variants, so we need to try and figure something else out here.

> Can control sequences have a relevance of 1 (instead of 0)? In the existing latex.js placeholder*, control sequences were given a relevance of 0. I left it that way for now.

Not opposed. Most matches are allowed a relevance of 1.  It might be worth exploring why it was defaulted to 0 in the past... often this is done when there are a lot of other languages that do something similar (or it's a pattern that occurs often in the wild making it a poor "heiristic").

> sites where LaTeX is to be expected can set it as the default language.

Setting language manually always produces the best results.

> I guess the decision was made because the backslash can also appear in paths or as an escape character. 

Yeah, perhaps... often you can just test this (to some degree) by changing something and running the test suits and seeing if suddenly there are auto-detect problems with our own set of other languages and sample files..

> Should I worry about efficiency? Every time a backslash is found, latex.js checks for 34 known control sequences for language detection. Is this a lot? Should this be reduced in order not to slow down the parser? I have no idea how fast this thing runs / should run.

There is nothing wrong with a fairly large `|` regex expression, many of our grammars do that...

**Comment by joshgoebel** [comment]
So first... lets try and kill the @ and non-@ variants...  What is the harm in ALWAYS assuming @ COULD possibly be a character?  Shouldn't non-@ LaTex simply not use the @ in it's control sequences... making it a non-issue?  Ie, @ would be a superset of non-@?  Or am I missing something?

**Comment by joshgoebel** [comment]
> (As you can see, the GitHub syntax highlighter always treats @ as a letter, which is not always correct but a better choice than never treating it as one.

I'd suggest we simply do this, or *perhaps* play with a stateful toggle set in an `on:begin` rule... so you always match with @ but then depending on the mode you `skip` matches that don't match the mode.  You could try that and we could see what it looks like... the problem is we don't currently provide any way to "reset" state to a clean for subsequent highlighting so you could quickly get in a state where you have buggy/inconsistent behavior when highlighting multiple things.

That's probably something we could fix if we're going to encourage/allow this type of usage of rules (currently we don't and there is no precedent)... but I'm about to do something similar to support JSX in JS/TS... so this may be worth exploring.

```js
{
  begin: /(?<=\\makeatletter)/,
  end: /0^/,
  "on:begin": () => { at_mode = true }
}
```

**Comment by schtandard** [comment]
>  Ie, @ would be a superset of non-@? Or am I missing something?
A control word in TeX (i.e. a control sequence consisting of letters) is terminated by the first non-letter, regardless of what that is. That is, in the string `\foo@bar`, the `@` actually tells TeX that the control word is over, because it is not a letter. *Any* non-letter terminates the control word.

Is this a large issue? No. The `@` character does not occur regularly in most texts (which is what is typeset with LaTeX), so it is reasonable to just assume it is a letter. This could lead to wrong results when an email address is typeset like `\name@domain.com` (here the highlighter would highlight `\name@domain` as a control sequence even though only `\name` would be right), but that is very uncommon.

In short, always treating `@` as a letter is fine. This would bring the number of languages down to 2.

----

This does not work at all for `:` and `_`, though. Let's consider `_`: This character usually denotes a subscript in math mode. Code like
```latex
\theta_a + \xi_a = \int_\infty^0 \partial_x f(x, y) \mathrm{d} y
```
is very common. (Here, the underscores are not part of the macro names.)

However, in the LaTeX3 syntax, _every_ macro contains at least two underscores. These two contexts need different highlighting.

----

Having two different languages for LaTeX and LaTeX3 is not unreasonable, I'd say. While both run on TeX, they really are completely different languages, at least in terms of how they should be highlighted.

**Comment by schtandard** [comment]
Selecting classes semantically is a bit tricky, as most of the classes don't map nicely onto LaTeX. For example, a macro could both be a function (i.e. a macro containing code) or a variable (i.e. a macro containing data) and would look exactly the same. This is different in LaTeX3, though. I will think about this some more.

**Comment by joshgoebel** [comment]
I'm still a little hazy on Latex vs 3...

```
\theta_a + \xi_a = \int_\infty^0 \partial_x f(x, y) \mathrm{d} y
```

Is this supposed to be LaTex or LaTex 3?  Which mode is this in?  I kind of get the "could be an exponent" but is the `_` just silently dropped then and it's serving as a space?  

> Having two different languages for LaTeX and LaTeX3 is not unreasonable

I'm not 100% opposed here, but want to understand this thoroughly... how does the parser detect one from another?  Switching in an out inside a single file probably really isn't something we want to get into... ie this isn't something we'd want to handle with context and sublanguage... if we had two grammars then a file would either be "ALL latex" or "ALL latex3"... so we're not going to understand something like:

```
\tl_set_eq:NN \l_tmpa_tl \l_tmpb_tl
\ExplSyntaxOn
  \tl_set_eq:NN \l_tmpa_tl \l_tmpb_tl
\ExplSyntaxOff
```

We might see "\ExplSyntaxOn" (give it a high relevancy) and then decide that the file is "latex3" and the WHOLE file would be highlighted as such...

---

If you're willing to explore a bit more I wonder if this couldn't be solved with callbacks as I was suggesting for the `@` issue earlier?

**Comment by joshgoebel** [comment]
Is there such a think as "LaTex3" if said file does not include a \ExplSyntaxOn directive?

**Comment by schtandard** [comment]
> Is this supposed to be LaTex or LaTex 3?

Sorry for not being clear. This is LaTeX in math mode. (LaTeX is for typesetting documents and has two different modes: text mode and math mode. The typesetting rules are quite different in both, but not the language rules, i.e. a control sequences looks the same in either. A code highlighter does not need to know the difference.) Here, a `^` means what comes next is superscript and `_` means what comes next is subscript.

**Comment by joshgoebel** [comment]
```
            {
              begin: /(?<=\\ExplSyntaxOn)/,
              end: /0^/,
              subLanguage: 'latex3'
            }
```

What is `end` trying to match?

**Comment by schtandard** [comment]
> how does the parser detect one from another?

> Right now it seems you have "basic latex" until you hit the \ExplSyntaxOn directive then it's LaTex3, is that correct?

Exactly. In a complete document, the parser always starts in LaTeX2e mode and only switches over when it executes an `\ExplSyntaxOn`: The TeX engine does not load the entire file, parses it and the executes it. Instead, it only reads the first thing in the file, executes that (which may include a lot of steps of macro expansion) and only then moves on to the next thing. Crucially, the rules for how the parser should scan ahead for "the next thing" or what that thing means can be changed in the process (via catcodes). Keeping track of all the possible ways to do this is way outside the scope of any syntax highlighter. Switching over to LaTeX3 catcodes is rather common though (and will only become more common in the future) and profoundly changes the appearance of the code (which is what highlighters care about). This is why I believe this case should be supported.

I think it's getting a bit confusing to talk about LaTeX and LaTeX3 since the names are so similar. Let's instead call them typesetting mode and programming mode. Their use somewhat resembles the use of php in html. (Don't take this too literally, but only looking at the syntax it is close enough to true.)

Now, while the parser always starts out in typesetting mode when compiling a document, that does not mean that it is in typesetting mode at the start of every file. Files can `\input` other files, which means that the parser will read that file in whatever state it currently is. A file may be completely in programming mode, with no `\ExplSyntaxOn` present. This is even more true for code snippets online.

I think it would be doable to put both typesetting and programming mode in one file, but unless there is a way for the language to look at the whole file in order to decide in which mode to start, this won't work. Could users decide which mode to start in, like they can decide which language to use?

**Comment by schtandard** [comment]
> What is `end` trying to match?

It is trying to match the end of the file (which is why it has a regex that matches nothing). I did this in order to accommodate for arbitrary movement between the four sublanguages. If we kick two of them, this won't be necessary anymore (as the only place to go from the second language is back to the first).

**Comment by schtandard** [comment]
> Is there such a think as "LaTex3" if said file does not include a \ExplSyntaxOn directive?
Yes. The whole file might be LaTeX3.

**Comment by joshgoebel** [comment]
> Exactly. In a complete document, the parser always starts in LaTeX2e mode and only switches over when it executes an \ExplSyntaxOn: 

Perfect.  So I understand that correctly.

> Now, while the parser always starts out in typesetting mode when compiling a document, that does not mean that it is in typesetting mode at the start of every file. Files can \input other files ... [also] code snippets online.

> I think it would be doable to put both typesetting and programming mode in one file, but unless there is a way for the language to look at the whole file in order to decide in which mode to start, this won't work. ...

And now we have the crux of the problem. This is why we have `php` and `php-template` (xml with embedded PHP) though I HATE the necessity of it - and not sure we have the right tools to handle this sort of thing. :-)  One of our 3rd party grammar modules has a similar issue and solves it with two grammars (although they are both built from a single JS function)...

Can we make this a bit less abstract?  Can you pick a small (but telling) snippet of LaTex3 and highlight it with both "Latex" and "Latex3" (and show snaps) so I can visualize what differences we're talking about?  IE, how does "latex" misunderstand latex3?

**Comment by joshgoebel** [comment]
For auto-detect if a file does not include "\ExplSyntaxOn" isn deciding whether it's latex or latex3 a lost cause?  That's a consideration here also.. `php` and `php-template` work with auto-detect because XML is very different than PHP and can pick up a lot of relevancy from HTML content... So php-template will score much higher than php against a template..

**Comment by egor-rogov** [comment]
Why not treat any macro name with at least two underscores in it as LaTeX3? I believe it's a simple and satisfactory solution. In any case there is no 100% accurate way to handle switches between 2e/3 modes - we need a LaTeX interpreter for that (e. g. I can create my own macro to invoke `\ExplSyntaxOn` in it).

I'm +1 to always treats @ as a letter. It is simple and covers absolute majority of cases.

> Units, stretch values and the like: These are impossible to differentiate from normal text and the value added by highlighting them is very limited.

I think we'd better highlight them. I can hardly imagine normal text with, say, `3em` in it. Even so, it would make no harm to highlight it.

> Can control sequences have a relevance of 1 (instead of 0) ... to also support auto-detection in short code snippets

We can give high relevance to some widely used command like `\begin`, `\end`, `\item`, and so on. But it's a minor issue.

**Comment by schtandard** [comment]
> Can you pick a small (but telling) snippet of LaTex3 and highlight it with both "Latex" and "Latex3" (and show snaps) so I can visualize what differences we're talking about?

Sure. Here's a snippet of both with just the control sequences highlighted. (Of course, the LaTeX renderer would additionally misinterpret the underscores as math-subscripts if that were highlighted.) The first image is normal LaTeX highlighting, the second one is LaTeX3 highlighting.

latex-highlighting
latex3-highlighting

> For auto-detect if a file does not include "\ExplSyntaxOn" isn deciding whether it's latex or latex3 a lost cause?

No, we can still look for macro names that look like LaTeX3 (, which actually already worked pretty well in this draft.

**Comment by schtandard** [comment]
> Why not treat any macro name with at least two underscores in it as LaTeX3?

After reconsidering I discovered that my claim that all LaTeX3 macros have at least two underscores is simply wrong (the screenshots above show some examples). This is still feasible, however. In fact, I really like this idea.

We can look for macros that would adhere to the LaTeX3 naming convention if LaTeX3 catcodes were in effect. This is basically what I already did for language detection. If people don't follow the naming convention, this will of course fail, but that's fine I'd say.

**Comment by egor-rogov** [comment]
Pattern can be e. g. like this: "letters, followed by underscore, followed by at least two letters" (in LaTeX2e you'd write `\foo_{bar}`, not `\foo_bar` - although the latter is formally correct), or "letters and underscores, followed by colon, followed by one or more letter", or something like this.
So the idea is to put everything in one grammar. This should be much simpler.

**Comment by schtandard** [comment]
> I think we'd better highlight them. I can hardly imagine normal text with, say, 3em in it.

Hmm, that's true. I'm still not sure about this, though. For consistency I would want to highlight counter values as well. After all, assigning a value to a counter and assigning a value to a dimension are pretty similar. But I'd find highlighting numbers in the document text rather confusing as they're not different from other characters.

I guess I just don't see the value of highlighting dimensions: When they appear in an assignment, they are surrounded by other stuff that is highlighted, namely macros and braces, so they stand out anyway. From a language standpoint they are nothing special: They are not literals as in other languages, they are just characters. What makes them special is the context, which is highlighted.

---

Highlighting stretch values (i.e. `plus` and `minus`) is not feasible in any case, I think.

**Comment by schtandard** [comment]
> So the idea is to put everything in one grammar. This should be much simpler.

Agreed. I will commit some changes tomorrow.

**Comment by schtandard** [comment]
Ok, here's what I changed since yesterday:

### Make it one language
I followed igor-rogov's suggestion to try and just pattern-match LaTeX3 macros. Here's the rules I used:
- Anything that looks like
  `\` + maybe `__` + two or more `[a-zA-Z]` + `_` + two or more `[a-zA-Z_]` + `:` + any number of `[nNcVvoxefTFpwD]`
  is a LaTeX3 function.
- Anything that looks like
  `\` + `[lgc]` + one or two `_` + one or more `[a-zA-Z]` + `_` + one or more `[a-zA-Z_]`
  is a LaTeX3 variable.
- Anything that looks like
  `\` + `[qs]` + one or two `_` + two or more `[a-zA-Z_]`
  is a LaTeX3 quark or scan mark.

This covers most cases. Some are missed and have to be covered separately:
- The functions `\use:` and `\use_i:` with various signatures.
- The functions `\else:`, `\fi:` and `\or:`.
- The functions `\if:w`, `\cs:w` and `\exp:w`.
- The functions `\::N` and friends.
- The functions `\::o_unbraced` and friends.

For now I explicitly enumerated the letters that are legal in the function signatures (the part of the macro name after the colon `:`) in each case. I guess this could be replaced by `[a-zA-Z]` everywhere, which would continue working if the language introduces further argument types.

If a backslash `\` is not followed by any of these patterns, it is checked for the double caret syntax (see below) and finally for a LaTeX2e macro (which always succeeds).

### Is this safe (enough)?
I think this is a pretty good heuristic. The highest risk for mistakes I can see is with `\else:`, `\fi:` and `\or:` which may be confused with the corresponding LaTeX2e macros `\else`, `\fi` and `\or` followed by a colon `:`. This is, however, not a big issue, I think.

### The double caret syntax
I included the double caret syntax for inputting characters, but only for control symbols and outside of macros. This covers the vast majority of use cases. (They can also appear in control words, but that is not really relevant and very hard to implement.)

These characters do not receive any special highlighting right now. The mode just makes sure that they are not wrongly highlighted (which would always happen otherwise).

### Active characters
As far as I know, `~` is always active and `"` is either active or unused (except for hex input). I included a rule for highlighting them like control sequences.

### Magic comments
I added magic comments.

### CSS classes
I went ahead and picked some CSS classes. I tried to do it semantically, as far as that's possible with LaTeX. Here's what I came up with:
- `keyword` for control sequences and active characters.
- `params` for macro parameters.
- `built_in` for `{`, `}`, `$`, `&`, `^` and `_`
- `meta` for magic comments
- `comment` for comments (duh)

---

I also restructured the code into variables. Hope that makes it a bit easier to read.

**Comment by schtandard** [comment]
If that's okay so far from a technical point of view, I think the following has yet to be decided:
- Do we want to highlight dimensions?
- Do we want to highlight numbers?
  - What about the ```, `"` and `'` notations?
- Do we want to highlight verbatim text?

I think highlighting verbatim text is probably the most pressing of these. As always, we can't reach 100 % coverage, but the most common cases should be possible I think.

**Comment by schtandard** [comment]
Two technical questions regarding `highlight.js`:
1. Is it possible to assign different CSS class names to different regex capturing groups of the same match?
  That is, can I for example match a regex with three capturing groups and then tell `highlight.js` that I want the first group to be a `keyword`, the second to be a `function` and the third to be a `literal`?
2. Can I write a mode in the following way:
  - Match something as the starting indicator of the mode.
  - Highlight the rest of the line normally, as if nothing had happened.
  - At the start of the next line, _really_ start the mode (i.e. start highlighting with that mode) until the end of the mode is found.

**Comment by egor-rogov** [comment]
> Is this safe (enough)? I think this is a pretty good heuristic.

I think so. Heuristics look good and they can be easily changed if necessary.

What worries me is highlighting of characters like `{`, `}`, `$`, `&`, `^`, `_`. This is non consistent with other languages, in which we don't highlight parens and braces, and operators. For example, I think curly braces have somewhat comparable meaning in LaTeX and languages like C, Java, JS etc.

For the sake of discussion: what do you think of highlighting not `{` and `}`, but parameters of marcos? E. g. to highlight
```
\begin{document}
```
not as
```
<span class="hljs-keyword">\begin</span>
<span class="hljs-built_in">{</span>
document
<span class="hljs-built_in">}</span>
```
but as
```
<span class="hljs-keyword">\begin</span>
{
<span class="hljs-params">document</span>
}
```

**Comment by schtandard** [comment]
> What worries me is highlighting of characters like `{`, `}`, `$`, `&`, `^`, `_`. This is non consistent with other languages, in which we don't highlight parens and braces, and operators. For example, I think curly braces have somewhat comparable meaning in LaTeX and languages like C, Java, JS etc.

My thought here is that these are the (visible) characters with special catcodes, i.e. not `letter` or `other` (or `space` or `newline` if you consider those visible). `\`, `#`, `%` and the active characters complete that list, but those are handled separately.

These characters are not merely elements of a larger syntax like, say, the parentheses in a function definition in other languages. They carry meaning on their own.
- `{` and `}` delimit TeX groups. These are not only used for macro arguments. TeX groups are routinely used on their own to provide a local scope to everything in that group, similar to namespaces in other languages.
- `$` is the math shift. It completely changes the typesetting rules LaTeX adheres to.
- `&` is the alignment tab. It is used in tables and the like to denote the boundary between two columns.
- `^` and `_` are math super- and subscript.

Importantly, all of these characters are _never printed in the output document_ (in contrast to every other character). For me, that alone is enough reason to highlight them. It is a complete list of all the special characters in the language (under normal catcodes).

Even if we ignore this and focus just on the highlighted code, I would still want to highlight them (`^` and `_` not as much as the others, but I wouldn't take them out of the list): They are often surrounded by normal text (i.e. non-highlighted text) and should be made to stand out. An `a` after a `$` (or rather between two `$` means something different than an `a` before it (outside of them). The line
```
lorem ipsum dolor & sit & amet, consectetur adipisici elit, sed & eiusmod tempor \\
```
is not just a line of text, it is a sequence of tabular cells and the highlighting should emphasize that. (This is of course even more helpful when viewing code that is not formatted in a helpful way, like with missing spaces around the `&` and columns not aligned in the source.)

> For the sake of discussion: what do you think of highlighting not `{` and `}`, but parameters of marcos?

I believe this to be impossible to do in a helpful way. In fact, this is one of the ways in which the current highlighting went wrong.

One problem is that braces to not always delimit macro arguments (as I mentioned before), even if they are placed directly behind a macro or it argument. They are routinely used for grouping, usually (but not always) placed at the start of a line. Macro arguments, however, are also routinely placed at the start of the next line in order to improve readability.

But let's say we can solve this problem and find a good heuristic to guess which braces are in fact macro arguments. How would one even highlight that? Anything can be in a macro arguments, all the elements of the language. And they can be arbitrarily nested. I don't see a way of highlighting this in a meaningful way. (The current implementation chose to not highlight code "in braces" at all, which is terrible.)

And then there's the problem of macro arguments that are not delimited by braces (they can be delimited by other characters or undelimited)...

In conclusion, I believe that highlighting the argument passed to a macro is a lost cause, both because we can't possibly recognize which part of the code belongs to the argument and because there is no feasible way of actually performing the highlighting.

**Comment by schtandard** [comment]
I added support for verbatim code. The details are in the regexes, but here's the general idea: At every step, the parser looks backwards and checks if it is at a point where verbatim text starts. If so, it scans ahead to the matching end and highlights everything in between as verbatim text.

`\mintinline` needs two rules because it accepts the verbatim text both delimited by two equal characters and by braces.

In order to prevent the macros from repeatedly triggering the rules, they cannot accept braces inside their argument. Since this expects a language which is usually give explicitly, this should be fine.

The other limitations to the syntax recognition line up pretty nicely with those of the syntax itself.

**Comment by schtandard** [comment]
I tried highlighting numbers and dimens in the branch [number_dimen], just to get a feel for it. I still don't like it. Apart from problems like this
image
image
(which we could probably reduce by supporting only a small subset of the syntax allowed in LaTeX), I find it really distracting in math mode
image
(Why should the `2`s be highlighted but the `k` not? Why should the `2`'s `-` be highlighted but the `k`'s not?) We could of course start highlighting all math operands (`+`, `-`, `*`, `/`, ...), but I don't think that is what we want. (It also comes with even more problems.)

Highlighting just dimens and not numbers is of course a bit simpler, but really inconsistent. Then, we would only highlight a very small percentage of the cases where a dimen is present in the code. (`1.5in` would highlighted, `1.5 in` would either not be highlighted or lead to the problem above, `.5\textwidth` would not be highlighted.)

I think it's much better to just leave it be and not highlight dimens and numbers at all.

[number_dimen]: https://github.com/schtandard/highlight.js/tree/number_dimen

**Comment by joshgoebel** [comment]
> Anything can be in a macro arguments, all the elements of the language. And they can be arbitrarily nested.

FYI: We support infinitely nested rules with "self". And manual multi-layer nesting is annoying but not impossible.

> In order to prevent the macros from repeatedly triggering the rules, they cannot accept braces inside their argument. Since this expects a language which is usually give explicitly, this should be fine.

Not sure I followed you here.

> What worries me is highlighting of characters like {, }, $, &, ^, _. This is non consistent with other languages, in which we don't highlight parens and braces, and operators. 

@egor-rogov This ship has sailed.  `operator` is open for usage now as part of the improved fidelity highlighting initiative. I'd like to encourage this highlighting going forward (when it's possible without much complexity).  There may still be issues here with grouping and consistency, but with regard to "we didn't used to highlight such things" that's no longer a blocker. Although perhaps these aren't strictly operators, but that's a whole other discussion. :)  Operator might still be the best class for them for the short-term.

**Comment by joshgoebel** [comment]
> Why should the 2s be highlighted but the k not? Why should the 2's - be highlighted but the k's not?

It should not be, traditionally we do not highlight unary operators because it's impossible to do so correctly without a full parser since you can't handle simple things like "2-3" easily...  _So only the number itself would be highlighted._

**Comment by joshgoebel** [comment]
> I added support for verbatim code. The details are in the regexes, but here's the general idea: At every step, the parser looks backwards and checks if it is at a point where verbatim text starts.

We cannot use look behind until some period AFTER it is supported by all major browsers, and that's still not the case.  So no look behind, sorry.

**Comment by joshgoebel** [comment]
> { and } delimit TeX groups. ... $ is the math shift. ... & is the alignment tab. ... ^ and _ are math super- and subscript.

I read this list and to me these still sound like `operators`, not `built-ins`.  With `{}` perhaps being in a weird case, we're having a similar discussion over in mathematic about what "brackets" should be...

**Comment by joshgoebel** [comment]
I just disabled the verbatim rule and took and look at how this looks with the default.txt and it looks WAY better than before already...

**Comment by joshgoebel** [comment]
Almost all the relevance 10s should be removed except for `MAGIC_COMMENT`... additional relevance shouldn't be added offensively, only defensively. It's possible many existing grammars do this poorly, so don't look there for inspiration.   Relevance 10 really says "this could be NOTHING except latex, i SWEAR on my life"... :-)

**Comment by egor-rogov** [comment]
> This ship has sailed. operator is open for usage now as part of the improved fidelity highlighting initiative.

Oh. Okay then.
Still, highlighting these single-character "operators" doesn't make a lot of sense to me. `{` and `}` differ from other text by themselves, so pouring some color in them doesn't make them much more different.
That is, okay, let's do it, but imho it wouldn't be very helpful.

And don't we want to also highlight `[` and `]` then?

> >  For the sake of discussion: what do you think of highlighting not { and }, but parameters of marcos?
>
> I believe this to be impossible to do in a helpful way. In fact, this is one of the ways in which the current highlighting went wrong.

No doubt, the current grammar does it wrong way, because it doesn't respect nesting and doesn't highlight inner elements. I think we can do it meaningfully, covering widely-used cases like `\begin{section}` and not ruining highlighting for other cases.
But I agree with Josh: let's first come to something mergeable and then we can return back to it.

> $ is the math shift. It completely changes the typesetting rules LaTeX adheres to.

Why not retain current `formula` class for the formulas? What's wrong with it? I can imagine CSS design that highlights formulas by slightly changed background color, for example.

**Comment by egor-rogov** [comment]
> Almost all the relevance 10s should be removed except for MAGIC_COMMENT

@joshgoebel In what language you can see e.g. `\makeatletter`? I swear on my life it is LaTeX (:
Most of KNOWS_CS are also good relevance boosters in addition to MAGIC_COMMENT.

**Comment by joshgoebel** [comment]
> good relevance boosters

Which is why they get 1 be default. 😊

Perhaps \makeatehatever could be higher but every single one of the CS rules, no. 

You're also forgetting about latex embedded in other documents like markdown￼ or HTML. A grammars relevancy should not be high enough that it completely overwhelms a markup language that it might be embedded inside of￼.

Latex is already going to get plenty high enough relevancy just because of all the control sequences individually getting relevance. ￼

**Comment by joshgoebel** [comment]
> { and } differ from other text by themselves, so pouring some color in them doesn't make them much more different.

Is your primary concern the brackets?￼

> And don't we want to also highlight [ and ] then?

Good question.

**Comment by schtandard** [comment]
> We cannot use look behind until some period AFTER it is supported by all major browsers, and that's still not the case. So no look behind, sorry.

Dammit, ok. In that case, will need a couple more modes..

> > In order to prevent the macros from repeatedly triggering the rules, they cannot accept braces inside their argument. Since this expects a language which is usually give explicitly, this should be fine.
> 
> Not sure I followed you here.

What I meant was that for example `\mintinline` has the syntax `\mintinline{language}{verbatim code}`, where the `verbatim code` is not LaTeX code. In order to match this with just a regex (which can't detect balanced braces), I had do exclude braces from the `language` part.

Not doing so would lead to `\mintinline{language}{verbatim code}{something else}`highlighting both `verbatim code` and `something else` as a string, because `language}{verbatim code` could be mistaken as a match for `language`.

As lookbehind is not an option, this may not be an issue, though. (That is, I will have to take a different approach anyways.)

**Comment by schtandard** [comment]
> Perhaps \makeatehatever could be higher but every single one of the CS rules, no.

No objection here. Just want to point out that this is a _very_ small sample of all of the control sequences in LaTeX. ;-)

**Comment by joshgoebel** [comment]
> No objection here. Just want to point out that this is a very small sample of all of the control sequences in LaTeX. ;-)

I know.  It could also be that the beginning of the control sequence itself plus a look ahead to make sure it’s followed by an identifier might deserve some relevancy instead of zero.

> So everything that has 10 now should have 1 (so no explicit relevance) except magic comments, right?

Yes I think so.

**Comment by schtandard** [comment]
> And don't we want to also highlight `[` and `]` then?

Because those are just normal characters. If you type `[hello]` in a LaTeX document, you will find "[hello]" in the output. If you type `{hello}`, you will only find "hello". They are also very common characters, especially in math but also in text. (And highlighting brackets but not parentheses would be very weird.)

It is true that they are also used to delimit optional arguments, but that is not a feature of TeX itself but instead of the programming of the macros that take them. Again, it is impossible to know which brackets are "optional arguments" and which aren't without running TeX. I can't see a good way of highlighting only some brackets either, as optional arguments commonly appear both in text and math mode and the syntaxes of macros that take them vary greatly.

> Why not retain current `formula` class for the formulas? What's wrong with it? I can imagine CSS design that highlights formulas by slightly changed background color, for example.

Because, again, it is impossible to tell where in the code math mode begins and ends without running TeX. One could of course cover the most common cases, like I tried for verbatim code, just with a lot more common cases (the TeX math toggles, the LaTeX math toggles, all of the `amsmath` environments and `\ensuremath` for starters). One would then have to also cover the common ways to temporarily leave math mode (like `\text` and `\intertext`). It is a lot of work!

Additionally, many documents define custom macros that can only be used in math mode (using other macros only found in math mode), but the definition itself is never in math mode (well, it shouldn't be). That is, not everything that will be executed in math mode also first appears in math mode in the document.

In contrast to verbatim text, however, it is not a big problem to just not detect math mode at all. Category codes don't change (well, there's `'` which is active in math mode but not in text mode, but that is neglectable), so all the other highlighting rules still work fine in math mode.

**Comment by schtandard** [comment]
> It could also be that the beginning of the control sequence itself plus a look ahead to make sure it’s followed by an identifier might deserve some relevancy instead of zero.

Yes, I think we should do that. Otherwise we'd have to add a lot more known macros in order to get something in most snippets. (For example, I get a relevance of 0 for my earlier test snippet
```latex
\( - \sum_{k = 0}^\infty 2^{-k} = -2 \)
1 in 5 people expects a joke here.
\( 1 + 2 - 3 + a - 5 - b \)
```
even though it is clearly LaTeX.)

So that would mean giving every control sequence a relevance of 1 and every one that indicates LaTeX more specifically (known explicitly or matches LaTeX3 conventions) an additional one. Is that okay?

**Comment by egor-rogov** [comment]
Well, my concern is that LaTeX simply doesn't have enough structural elements to make helpful highlighting. No keywords, no built-ins, basically only macros.
That's why I think that we should identify as many meaningful elements as possible. Parameters of macros, formulas etc.

>> And don't we want to also highlight [ and ] then?
>
> Because those are just normal characters.

For me it is weird to highlight `{` and `}`, but not `[` and `]`, in cases like `\usepackage[T2A]{fontenc}`.
Can we treat any number of `{...}` and `[...]`, immediately following macro, as its parameters? Does it not cover vast majority of cases? What harm can be?

**Comment by schtandard** [comment]
> `1.5 in` and `.5\knownidentifer` could pretty easily be detected/matched, no (if we wanted to)?... is the variety here just endless? What am I missing here? How many different ways are there to include dimensions?

The variety is not endless, but TeX accepts a pretty wide range of input. Some (more or less extreme) examples:
```latex
\@tempdima 12em                   % sets \@tempdima to 12 em
\@tempdima +-- -  + -   12   em   % does the same thing
\@tempdima = 12 emphasized        % does the same thing and prints "phasized"
\@tempdima 1\foo 2 em             % depending on \foo, may do the same or not
\@tempdima 2\foo                  % \foo needs to be a dimension for this to be legal
\@tempcnta 2\foo                  % always legal, \foo may be part of the number or not
\foo{12em}                        % depending on \foo, "12em" may be a dimen or not
```
It is noteworthy that, to TeX, the `+` and `-` in the second line are _not_ operators but part of the number. (Okay, one might argue they are unary operators..) In that example, no calculations are permitted. For example `\@tempdima 9 + 3 em` or `\@tempdima 9 em + 3 em` would not be legal.

It is of course reasonable to decide only to support the most common occurances of dimensions. Those are
```latex
\macro - 123.456 unit
\macro {...} [...] { - 123.456 unit } {...}
\macro - 123.456 unit operator - 123.456 unit
\macro {...} [...] { - 123.456 unit operator - 123.456 unit } {...}
```
where every space stands for zero or more possible spaces (0 and 1 are common), the `-` may be missing or a `+`, the decimals before or after the decimal point or both may be missing, the decimal point may be a `,`, there may be an integer instead of a decimal number and the other macro parameters may be missing or different. Oh, and any dimen may instead be a number (integer or not) followed by a control sequence.

That is to say, even if we focus on the common occurences, we really can't use context to determine where we can expect a dimen. (The same is true for numbers.)

Just pattern matching numbers and legal units leads to the problems shown [above](https://github.com/highlightjs/highlight.js/pull/2726#issuecomment-703270198). One may argue that this is acceptable, but I think it would be an unnecessary misfeature.

**Comment by schtandard** [comment]
> That's why I think that we should identify as many meaningful elements as possible. Parameters of macros, formulas etc.

I guess I just don't see the need. I think a LaTeX highlighter's main task should be highlighting control sequences and comments correctly (which does include trying to recognize verbatim code). Everything else is secondary.

However, I do feel that highlighting the other special characters nicely brings out the actual structure of the language. It is true that there are some conventions including other characters (most notably `[`, `]` and `*`, but parentheses `()` and angle brackets `<>` are also common in some contexts), but that is not universal. In a user document treating all brace- and bracket-groups directly following a macro may be correct most of the time (excluding math, there it may actually be wrong quite often), but not when highlighting a package file or many code snippets on help sites online. The highlighter stumbling over unmatched brackets would be quite annoying.

I actually think that not highlighting `[`, `]` and `*` is helpful for beginners. Not understanding that optional arguments behave differently because they are "faked" using programming or that a macro may not absorb a following brace group (or absorb something that is not braced) even though it looks like an argument are common difficulties for people who are new to LaTeX. They assume a similar grammar as in other programming languages, where, say, providing the wrong number of arguments to a function will lead to an error before execution even begins, because it is apparent from the syntax that they made a mistake, whereas TeX will just grab what's there regardless of if it was intended as an argument or not. The highlighter not reinforcing these misconceptions would be a feature in my view.

---

I should maybe clarify that I am not dead-set on highlighting braces. I would say the following about the characters in that rule:
- Highlighting `$` and `&` is very helpful. We should definitely do so.
- Highlighting `^` and `_` is somewhat helpful. I'd say we should also do so.
- Highlighting `{` and `}` is optional, but they do belong in the same list from a language standpoint.
I just think it would be an easy and consistent rule to say "We highlight every character that has a special catcode (i.e. characters that are not output to the document).

If you could clarify a bit why highlighting `{` and `}` is not good (apart from "We don't do it in other languages."; LaTeX is _very_ different from those languages), I'd be happy to give that up.

I could also ask some other members of the LaTeX community and the LaTeX3 team to weigh in on this (and on the rest of the highlighting). I was planning to do so at some point, anyway. It is possible, after all, that most people do think differently about this than I do.

**Comment by joshgoebel** [comment]
> Because, again, it is impossible to tell where in the code math mode begins and ends without running TeX. One could of course cover the most common cases, like I tried for verbatim code, just with a lot more common cases (the TeX math toggles, the LaTeX math toggles, all of the amsmath environments and \ensuremath for starters). One would then have to also cover the common ways to temporarily leave math mode (like \text and \intertext). It is a lot of work!

So you're saying the `$` and `$$` rule in the current grammar is woefully broken/inadequate then because all sorts of stuff can appear between the $$ to change the mode?

**Comment by joshgoebel** [comment]
It's worth noting our original unit rule was scoped to "variable like" statements:

```
\hoffset=0pt
\voffset=.3em
\tolerance=400
```

Is highlighting numbers/units only after `=` problematic?  Is this a common pattern to set variables? (I'm not sure what I'm looking at)

**Comment by joshgoebel** [comment]
> but TeX accepts a pretty wide range of input. 

I'm not sure we care that EVERY possible case is handled IF say 90%+ of the time the common cases would still be highlighted... If we *knew for sure* something was a dimension there could still be value in highlighting it as such.

**Comment by joshgoebel** [comment]
@schtandard Could you please work up some simple aliases (or just names) for the CSS... even if we have no way to encode them yet... if  nothing else we'll add this to the grammar as a comment...  (you could add to the original PR message)

IE:

```
control sequence => "keyword"
bracket (what do you call them) => "operator"
& (does it have a special name?) => "operator"
```

You've probably already named these things in the long dialog above but it'd be nice to get them all in a single place.

**Comment by joshgoebel** [comment]
@egor-rogov On a side note this is why I wonder if we wouldn't be better served by some languages spinning off into 3rd party modules... letting the LaTex community (who would maintain the 3rd party module) decide what is best rather than us trying to guess when we know little about LaTex or how it's ultimately used... 

I think sometimes being "man in the middle" really adds a lot of value but in some cases I really start to feel perhaps it gets in the way... yet as core we can't just let grammar writers run amok... We have to constantly be thinking about themes, the bigger picture, consistency, etc...  So we end up with cases (Mathematica might be another example) where the end result is a WORSE grammar overall (for the Mathematica community), yes one that fits better inside core... rather than a better, more fully featured grammar that isn't maintained by core.  Just some thoughts.

It makes me glad we currently only have to deal with this when a "rewrite" happens...

**Comment by joshgoebel** [comment]
Also I think it's always worth looking at what Prism is doing as a "peer": https://github.com/PrismJS/prism/blob/master/components/prism-latex.js

Seems they handle:

- comments
- verbatim
- urls (we have CSS for `links`)
- equations (`$`, `$$`, `\(`, `\[`) and some common begin matches for equations
 - `\\begin\{((?:equation|math|eqnarray|align|multline|gather)`
- sections/chapter headlines (we do have CSS for this)
- keywords (`begin|end|ref|cite|label|usepackage|documentclass` it calls these keywords)

**Comment by joshgoebel** [comment]
I'd suggest:

- Fix the look-behinds to look forwards...
- Fix relevancy.
- I'd really like to try and add the equation `$`, `$$`  stuff back...
- Forget about units unless there is a very common pattern we could match (like assignment after `=`, etc).  Prism does nothing here so I'm not sure it's a huge deal... (if it's trivial then it should be easy enough to add again later)

Then we might have a minimal mergeable PR I think...  And we should some more LaTex peoples thoughts on `[` vs `{`. Prism highlights both.

I would be curious to hear your thoughts on highlighting more "markup" stuff like sections/headers/urls, etc.. Since those seem to be commonly encoded in LaTex and would be easy enough to match.

**Comment by egor-rogov** [comment]
> On a side note this is why I wonder if we wouldn't be better served by some languages spinning off into 3rd party modules...

Yeah, same thoughts.
3rd party module is always an option, I'm not against another alternative implementation. But I really hope we can get to a useful in-core implementation.

> I'd suggest:
>
>    Fix the look-behinds to look forwards...
>    Fix relevancy.
>    I'd really like to try and add the equation $, $$ stuff back...

+1 to every point to get to a mergeable PR.

> I actually think that not highlighting [, ] and * is helpful for beginners. Not understanding that optional arguments behave differently because they are "faked" using programming or that a macro may not absorb a following brace group (or absorb something that is not braced) even though it looks like an argument are common difficulties for people who are new to LaTeX.

Here my opinion is opposite. Highlighting is not meant to help people understand basic concepts. It is meant to make code easier to read. I personally would stumble on procession of highlighted braces and unhighlighted brackets.

**Comment by egor-rogov** [comment]
A thought about Prism's work.
See those `{document}` and `{epsfig,multicol}` colored blue? That's what I meant suggesting highlighting macro parameters. I think it would  be helpful - if we can devise proper rules for it. Usually these are macros started on the beginning of the line, and text inside braces (and brackets) is limited to words, or "word=something", or comma-separated list of the above...

**Comment by schtandard** [comment]
I tried my best at implementing the verbatim stuff without lookbehind. It got a bit more involved, of course (but works really well, I think). Would that be okay?

**Comment by schtandard** [comment]
> So you're saying the `$` and `$$` rule in the current grammar is woefully broken/inadequate then because all sorts of stuff can appear between the $$ to change the mode?

The current grammar is mostly woefully inadequate due to it's utter incompleteness. It only supports two syntaxes of switching to math mode, one of which has been deprecated for decades.

We could of course implement the most common ways to do this, I'd say there are probably between 10 and 20 we should support in that case (would have to look around and make a list to be sure). This would probably cover the vast majority of uses in the `document` environment part of a LaTeX doccument. Doing this in the preamble (where no typesetting takes place) is a lost cause and shouldn't even be attempted I think, except for maybe `\ensuremath`.

However, code snippets online frequently omit the commands shifting to and from math mode when it is clear from context that one is writing about math mode. I do realize that [tex.sx] (which is what brough me here) is just one site, but I expect that the vast majority of LaTeX documents and code snippets that are actually typeset using `highlight.js` will be typeset there. (Correct me if I'm wrong; I don't actually know how widespread `highlight.js` is. I do know that tex.sx is _the_ site for LaTeX support on the web.) And the code that is typeset there is often just a snippet and never a full-blown document with hundreds of pages of text and formulas.

So, while doing this would probably highlight the majority of finished documents that are compiled using LaTeX "correctly", I'm not sure this is true about the aggregate of all code _actually highlighted_ using `highlight.js`.

(I'm not sure were your focus lies.)

[tex.xs]: https://tex.stackexchange.com/

> How did we decide control sequences are `keyword`s and not `tag`s` as in the original implementation? (I just noticed this)

Well, I scratched all the CSS classes when I started out and had a look at [the documentation][css-classes] when I wanted to put in some that are actually supported. The description of `tag` reads
> XML/HTML tag

and is in the section "Tags, attributes, configs". It didn't seem remotely right for control sequences. I thought (and think) that `keyword` is the best fit. (Even though these are of course not keywords; there are no keywords in TeX. But that is true about most of the other classes, too.)

[css-classes]: https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html

**Comment by schtandard** [comment]
> 
> 
> It's worth noting our original unit rule was scoped to "variable like" statements:
> 
> ```
> \hoffset=0pt
> \voffset=.3em
> \tolerance=400
> ```
> 
> Is highlighting numbers/units only after `=` problematic?

I'd say it is still problematic, because this is also a common syntax in typeset math (e.g. `\theta=0`). If we tried to detect math mode, we could of course disable that rule there. Then it would depend a lot on how good the math mode detection is. The disabling would of course not work in code snippets with no formal indication of math mode or in math environment that are not specifically implemented in the grammar.

> Is this a common pattern to set variables? (I'm not sure what I'm looking at)

That is the more important issue. Most users set numbers and dimens using macros (an uncountable number of different macros). Highlighting just this pattern would actually highlight only a minority of instances where numbers and dimens are assigned. I think the choice really is between either highlighting all numbers and things that look like units everywhere and live with the fact that it will often highlight things that are not numbers to TeX but characters, or to not highlight them at all.

**Comment by schtandard** [comment]
>     * sections/chapter headlines (we do have CSS for this)
> 
>     * urls (we have CSS for `links`)
> 
>     * (these confuse me a little though unless we think of LaTex as markup, in which they make more sense)

URLs is actually a good point, we should include that, too. (It's basically a verbatim macro.)

> I would be curious to hear your thoughts on highlighting more "markup" stuff like sections/headers/urls, etc.. Since those seem to be commonly encoded in LaTex and would be easy enough to match.

This is something many syntax highlighters do: Highlighting the some common macros that give structure to the document. I think it's okay to do this, it will probably really help break the monotony of LaTeX code in some cases. Specifically, the following macros could be included:
- `\documentclass`, `usepackage`, `\begin{document}` and `\end{document}` should certainly be included if we did this.
- `\NeedsTeXFormat`, `\ProvidesPackage`, `\RequirePackage` and the like should then also be included, I think. (These are only used in packages.)
- `\makeatletter`, `\makeatother`, `\ExplSyntaxOn` and `\ExplSyntaxOff` I would also include.
- `\part`, `\chapter`, `\section`, `\subsection`, `\subsubsection`, `\paragraph` and `\subparagraph` are also a no-brainer.
- `\begin` and `\end` generally, I'm a bit on the fence, tending a bit towards yes. Maybe just highlighting their argument (the name of the environment) could be a nice solution.
- Labels as in `\label`, `\ref` and friends (but not the macro itself) could also be included. There are a lot of `\ref`-like macros, but I think they mostly have the same syntax. I'd have to check. (This would be a project for a later merge, I think.)

I would argue against including
- Macro definition commands like `\newcommand`. There are just way to many of them with a huge variety of syntaxes (even LaTeX editors have a hard time keeping track).
- Probably anything I didn't think of right now. ;-)

Which classes to use for this should be carefully chosen though. For example, `\section{A Cool Section}` should be much more pronounced (definitely not less) than the rest of the code in the default styles. The description of the `section` class leaves me unsure if that is usually the case.

> heading of a section in a config file, heading in text markup

**Comment by schtandard** [comment]
> A thought about Prism's work.
> See those `{document}` and `{epsfig,multicol}` colored blue? That's what I meant suggesting highlighting macro parameters. I think it would be helpful - if we can devise proper rules for it. Usually these are macros started on the beginning of the line, and text inside braces (and brackets) is limited to words, or "word=something", or comma-separated list of the above...

I think that would also be kind of what you were thinking about here, right?

**Comment by schtandard** [comment]
> I personally would stumble on procession of highlighted braces and unhighlighted brackets.

In that case I would much prefer not highlighting the braces over also highlighting brackets. I think there would be a rather large number of unavoidable false highlights, especially in math mode. I wouldn't know how to tell that `... \theta [ a + b ] ...` and `\left[ ...` are not macro arguments. In addition, brackets are often unmatched here, which could then lead to some other closing bracket being highlighted later in the code.

**Comment by schtandard** [comment]
> @schtandard Could you please work up some simple aliases (or just names) for the CSS... even if we have no way to encode them yet... if nothing else we'll add this to the grammar as a comment...

> As in if you weren't restricted to our existing names, what would these things be called in LaTex land? 

Sure.
With the last commit that would be:
```
comment <- comment
meta    <- magic_comment
keyword <- control_sequence
keyword <- active_character
params  <- macro_parameter
builtin <- math_shift
builtin <- alignment_tab
builtin <- math_sub_sup
builtin <- brace
string  <- verbatim_code
```
(For actual classes, I would probably use some common abbreviations here and there, but that's not the point here, right?)

> (you could add to the original PR message)

Not sure what you mean here. (This is my first pull request.) Do you mean the first message in this thread? Is that special in any way? (I'd think it's somewhat outdated by now..)

**Comment by schtandard** [comment]
> - Forget about units [...]

Done. :-)

**Comment by joshgoebel** [comment]
> Which classes to use for this should be carefully chosen though. For example, \section{A Cool Section} should be much more pronounced (definitely not less) than the rest of the code in the default styles. The description of the section class leaves me unsure if that is usually the case.

*This is not a decision for grammar authors.*  If someone wants pronounced headings, then they can choose a style that provides that.  If they don't then they can choose a style that does not highlight them prominently.  _The grammars job is to describe what it sees - not dictate its visual appearance._  Headers (being headings) are often highlighted prominently in themes, but not always.

Someone who wants full control of the visual side of highlighting should pick their theme carefully (or be using a custom theme).

**Comment by joshgoebel** [comment]
> However, code snippets online frequently omit the commands shifting to and from math mode when it is clear from context that one is writing about math mode. I do realize that [tex.sx] (which is what brough me here) is just one site, but I expect that the vast majority of LaTeX documents and code snippets that are actually typeset using highlight.js will be typeset there.

We have millions of downloads each week... no idea.  But I would never assume a single context of usage... if that was truly the case this would be better as a 3rd party module (allowing `tex.sx` complete freedom) rather than being part of the core library at all... just currently we have no precedent for "demoting" languages from the core library into 3rd party modules.

> However, code snippets online frequently omit the commands shifting to and from math mode when it is clear from context that one is writing about math mode. 

We never know (in any context) if we're given a snippet or a full source file... so we always try and do our "best effort"... sometimes this means slightly poorer results with snippets, esp. for more context-aware grammars.

**Comment by joshgoebel** [comment]
This latest interation is VERY abstract, so I'm still processing it, but I'll drop a few notes...

File: src/languages/latex.js [hunk 1]
```diff
@@ -1,70 +1,231 @@
...
+        contains: arg,
+        starts: starts_mode
+      }
+    };
+  };
+  var CSNAME = function(csname, starts_mode) {
+    return hljs.inherit(
+      {
+        begin: '\\\\' + csname + '(?![a-zA-Z@:_])',
+        keywords: {$pattern: /\S+/, keyword: '\\' + csname}
```
Comment (joshgoebel) [inline src/languages/latex.js:169]: Pretty sure `\S+` if FAR too broad... can we pin that down to what is actually a valid identifier?

File: src/languages/latex.js [hunk 2]
```diff
@@ -1,70 +1,231 @@
...
+  };
+  var VERBATIM = {
+    variants: [
+      CSNAME('verb', {contains: [VERBATIM_DELIMITED_EQUAL]}),
+      CSNAME('lstinline', {contains: [VERBATIM_DELIMITED_EQUAL]}),
+      CSNAME('mint', ARGUMENT_AND_THEN(ARGUMENT_M, {contains: [VERBATIM_DELIMITED_EQUAL]})),
+      CSNAME('mintinline', ARGUMENT_AND_THEN(ARGUMENT_M, {contains: [VERBATIM_DELIMITED_BRACES, VERBATIM_DELIMITED_EQUAL]})),
+      CSNAME('url', {contains: [PATCH_CLASSNAME(VERBATIM_DELIMITED_BRACES, 'link'),
+                                PATCH_CLASSNAME(VERBATIM_DELIMITED_EQUAL, 'link')]}),
+      BEGIN_ENV('verbatim',    {starts: VERBATIM_DELIMITED_ENV('verbatim')}),
```
Comment (joshgoebel) [inline src/languages/latex.js:212]: What are all these "*" variants?  Looks like we could do this with a loop, no?  Defining both rules from a single list? (other than the minted exception)

File: src/languages/latex.js [hunk 3]
```diff
@@ -1,70 +1,231 @@
...
+      BEGIN_ENV('verbatim\\*', {starts: VERBATIM_DELIMITED_ENV('verbatim\\*')}),
+      BEGIN_ENV('Verbatim',     ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('Verbatim')})),
+      BEGIN_ENV('Verbatim\\*',  ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('Verbatim\\*')})),
+      BEGIN_ENV('BVerbatim',    ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('BVerbatim')})),
+      BEGIN_ENV('BVerbatim\\*', ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('BVerbatim\\*')})),
+      BEGIN_ENV('LVerbatim',    ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('LVerbatim')})),
+      BEGIN_ENV('LVerbatim\\*', ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('LVerbatim\\*')})),
```
Comment (joshgoebel) [inline src/languages/latex.js:219]: Are you double nesting starts here?  `ARGUMENT_AND_THEN` already has `starts` (line 161), I'm not sure why it's also listed here?

File: src/languages/latex.js [hunk 4]
```diff
@@ -1,70 +1,231 @@
...
+  var BEGIN_ENV = function(envname, starts_mode) {
+    return hljs.inherit(
+      {
+        begin: '\\\\begin(?=\\s*\\r?\\n?\\s*\\{' + envname + '\\})',
+        keywords: {$pattern: /\S+/, keyword: '\\begin'}
+      },
+      ARGUMENT_AND_THEN(ARGUMENT_M, starts_mode)
+    );
+  };
+  var VERBATIM_DELIMITED_EQUAL = hljs.END_SAME_AS_BEGIN({
```
Comment (joshgoebel) [inline src/languages/latex.js:183]: Why do we need END_SAME_AS_BEGIN here, isn't this really just two different variants?

File: src/languages/latex.js (hunk 1 above)
Comment (schtandard) [reply src/languages/latex.js:169]: Of course, `\\[a-zA-Z]+` is sufficient here. I just didn't think it made a difference, since this regex is only applied to the one string on the same line. Will change that.

File: src/languages/latex.js (hunk 2 above)
Comment (schtandard) [reply src/languages/latex.js:212]: Yes, we could also combine the `[BL]Verbatim\*?` variants into a loop. Not sure about the clearest way to do that, though. Do you mean just adding a bare loop that modifies the `VERBATIM` object?

Comment (joshgoebel) [reply src/languages/latex.js:212]:
```
// for
      BEGIN_ENV(X,     ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('Verbatim')})),
      BEGIN_ENV(X + "*",  ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('Verbatim\\*')})),
// end
```

File: src/languages/latex.js (hunk 3 above)
Comment (schtandard) [reply src/languages/latex.js:219]: I am. What I need to do after finding, say, `\begin{minted}` is looking for one optional pair of brackets (with arbitrary highlighted content) followed by exactly one pair of braces (with arbitrary highlighted content) followed by the verbatim content (i.e. `string`). The only possibility for adding such a sequence of syntax elements I saw is `starts` (used repeatedly), but maybe I missed something?

Comment (joshgoebel) [reply src/languages/latex.js:219]: You're writing `{starts: { starts: ... }}` though from what I can see you don't need the extra empty starts.

Comment (joshgoebel) [reply src/languages/latex.js:219]: Why not:

```
BEGIN_ENV('Verbatim',     ARGUMENT_AND_THEN(ARGUMENT_O, VERBATIM_DELIMITED_ENV('Verbatim'))),
```

File: src/languages/latex.js (hunk 4 above)
Comment (schtandard) [reply src/languages/latex.js:183]: Not sure what you mean here. (Maybe you mistook `.` for `\.` in the regex?) `VERBATIM_DELIMITED_EQUAL` looks for an arbitrary character (including newlines) and marks everything up to the next occurrence of that same character as verbatim (`string`).

Comment (joshgoebel) [reply src/languages/latex.js:183]: > Maybe you mistook . for \. in the regex?)

LOL.  That makes a lot more sense now. :)

**Comment by schtandard** [comment]
A question on variable declarations (I'm not so firm in JavaScript anymore): I declared everything as `var` and with all caps names because that's how I saw it done in other languages, even though it's a bit weird to me (isn't that usually only used for constants?). But I assume that at least the functions could be `const` instead, right? What is the "right" declaration here?

File: src/languages/latex.js (hunk 3 above)
Comment (schtandard) [reply src/languages/latex.js:219]: (Oh, and an arbitrary number of spaces and one newline should be allowed between these elements, but that's a detail.)

**Comment by joshgoebel** [comment]
What is with all the use of `endsParent`... are you trying to return to the parent mode to trigger the next `starts`?  This isn't real chaining... to do real chaining the starts would have to be nested...

Right now `ARGUMENT_AND_THEN` can't guarantee an argument at all... contains could match absolutely nothing and then it will just jump on to the next `starts` trying to match the next argument.  Is that the desired behavior?

To do true chaining you'd have to have a structure like:

```
{starts:
 contains : [ 
   // first thing
   starts: {
     contains: [ 
     // second thing
     starts: {
        contains: [ // third thing
```

**Comment by joshgoebel** [comment]
>  declared everything as var and with all caps names because that's how I saw it done in other languages, even though it's a bit weird to me (isn't that usually only used for constants?).

You should be using `const` everywhere... I think a few things perhaps shouldn't be uppercase, but I'll probably clean that up in a final pass after this is approved.  Most of the modes should be uppercase (our convention).

File: src/languages/latex.js (hunk 4 above)
Comment (schtandard) [reply src/languages/latex.js:183]: (The newline really is an edge case, but I thought including it won't hurt, as it doesn't change the rule otherwise.)

**Comment by joshgoebel** [comment]
And I'm left confused by things like: `BEGIN_ENV('minted', ARGUMENT_AND_THEN(ARGUMENT_O, ARGUMENT_AND_THEN(ARGUMENT_M, {starts: VERBATIM_DELIMITED_ENV('minted')}))),`

Whta does it mean to have an optional argument following by a mandatory argument?

**Review by schtandard — COMMENTED** [review]
> What is with all the use of `endsParent`... are you trying to return to the parent mode to trigger the next `starts`? This isn't real chaining... to do real chaining the starts would have to be nested...

The `endsParent` is meant to make sure that the rule is not applied multiple times in a row. Either somewhere in the chain
```
{
  contains: A,
  starts: B
}
```
where `A` is one or more rules and I am looking for only one match to one of them, or at the end of the chain, where I am also looking for only one match.

> Right now `ARGUMENT_AND_THEN` can't guarantee an argument at all... contains could match absolutely nothing and then it will just jump on to the next `starts` trying to match the next argument. Is that the desired behavior?

That's true. It's not too terrible, since that argument missing would lead to an error in TeX and highlighting it the wrong way is forgivable, I think, but aborting the chain would be better. Not sure how to do that, though.

> To do true chaining you'd have to have a structure like:
> 
> ```
> {starts:
>  contains : [{
>    // first thing
>    starts: {
>      contains: [ {
>      // second thing
>      starts: {
>         contains: [{ // third thing
> ```
> 
> This probably works for ARGUMENT_O but I'm guessing it doesn't do exactly what you think for ARGUMENT_M.

Isn't that what I'm doing? Every call to `ARGUMENT_AND_THEN` adds one layer of nesting. (Two, actually, to account for possible spaces.)

**Comment by schtandard** [comment]
> And I'm left confused by things like: `BEGIN_ENV('minted', ARGUMENT_AND_THEN(ARGUMENT_O, ARGUMENT_AND_THEN(ARGUMENT_M, {starts: VERBATIM_DELIMITED_ENV('minted')}))),`
> 
> Whta does it mean to have an optional argument following by a mandatory argument?

That is not a problem in LaTeX, since there are no "true" optional arguments. An optional argument (the bracket kind, which is the most common) just means: If the next thing is a `[`, grab everything up to the next `]` (that is not inside a brace group) and treat that as the optional argument. If the next thing is not a `[`, treat the optional argument as absent. This works before, after or between other kinds of arguments.

> It might be worth it to walk me thru some actual examples of:
> 
>     * ```
>         BEGIN_ENV('Verbatim\\*',  ARGUMENT_AND_THEN(ARGUMENT_O, {starts: VERBATIM_DELIMITED_ENV('Verbatim\\*')})),
>       ```
> 
> 
> ( with and without argument)

Alright. The syntax is
```latex
\begin{Verbatim*}
Some verbatim code here
\end{Verbatim*}
```
With the optional argument:
```latex
\begin{Verbatim*} [gobble=2]
Some verbatim code here
\end{Verbatim*}
```

For `minted` some possible examples are:
```latex
\begin{minted}{language}
Some verbatim code here
\end{minted}
```
With an optional argument:
```latex
\begin{minted}[gobble=2]{language}
Some verbatim code here
\end{minted}
```
For long arguments, it is common to break this across lines:
```latex
\begin{minted}
  [gobble=2, more options]
  {language}
Some verbatim code here
\end{minted}
```
The details are that there may not be blank lines between the arguments and there may not be a line break before trailing optional arguments, but a highlighter does not have to enforce these rules, I think.


> 
>     * ```
>          BEGIN_ENV('minted', ARGUMENT_AND_THEN(ARGUMENT_O, ARGUMENT_AND_THEN(ARGUMENT_M, {starts: VERBATIM_DELIMITED_ENV('minted')}))),
>       ```
> 
> 
> Might be a better way to structure this.

Not sure what you mean here?

File: src/languages/latex.js (hunk 3 above)
Comment (schtandard) [reply src/languages/latex.js:219]: Ah! That is a good question. No idea, it's an oversight. Will change it.

File: src/languages/latex.js (hunk 2 above)
Comment (schtandard) [reply src/languages/latex.js:212]: Are you writing pseudocode with those comments or is there some preprocessor magic I'm not aware of? (If so, what should I google?)

**Comment by Skillmon** [comment]
Some comments on your rules (not sure whether still valid):
 
>     * Anything that looks like
>       `\` + maybe `__` + two or more `[a-zA-Z]` + `_` + two or more `[a-zA-Z_]` + `:` + any number of `[nNcVvoxefTFpwD]`
>       is a LaTeX3 function.

Why two or more? Seems like an arbitrary limitation to multi-letter modules. This should be "one or more" instead in both cases (`\o_o:` is a stupid but valid name).

> 
>     * Anything that looks like
>       `\` + `[qs]` + one or two `_` + two or more `[a-zA-Z_]`
>       is a LaTeX3 quark or scan mark.

Should be "`\` + `[qs]` + one or two `_` + `[a-zA-Z]` + any number of `[a-zA-Z_]`". (`\q___` doesn't look like a valid name).

> ### The double caret syntax
> 
> I included the double caret syntax for inputting characters, but only for control symbols and outside of macros. This covers the vast majority of use cases. (They can also appear in control words, but that is not really relevant and very hard to implement.)
> 
> These characters do not receive any special highlighting right now. The mode just makes sure that they are not wrongly highlighted (which would always happen otherwise).

Since double caret syntax can be confusing (especially for people new to (La)TeX), I'd think they should be highlighted.

> ### Active characters
> 
> As far as I know, `~` is always active (or a space when in LaTeX3 code) and `"` is either active or unused (except for hex input). I included a rule for highlighting them like control sequences.
> 
> I'm not dead-set on this, though. If anyone thinks this is a bad idea, I'm open to being convinced.

**Comment by Skillmon** [comment]
Regarding optional arguments: If `xparse` is used, the brackets must be balanced as long as they are not surrounded by braces (e.g., test `\NewDocumentCommand\foo{O{}}{\def\tmp{#1}\show\tmp}\foo[a[b]c]\foo[a{[}b]c]`). In other cases only closing brackets that are not nested inside of `{}` count as the right delimiter. (I'm sure you know this, but I just wanted to show that getting them right can be arbitrarily hard).

**Comment by schtandard** [comment]
> > ```
> > * Anything that looks like
> >   `\` + maybe `__` + two or more `[a-zA-Z]` + `_` + two or more `[a-zA-Z_]` + `:` + any number of `[nNcVvoxefTFpwD]`
> >   is a LaTeX3 function.
> > ```
> 
> Why two or more? Seems like an arbitrary limitation to multi-letter modules. This should be "one or more" instead in both cases (`\o_o:` is a stupid but valid name).

The thought was to avoid misidentifying math as a LaTeX3 macro. I can see lots of people writing something like `\theta_a:` in their documents. Only detecting function names of two or more letters is an easy way to avoid this (and I don't think one-letter function names really exist; at least they shouldn't).

Dropping that condition for the module name would probably be safe. (Though, like with function names, I don't think one-letter module names do or should exist.)

> > ```
> > * Anything that looks like
> >   `\` + `[qs]` + one or two `_` + two or more `[a-zA-Z_]`
> >   is a LaTeX3 quark or scan mark.
> > ```
> 
> Should be "`\` + `[qs]` + one or two `_` + `[a-zA-Z]` + any number of `[a-zA-Z_]`". (`\q___` doesn't look like a valid name).

Good point. (I would still require a name of at least two characters for the same reason as with functions, though.)

> > ### Active characters
> > As far as I know, `~` is always active (or a space when in LaTeX3 code) and `"` is either active or unused (except for hex input). I included a rule for highlighting them like control sequences.
> > I'm not dead-set on this, though. If anyone thinks this is a bad idea, I'm open to being convinced.
> 
> I'm against specifically highlighting active characters. There can be arbitrarily many (e.g., `\usepackage[turkish]{babel}` will make `=` active).

Thanks for that note. After looking into it, I found that additionally, `arabic` uses `_`, `^`, `.` and `'` as shorthands (i.e. active characters). This makes me agree that we should not highlight active characters at all.

**Comment by PhelypeOleinik** [comment]
First of all: wow, this is amazing. Thanks!

> Dropping that condition for the module name would probably be safe. (Though, like with function names, I don't think one-letter module names do or should exist.)

Technically no, there shouldn't be one-letter module names (and two- and three-letter ones should be rare as well).  The problem with short module names is that you can only have so many available, and then you end up with the old problem of name clashes.  Long-term we (the LaTeX project) would like modules to be registered, so there's a comprehensive list of the ones used (thus the ones available) and we encourage authors to prefer longer, more descriptive module names (so 4+ letters), so I think it's safe to assume 2+ letters.

But of course as everything in TeX it's not a rule, just a friendly agreement not to break conventions :-)

**Comment by joshgoebel** [comment]
I'm confused why we have to individually detect all these variants and all this chaining... can't this be done much simpler with a END_SAME_AS_BEGIN:

```
\begin{minted} (begin)
  [gobble=2, more options] (allow [.*] )
  {language} (allow {.*} )
Some verbatim code here
\end{minted} (end)
```
IE:

- a begin/end pair has a "name", which is what END_SAME_AS_BEGIN is matching
- [.*] can be matched multiple times
- {.*} can be matched multiple times
- Remaining text is literal verbatim...

This seems like it would work for all the examples shown above...

**Comment by Skillmon** [comment]
@joshgoebel how about the following valid TeX code:

```latex
\begin{minted}[%
  ,gobble=2
  ,more
  ,options
]{%
language}
some verbatim code here
\end{minted}
```

**Comment by schtandard** [comment]
> I'm confused why we have to individually detect all these variants and all this chaining... can't this be done much simpler with a END_SAME_AS_BEGIN:
> 
> ```
> \begin{minted} % (begin)
>   [gobble=2, more options] % (allow [.*] )
>   {language} % (allow {.*} )
> Some verbatim code here
> \end{minted} % (end)
> ```
> 
> IE:
> 
>     * a begin/end pair has a "name", which is what END_SAME_AS_BEGIN is matching
> 
>     * [.*] can be matched multiple times
> 
>     * {.*} can be matched multiple times
> 
>     * Remaining text is literal verbatim...
> 
> 
> This seems like it would work for all the examples shown above...

It would work for those examples, yes (provided `Some verbatim code` does not start with `[` or `{`, and one may even argue that it would be good enough. However, it does not work for the inline commands, e.g. `\mintinline`, where the verbatim code comes after the first balanced brace group after the command, either itself in braces or in a pair of identical symbols. That is
```latex
\mintinline{language}{Some verbatim code here}
\mintinline{language}|Some verbatim code here|
```
need to work.

Also, the regexes you mentioned aren't sufficient (`\[.*\]`, `\{.*\}`) even for the environments, as we'd still have to keep track of nested braces to avoid mistakes with common patterns like `{{}}` or `[{[]}]`.

**Comment by schtandard** [comment]
I'd like to restate my question from earlier, since it may help avoiding group-chaining like this for some patterns:
> 1. Is it possible to assign different CSS class names to different regex capturing groups of the same match?
That is, can I for example match a regex with three capturing groups and then tell highlight.js that I want the first group to be a keyword, the second to be a function and the third to be a literal?

For example, could I match to `(\\mintinline)(\{)([a-zA-Z]+)(\})` and highlight the first capturing group (`\\mintinline`) as a control sequence, the second and fourth (`{` and `}`) as braces and not highlight the third?

**Comment by schtandard** [comment]
> We have millions of downloads each week... no idea.

Regarding the current state of the LaTeX grammar and the lack of issues about it, I'd be willing to bet that those are not for LaTeX. ;-)

> But I would never assume a single context of usage...

Of course, and I didn't mean to advertise catering to only tex.sx, just wanted to point to the most prominent example of usage. I do think LaTeX should be in the core library and I believe we're getting to something good here.

> We never know (in any context) if we're given a snippet or a full source file... so we always try and do our "best effort"... sometimes this means slightly poorer results with snippets, esp. for more context-aware grammars.

Would highlighting just the start and end macros of math contexts (like `\(` or `\begin{align*}`) be acceptable? That way, if the context switchers are present, they are highlighted, but if they are not, the highlighting is still consistent. This would also tie in nicely with highlighting other commands like `\section{...}` and maybe `\begin{...}` generally.

**Comment by schtandard** [comment]
@PhelypeOleinik Can you give any insights on how likely it is that the list of existing `expl3` argument types will be changed in, say, the next decade? Can you think of any reason not to match function signatures with `[a-zA-Z]*`?

**Comment by PhelypeOleinik** [comment]
> @PhelypeOleinik Can you give any insights on how likely it is that the list of existing `expl3` argument types will be changed in, say, the next decade?

Absolutely no idea. Until not so long ago (TeXLive 2015) we didn't have the `e`-type expansion, only `x`, but then it was derived from the latter based on the different treatment of parameter tokens. I can't think of any new type, but it might happen (though very unlikely) that we derive a new one, but I find it unlikely.

> Can you think of any reason not to match function signatures with `[a-zA-Z]*`

The rules you stated above for determining if something is a LaTeX3 macro seem good to me, but as you know, `\__some_macro:funny_signature` is equally valid (though very much frowned upon :-), so I think I'd find odd (albeit correct) that highlighting stopped at the `f` in `funny_signature`; I think I'd use `[a-zA-Z]*`.

> (including the special case of `\::X`)?

(also there's `\:::` and `\::x_unbraced` and so on but) I wouldn't bother with those: they are seldom used in code, so I don't feel they need special treatment.

**Comment by schtandard** [comment]
> I think I'd use `[a-zA-Z]*`.

Great, thanks. That was my feeling, too.

**Comment by joshgoebel** [comment]
To be clear I wasn't talking about doing it with pure regex (sorry for not being clearer), only if there is truly a need for all this special-casing.

IE, could a single rule (or a few) with a list of sequential modes.  It's ok in mintinline is different:

So why not match (with regex or modes, again not dictating that):

```
\\thingy(optional)?(optional)?[verbatim]?
```

Why do we NEED to track that this specific command has ONE optional argument and then ONE maditory argument?  That sounds very very precise and like we're trying to do too much.

> Is it possible to assign different CSS class names to different regex capturing groups of the same match?
That is, can I for example match a regex with three capturing groups and then tell highlight.js that I want the first group to be a keyword, the second to be a function and the third to be a literal?

No.  The way you'd do that would be to write a generic helper around chaining... but my issue isn't with your chaining, it's with the explicitness of the rules.  It's ok if we need a chain like:

```
thing -> argument -> argument -> verbatim
```

But why do we nede to keep track of a list of commands and which arguments are manditory or optional PER command?  

> Regarding the current state of the LaTeX grammar and the lack of issues about it, I'd be willing to bet that those are not for LaTeX. ;-)

Yeah, it's just one metric... I have no idea to judge how many people if any were using the existing LaTex support. The broader point was about not assumign we're for a single website. :-)

> Would highlighting just the start and end macros of math contexts (like \( or \begin{align*}) be acceptable? That way, if the context switchers are present, they are highlighted, but if they are not, the highlighting is still consistent.

I'm not sure what you're asking here.

**Comment by joshgoebel** [comment]
What we're missing here currently are `markup` tests for LaTex, could you add some?  We need them anyways... I think that would really help me.

So for your each of your explicit rules (lines  206-222) you'd have a few variants of markup tests... then I could open up the grammar, simplify it myself, re-run the tests... and if the test suits still passes then I can show you what I'm talking  about vs talking in abstractions and we can discuss if there are OTHER edge cases that are missing.

And when/if the test suits fails then I'll understand why it's more complicated than I think it is. :-)

**Comment by joshgoebel** [comment]
> Is it possible to assign different CSS class names to different regex capturing groups of the same match?
That is, can I for example match a regex with three capturing groups and then tell highlight.js that I want the first group to be a keyword, the second to be a function and the third to be a literal?

It shouldn't be impossible to  abstract this to a nice helper though, and it's been on my list of things to play with... so once we have some tests and if you gave me just one example I could take a pass at it... I'd really want to see an API where you just write out the sequence in terms of modes:

```
sequence: [RULE_START, ARGUMENT, ARGUMENT, VERBATIM]
```

So we might have something like (if all these variants are still required):

```
variants: [
  { sequence: [RULE_START_VERBATIM, ARGUMENT, ARGUMENT, VERBATIM] }
  { sequence: [RULE_START, ARGUMENT] }
  { sequence: [RULE_START, ARGUMENT, ARGUMENT] }
]
```

Or something.

**Comment by joshgoebel** [comment]
If we're starting to be reasonably happy with what the current grammar is doing now (behavior wise) then I think the next step is adding markup tests for that behavior...  then that will allow us the flexibility to play around with the grammar and see what can be further simplified and what can not be.

**Comment by schtandard** [comment]
> To be clear I wasn't talking about doing it with pure regex (sorry for not being clearer), only if there is truly a need for all this special-casing.

Ah, ok. In that case I misunderstood.

I don't think there is a need for all of the special casing in case of the verbatim environments. Verbatim code (in an environment) starting with `[` or `{` is unusual enough that getting that wrong would be acceptable, I think.

I was just thinking that, since we already need the machinery for the inline commands (like `\mintinline`), we may as well use it for the environments, too. I'll change that.

**Comment by joshgoebel** [comment]
> Verbatim code (in an environment) starting with [ or { is unusual enough that getting that wrong would be acceptable, I think.

I'm not saying we have to break things. :-)  I'm wondering if it can be simplified WITHOUT breaking things.  Having some tests we could play with would set our "baseline".

File: src/languages/latex.js (hunk 2 above)
Comment (schtandard) [reply src/languages/latex.js]: Could you clarify this for me? I'm still a bit unsure how to interpret this code snippet. I would have maybe tried something like
```
...['verbatim', 'verbatim\\*'].map(csname => BEGIN_ENV(csname, VERBATIM_DELIMITED_ENV(csname))),
```
but it seems like you had a different (possibly clearer) syntax in mind.

**Comment by schtandard** [comment]
> If we're starting to be reasonably happy with what the current grammar is doing now (behavior wise) then I think the next step is adding markup tests for that behavior... then that will allow us the flexibility to play around with the grammar and see what can be further simplified and what can not be.

Ok, will do.

Am I correct in assuming that the tests should only include cases that are (and should) be highlighted correctly (not edge-cases that we already decided not to support)?

**Comment by joshgoebel** [comment]
> Am I correct in assuming that the tests should only include cases that are (and should) be highlighted correctly (not edge-cases that we already decided not to support)?

Yes, though if there is anything we were "on the fence" about you could include that with a note that it isn't highlighted correctly and a short reason why, etc...

I'm talking about the tests in `markup`, you can look at many other languages for examples... you just create a source file and a "expects" file... I assume we'd group the tests into a few files (as made sense).  You're probably a better judge of how to do that than I am.

**Comment by schtandard** [comment]
> _What we're **really** missing here currently_ are `markup` tests for LaTex

I added some. Will look them over again tomorrow, but they should be good enough to play around with right now.

**Comment by schtandard** [comment]
@joshgoebel Did you get any time to look at this?

**Comment by joshgoebel** [comment]
Taking a look now.  Of what purpose is ARGUMENT_NONE?  Just to gobble space?  All tests pass with:

```
  var CSNAME = function(csname, starts_mode) {
    return {
        begin: '\\\\' + csname + '(?![a-zA-Z@:_])',
        keywords: {$pattern: /\\[a-zA-Z]+/, keyword: '\\' + csname},
        contains: [SPACE_GOBBLER],
        starts: starts_mode
      };
  };
```

**Comment by joshgoebel** [comment]
```
  const CONTROL_SEQUENCE = {
    className: 'keyword',
    begin: /\\/,
```

I'm thinking this may be wrong now also... that it should be scored relevance 0... really `\\` alone means nothing... I could imagine comment headers being written in such a way to have huge groups of these in a row.

Why wouldn't we give the relevance instead to L2_VARIANTS... so that really patterns like `\\some_l2_variant` got the credit but then we would never pick up any false positives from `\\` alone?

File: test/markup/latex/control_sequences.txt [hunk 5]
```diff
@@ -0,0 +1,35 @@
+\foo bar
+\foo:bar
+\
+\
```
Comment (joshgoebel) [inline test/markup/latex/control_sequences.txt:4]: Should these all alone really still be highlighted as keywords?

File: src/languages/latex.js [hunk 6]
```diff
@@ -1,70 +1,263 @@
...
+      'use(?:_i)?:[a-zA-Z]*',
+      '(?:else|fi|or):',
+      '(?:if|cs|exp):w',
+      '(?:hbox|vbox):n',
+      '::[a-zA-Z]_unbraced',
+      '::[a-zA-Z:]'
+    ].map(pattern => pattern + '(?![a-zA-Z:_])').join('|'));
+  const L2_VARIANTS = [
+    {begin: /[a-zA-Z@]+/}, // control word
+    {begin: /[^a-zA-Z@]?/} // control symbol
```
Comment (joshgoebel) [inline src/languages/latex.js:43]: Could this not use KNOWN_CONTROL_SYMBOLS?  This looks overly broad.

File: src/languages/latex.js [hunk 7]
```diff
@@ -1,70 +1,263 @@
...
+    className: 'built_in',
+    relevance: 0,
+    begin: /[$&^_]/
+  };
+  const BRACES = {
+    className: 'built_in',
+    relevance: 0,
+    begin: /[{}]/
+  };
+  const MAGIC_COMMENT = hljs.COMMENT(
```
Comment (joshgoebel) [inline src/languages/latex.js:98]: Would this typically have "normal" comment explanation text or doctags?  All the examples I saw looked VERY specific, not general purpose comments.

If so we probably shouldn't use the COMMENT mode but rather just turn this into a normal rule. (to avoid all the extra junk COMMENT carries with it which I think may not apply here.) Thoughts?

**Comment by joshgoebel** [comment]
I think overall this is starting to look good. :-)  If we finish in the next few days would love to include in 10.3.

File: src/languages/latex.js [hunk 8]
```diff
@@ -1,70 +1,263 @@
...
+      ARGUMENT_AND_THEN(ARGUMENT_M, starts_mode)
+    );
+  };
+  const VERBATIM_DELIMITED_EQUAL = (innerName = "string") => {
+    return hljs.END_SAME_AS_BEGIN({
+      className: innerName,
+      begin: /(.|\r?\n)/,
+      end: /(.|\r?\n)/,
+      excludeBegin: true,
+      excludeEnd: true,
```
Comment (joshgoebel) [inline src/languages/latex.js:193]: Is the fact that we want to exclude the begining and end the only reason we couldn't do this with a much simpler regex with a match group?

**Comment by schtandard** [comment]
> Of what purpose is ARGUMENT_NONE? Just to gobble space?

Yes, just to gobble spaces. It's probably clearer to just use `SPACE_GOBBLER` directly.

Should we rename 'ARGUMENT_ABSENT' in the same vein? It could also be called "END_PARENT", since all it does is immediately terminate the parent mode.

**Comment by schtandard** [comment]
> ```
>   const CONTROL_SEQUENCE = {
>     className: 'keyword',
>     begin: /\\/,
> ```
> 
> I'm thinking this may be wrong now also... that it should be scored relevance 0... really `\` alone means nothing... I could imagine comment headers being written in such a way to have huge groups of these in a row.
> 
> Why wouldn't we give the relevance instead to L2_VARIANTS... so that really patterns like `\some_l2_variant` got the credit but then we would never pick up any false positives from `\` alone? I see of all the rules you purposely set L2_VARIANTS to 0 for some reason? Do we know of some other language that uses `\ident`?

The problem is that every `\` makes a valid macro name, no matter what comes next (even a line break). That's why I just gave every `\` a relevance of 1 and gave those control sequences that are more specific (i.e. everything but `L2_VARIANTS`) an additional relevance of 1.

I wasn't sure if that is a good way to do it, though. I have now idea how prevalent backslashes may be in some other language. However, as a human, I basically use the heuristic "If it's got a log of backslashes, it's probably TeX.", though, so it may be fine..?

If we decide not to do this, I would want to add quite a few macro names to `KNOWN_CONTROL_WORDS`, though, in order to give snippets of math mode a chance to be recognized.

----

> Changes I made:
> 
>     * Some linting stuff
> 
>     * Some simplifications to the super complex rules.
> 
>     * Reduced overall relevancy: no double counting mode + keywords when the mode is really the keyword, brackets don't get relevancy.

Thanks, that does look better.

**Comment by schtandard** [comment]
> ```
>   const SPECIAL_CATCODE = {
>     begin: /[$&^_]/
>   };
>   const BRACES = {
>     begin: /[{}]/
>   };
> ```
> 
> @egor Are you wanting to continue this discussion on classes? I'm not sure we resolved it. I still feel like cat codes should perhaps be "operator" (though I'm willing to let it slide on my perhaps not having a great understanding of their semantic meaning in LaTex - unless you want to continue that discussion).
> 
> I'm 90% sure braces (if counted separately) should be "punctuation" though (based on syntactically they are being used compared to any other language).

For the record: I only separated braces out from the other "`built_in`" characters because they need to be excluded when scanning for nested braces. Otherwise, I would have left them in one regex with the others.

Regarding the question of highlighting braces at all: Inspired by you, I took a look at how other highlighters do it, specifically my LaTeX editor (TeXstudio), which does a better job than most at this, I think. It has a pretty sophisticated parser and highlights the arguments of some known macros, but it does _not_ highlight any braces (except for those after `\begin` and `\end`, which I don't quite get). (Needless to say, brackets are not highlighted either.)

I also had a look at Atom (with the plugin language-latex) and Notepad++. Atom also does not highlight braces (or brackets). Notepad++ does highlight them, it also highlights brackets, parentheses and angle brackets, but in a different color than braces. I don't have enough experience with those highlighters to say if they should be role models or not, though.

If we are unsure and worry that highlighting only braces may confuse people, I would suggest not to highlight braces for now. That does not seem to be uncommon and is certainly a better choice than trying to highlight brackets, I'd say.

----

> For comparison Prism lumps everything into the punctuation bucket (including `[]`, and doing nothing with `$`, `^`, and `_`):
> 
> ```
> 'punctuation': /[[\]{}&]/
> ```

I don't know Prism, so this may not apply, but my experience is that LaTeX syntax highlighters are often not great. Sometimes one can even see something shine through that suggests that the grammar author looked at LaTeX, thought they recognized structures they knew from other languages and implemented those. In my opinion, with just what we have now, this would probably be the best LaTeX highlighter out there (outside of dedicated software like TeXstudio).

File: test/markup/latex/control_sequences.txt (hunk 5 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.txt:4]: Yes. (Note that the first is `\ ` (backslash and space)* while the second one is `\` (backslash and new line). The former is a pretty common macro. I have never seen the latter in a real document, but I thought it best to make sure that it didn't cause anything unexpected (like highlighting the start of the following line or unexpectedly switching modes) and just test it, since it is a legal macro name.

*Oops, looks like that space got lost somewhere on the way. Will add it back in.

File: src/languages/latex.js (hunk 6 above)
Comment (schtandard) [reply src/languages/latex.js:43]: Every backslash followed by a non-letter is also a control sequence and many of them are not uncommon. (Just this week I wrote a document where I used `\$` quite a bit.)

File: src/languages/latex.js (hunk 7 above)
Comment (schtandard) [reply src/languages/latex.js:98]: No, there would not be any normal text in a magic comment. I agree that we thus shouldn't use `COMMENT`.

File: src/languages/latex.js (hunk 8 above)
Comment (schtandard) [reply src/languages/latex.js:193]: I hadn't thought about it before, but yes, I think it is. Would that be much better (probably meaning faster)?

File: test/markup/latex/control_sequences.txt (hunk 5 above)
Comment (joshgoebel) [reply test/markup/latex/control_sequences.txt:4]: > *Oops, looks like that space got lost somewhere on the way. Will add it back in.

That isn't going to stick unless you add it as an exception to `.editorconfig`.  Perhaps not even then.  I wonder if there is some other way to test this, I really don't like significant hidden whitespace.

File: src/languages/latex.js (hunk 6 above)
Comment (joshgoebel) [reply src/languages/latex.js:43]: Then I think we need two variants... one for the more common ones, which can have the default 1 relevance, and one for "this could match almost anything" with no relevance.

File: src/languages/latex.js (hunk 8 above)
Comment (joshgoebel) [reply src/languages/latex.js:191]: It'd be faster, yes, but I don't think you can do it if you want the delimiters on the "outside".  This isn't a huge problem or anything but I noticed it so thought I'd bring it up.

**Comment by joshgoebel** [comment]
> Should we rename 'ARGUMENT_ABSENT' in the same vein? It could also be called "END_PARENT", since all it does is immediately terminate the parent mode.

Yes, ah now I understand what you're doing there... renaming sounds good.  hmmm... how are you not falling afoul of the 0 width match rule with this one?

File: test/markup/latex/control_sequences.txt (hunk 5 above)
Comment (PhelypeOleinik) [reply test/markup/latex/control_sequences.txt:4]: As far as TeX is concerned, this
```
\ 
\
```
does the same as
```
\ %
\
```
and the same as
```
\ \
```
(in all three cases the first backslash is followed by a space and the second one by a newline) so the test file could use either.

**Comment by joshgoebel** [comment]
> The problem is that every \ makes a valid macro name, no matter what comes next (even a line break). That's why I just gave every \ a relevance of 1 and gave those control sequences that are more specific (i.e. everything but L2_VARIANTS) an additional relevance of 1.

I know discussed this a bit before but I don't think this is correct after finishing up a bunch of work on optimizing auto-detect for other languages... something like `\bluefish` or `\href` are each "one unit" and therefore should get 1 relevance. The problem is it does not work as you describe it. _If they are "highly likely" to be latex, they could get 2 (although I'm not sure this is necessary [if we give 1 relevance to LaTex 2 `\[ident]` I think the signal is already getting really strong, no?]) - but NOT by giving points to the `\`... the subsequent match (of the actual identifier) should get that relevance._ Ie, the relevance is awarding when you find a WHOLE `\ - whatever` expression not just a `\`.

The problem is:

```
\\\\\\\\\\
```
This would receive 10 relevance for Latex and that is not correct.  We need to make sure that what comes after is actually latex-like.

> I have no idea how prevalent backslashes may be in some other language. 

The point is that the grammar shouldn't award points for gibberish.  A sequence of \\\\\\\\\\ could really be anything... while `\ident` starts to be a lot more "latex like". 


> If we decide not to do this, I would want to add quite a few macro names to KNOWN_CONTROL_WORDS, though, in order to give snippets of math mode a chance to be recognized.

Remind me of some of these math cases again that you are feel would fall thru the floor?

**Comment by joshgoebel** [comment]
> If we are unsure and worry that highlighting only braces may confuse people, I would suggest not to highlight braces for now. That does not seem to be uncommon and is certainly a better choice than trying to highlight brackets, I'd say.

Unless you're very opposed I say we highlight them as "punctuation" then (and consider adding `[]` also).  `punctuation` is a new class and we can provide guidance on it (or even programmatically generate new styles) - the intention is to be "subtle variation from main text".  Often that would mean slightly darker, less saturated.  Making them fade into the background very slightly so the main content can pop more.  IE, it's like a middle ground between highlighting and not highlighting. :-)

**Comment by joshgoebel** [comment]
Screen Shot 2020-10-15 at 9 41 44 AM

As I feared.  Perhaps we could just lower (remove) relevance on the most common escape sequences... \n \r \t \u...

File: test/markup/latex/control_sequences.txt (hunk 5 above)
Comment (joshgoebel) [reply test/markup/latex/control_sequences.txt:4]: Then flip a coin but lets avoid the significant whitespace if we can. :)

Comment (schtandard) [reply test/markup/latex/control_sequences.txt:4]: Will do.

**Comment by schtandard** [comment]
> how are you not falling afoul of the 0 width match rule with this one?

Should I? I'm glad I didn't, because I wouldn't have known how to say "try these modes and if they don't match here, just give up and terminate the parent".

**Comment by schtandard** [comment]
> The point is that the grammar shouldn't award points for gibberish. A sequence of \\\\\ could really be anything... while `\ident` starts to be a lot more "latex like".

That's true.

> > If we decide not to do this, I would want to add quite a few macro names to KNOWN_CONTROL_WORDS, though, in order to give snippets of math mode a chance to be recognized.
> 
> It does sound like math might be the sticky point here if it is VERY weird... Remind me of some of these math cases again that you are feel would fall thru the floor?

They are not really weird, there's just a lot of them that are really common. Basically, anything on [this page](https://en.wikibooks.org/wiki/LaTeX/Mathematics) would qualify, but that would be a bit excessive, I think. I tried to come up with a reasonably short list that should give us a decent hit rate.

----

I also got rid of the `KNOWN_CONTROL_SYMBOLS`. As you pointed out, a backslash followed by a parenthesis (for example) could be anything.

**Comment by schtandard** [comment]
> That's some high praise. From terrible to "best in class", really?

I wanted to underline the need/potential for improvement of most other highlighters rather than toot my own horn here. (Tough many of them are acceptable.) But yes, just the fact that both LaTeX2e and LaTeX3 macros are recognized with a high accuracy elevates the grammar above many others, in my view.

File: test/markup/latex/control_sequences.txt (hunk 5 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.txt]: Done.

**Comment by schtandard** [comment]
> > If we are unsure and worry that highlighting only braces may confuse people, I would suggest not to highlight braces for now. That does not seem to be uncommon and is certainly a better choice than trying to highlight brackets, I'd say.
> 
> Unless you're very opposed I say we highlight them as "punctuation" then (and consider adding `[]` also). `punctuation` is a new class and we can provide guidance on it (or even programmatically generate new styles) - the intention is to be "subtle variation from main text". Often that would mean slightly darker, less saturated. Making them fade into the background very slightly so the main content can pop more. IE, it's like a middle ground between highlighting and not highlighting. :-)

Just to make sure: Does this mean that the `punctuation` is highlighted less prevalently than normal text (i.e. code that receives no special formatting)? In that case, I would be very opposed.

Otherwise, it would be something to think about. My feeling is that we would have to go the Notepad++ route and highlight a bunch of characters as punctuation if we want to include brackets, if we want to retain some kind of consistency (e.g. `(`, `)`, `<`, `>` and `=`, but probably some more).

I think I would feel better leaving all of these un-highlighted for now. I could write up a list of all of the common use cases for these characters, which may help with answering this question. Not highlighting them for now doesn't really hurt, I think, and adding them in easier is probably easier than taking them out, right? (From a policy standpoint.)

----

This would then be on my list of things to try and tackle next together with highlighting the contents of specific macro arguments, namely section headings, environment names, packages, document classes and labels.

File: src/languages/latex.js [hunk 9]
```diff
@@ -56,10 +55,7 @@ export default function(hljs) {
     contains: [
       {
         endsParent: true,
-        variants: [
-          {begin: KNOWN_CONTROL_WORDS},
-          {begin: KNOWN_CONTROL_SYMBOLS}
```
[the remark this answers is not in the document]
Comment (joshgoebel) [reply src/languages/latex.js]: IE:

```
        variants: [
          {begin: KNOWN_CONTROL_WORDS},
          {begin: KNOWN_CONTROL_SYMBOLS, relevance: 0 }
```

**Review by joshgoebel — COMMENTED** [review]
> Just to make sure: Does this mean that the punctuation is highlighted less prevalently than normal text (i.e. code that receives no special formatting)? In that case, I would be very opposed.

Well I'd suggest that any difference from the "normal" could actually be "more prevalent" in some regard, even if the overall highlighting tone is more subdued.  I don't think the highlighting has to be red and blinking to be noticeable. :-)

> I think I would feel better leaving all of these un-highlighted for now. 

Fine by me, for now.

File: src/languages/latex.js [hunk 10]
```diff
@@ -1,70 +1,243 @@
...
+    {begin: /[a-zA-Z@]+/}, // control word
+    {begin: /[^a-zA-Z@]?/} // control symbol
+  ];
+  const DOUBLE_CARET_VARIANTS = [
+    {begin: /\^{6}[0-9a-f]{6}/},
+    {begin: /\^{5}[0-9a-f]{5}/},
+    {begin: /\^{4}[0-9a-f]{4}/},
+    {begin: /\^{3}[0-9a-f]{3}/},
+    {begin: /\^{2}[0-9a-f]{2}/},
+    {begin: /\^{2}[\u0000-\u007f]/}
```
Comment (joshgoebel) [inline src/languages/latex.js:55]: Is this truly meant to also include the control characters below ASCII 32?

File: src/languages/latex.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (schtandard) [reply src/languages/latex.js]: All control symbols are covered by the `L2_VARIANTS` (with relevance 0), so all of these are still highlighted as `keyword`. This rule really just existed for the relevance. (Just like every item in `KNOWN_CONTROL_WORDS` would be covered by `L2_VARIANTS`, but not with relevance.)

[the remark this answers is not in the document]
Comment (joshgoebel) [reply src/languages/latex.js]: Ah, gotcha.

File: src/languages/latex.js (hunk 10 above)
Comment (schtandard) [reply src/languages/latex.js:55]: Yes. Honestly, I don't know how to input most of these (or which can even be input in a meaningful way), but some could definitely occur.

Some background on what this notation actually does in TeX: When you input `^^` followed by any ASCII character (with a number `n` between 0 and 127), this sequence acts like a single character. If `n` is below `64`, it acts like the character `n+64`, otherwise it acts like the character `n-64`. This way one can input character that would otherwise be hard to input, i.e. those control characters. For example `^^J` will result in a newline character and `^^` followed by a newline would result in a `J`.

Obviously, the more useful use of this notation is the first one, i.e. inputting control characters through letters and symbols. I just didn't see any reason to restrict the real rule (which is, all ASCII characters work). Is there any?

Comment (joshgoebel) [reply src/languages/latex.js:55]: I suppose not, just my linter flagged it as weird (and it is a little). :-)  So it was worth asking.

File: test/markup/latex/control_sequences.expect.txt [hunk 11]
```diff
@@ -0,0 +1,34 @@
+<span class="hljs-keyword">\foo</span> bar
+<span class="hljs-keyword">\foo</span>:bar
+<span class="hljs-keyword">\ </span>and<span class="hljs-keyword">\
+</span>bar<span class="hljs-keyword">\foo</span>:baz
+<span class="hljs-keyword">\!</span>!
+<span class="hljs-keyword">\^^3a</span>bc
+<span class="hljs-keyword">\^^3</span>ABC
+<span class="hljs-keyword">\^^x</span>yz
+<span class="hljs-keyword">\^</span><span class="hljs-built_in">^</span>°!
```
Comment (joshgoebel) [inline test/markup/latex/control_sequences.expect.txt:9]: This is intentional?

File: test/markup/latex/control_sequences.expect.txt [hunk 12]
```diff
@@ -0,0 +1,34 @@
...
+<span class="hljs-keyword">\cs:w</span> hljs<span class="hljs-built_in">_</span>test:N<span class="hljs-keyword">\cs_end:</span>
+<span class="hljs-keyword">\use_i:nn</span> <span class="hljs-keyword">\use:</span><span class="hljs-keyword">\q_test</span>
+<span class="hljs-keyword">\if:w</span><span class="hljs-keyword">\scan_stop:</span><span class="hljs-keyword">\s_test</span>[<span class="hljs-keyword">\else:</span>]<span class="hljs-keyword">\fi:</span>
+<span class="hljs-keyword">\hbox:n</span> <span class="hljs-keyword">\vbox:n</span>
+<span class="hljs-keyword">\::c</span><span class="hljs-keyword">\::o</span><span class="hljs-keyword">\::V</span><span class="hljs-keyword">\:::</span><span class="hljs-keyword">\hljs_test_args:Nnn</span>
+<span class="hljs-keyword">\::V_unbraced</span>
+<span class="hljs-keyword">\l_hljs_var_tl</span> <span class="hljs-keyword">\g_tmpa_prop</span> <span class="hljs-keyword">\c__hljs_secret_int</span>
+<span class="hljs-keyword">\c_e_fp</span>
+<span class="hljs-comment">% but only those conforming to the naming scheme</span>
+<span class="hljs-comment">% with at least to letters in every name</span>
```
Comment (joshgoebel) [inline test/markup/latex/control_sequences.expect.txt:28]:
```suggestion
<span class="hljs-comment">% with at least two letters in every name</span>
```
You meant two right?  Is this still accurate?

Comment (joshgoebel) [reply test/markup/latex/control_sequences.expect.txt:28]: Are there examples here that should and shouldn't be highlighted?  I'm trying to make heads or tails of it but it's hard. :)

File: test/markup/latex/verbatim.expect.txt [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+<span class="hljs-keyword">\begin</span>{filecontents*}{filename}<span class="hljs-string">
+  {The file&#x27;s contents}
+</span><span class="hljs-keyword">\end</span>{filecontents*}
+
+<span class="hljs-keyword">\begin</span> {Verbatim}
+<span class="hljs-string">\end {Verbatim}
+\begin{Verbatim}
+\end{Verbatim*}
+\begin{Verbatim*}
+</span><span class="hljs-keyword">\end</span>{Verbatim}
```
Comment (joshgoebel) [inline test/markup/latex/verbatim.expect.txt:37]: Is this correct?

File: test/markup/latex/verbatim.expect.txt [hunk 14]
```diff
@@ -0,0 +1,48 @@
+<span class="hljs-keyword">\verb</span>|<span class="hljs-string">\verb</span>|<span class="hljs-keyword">\verb</span>!<span class="hljs-string">%\&amp;$^_{}</span>!foo
+<span class="hljs-keyword">\verb</span>{<span class="hljs-string">\verb</span>{<span class="hljs-keyword">\verb</span>}<span class="hljs-string">\verb{</span>}
```
Comment (joshgoebel) [inline test/markup/latex/verbatim.expect.txt:2]: This is correct because verb can only be VERBATIM_DELIMITED_EQUAL so the delimiters here are `{` on both sides?

File: src/languages/latex.js [hunk 15]
```diff
@@ -1,70 +1,243 @@
...
+    return {
+      className: 'string',
+      end: '(?=\\\\end\\{' + envname + '\\})'
+    };
+  };
+
+  const VERBATIM_DELIMITED_BRACES = (innerName = "string") => {
+    return {
+      relevance: 0,
+      begin: /{/,
```
Comment (joshgoebel) [inline src/languages/latex.js:197]:
```suggestion
      begin: /\{/,
```

Needs to be escaped.

File: src/languages/latex.js [hunk 16]
```diff
@@ -1,70 +1,243 @@
...
+  const ARGUMENT_BRACKETS = {
+    begin: /\[/,
+      end: /\]/,
+    endsParent: true,
+    relevance: 0,
+    contains: [BRACE_GROUP_NO_VERBATIM, ...EVERYTHING_BUT_VERBATIM]
+  };
+  const END_PARENT = {
+    begin: /(?=[.$])/,
+    end: /(?=[.$])/,
```
Comment (joshgoebel) [inline src/languages/latex.js:138]: Explain again please, is this meant to be `.` (any character) or the literal `.` (period).

Can you show me an example or two that this is intended to terminate?

File: src/languages/latex.js [hunk 17]
```diff
@@ -1,70 +1,243 @@
...
+  const VERBATIM_DELIMITED_BRACES = (innerName = "string") => {
+    return {
+      relevance: 0,
+      begin: /{/,
+      starts: {
+        endsParent: true,
+        contains: [
+          {
+            className: innerName,
+            end: /(?=})/,
```
Comment (joshgoebel) [inline src/languages/latex.js:203]:
```suggestion
            end: /(?=\})/,
```

Sorry my work I know. :)

**Comment by joshgoebel** [comment]
Ok, that was a bear to review.  I think that's all I got though. :-)  I can smell the finish line. :nose:

**Comment by joshgoebel** [comment]
This is one of only two blockers for 10.3 now! :-)

File: test/markup/latex/control_sequences.expect.txt (hunk 11 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.expect.txt:9]: Yes. I wanted to do a negative test, too. (`°` does not qualify for the `^^` syntax, as it is not in ASCII.)

File: test/markup/latex/control_sequences.expect.txt (hunk 12 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.expect.txt]: Yes. The lines above this comment should be highlighted as LaTeX3 macros, the ones below shouldn't.

The naming convention is as follows
- A function belongs to a `module`, has a `function name` and a `signature`. These are encoded in its macro name as `\module_function_name:signature` or `\__module_function_name:signature`.
- A variable has a `scope`, a `module`, a `variable_name` and a `type`. These are encoded in its macro name as `\scope_module_variable_name_type` or `\scope__module_variable_name_type`. The module may be omitted if it is identical to the type.
- Quarks have a `quark name` and look like `\q_quark_name`.
- Similarly, scan tokens look like `\s_scan_token_name`.
- Built-in functions often do not follow any scheme except for the signature: `\anything:signature`

Now, the rule detecting LaTeX3 macros in the grammar only detects macro names that have at least two characters in each of `module`, `function_name`, `type`, `quark_name` and `scan_mark_name`, as applicable (except for certain built-in functions). (`scope` is always one of `l`, `g` or `c`, there is not restriction on `variable_name`s. Double `_`, except where indicated above, are also prohibited.) The restriction on at least two characters was introduced to avoid things like the misinterpretation of `\theta_a` (which is the letter theta with the subscript a in math mode) as a LaTeX3 variable.

That's what I wanted to hint at in that comment.

File: test/markup/latex/verbatim.expect.txt (hunk 13 above)
Comment (schtandard) [reply test/markup/latex/verbatim.expect.txt:37]: Yes, it is.

File: test/markup/latex/control_sequences.txt [hunk 18]
```diff
@@ -0,0 +1,34 @@
+\foo bar
+\foo:bar
+\ and\
+bar\foo:baz
+\!!
+\^^3abc
+\^^3ABC
+\^^xyz
+\^^°!
```
Comment (joshgoebel) [inline test/markup/latex/control_sequences.txt:9]:
```suggestion
\^^xyz
% ° does not qualify for the ^^ syntax, as it is not in ASCII
\^^°!
```
And the corresponding result also...

File: test/markup/latex/verbatim.expect.txt (hunk 14 above)
Comment (schtandard) [reply test/markup/latex/verbatim.expect.txt:2]: Precisely.

File: src/languages/latex.js (hunk 15 above)
Comment (schtandard) [reply src/languages/latex.js]: Yes, and the `end` a couple of lines down, too.

File: test/markup/latex/verbatim.expect.txt (hunk 13 above)
Comment (joshgoebel) [reply test/markup/latex/verbatim.expect.txt:37]: Oh, I see... what is the delimiter their, CR?

**Comment by joshgoebel** [comment]
@egor-rogov I'm going to push this home once all the tiny little final changes are made here (so I can release 10.3).  I think at this point we've dropped most of the "controversial" things discussed earlier that we had different diverging feelings on.  And of course this isn't the last word on the topic, hopefully the grammar will continue to evolve as all our grammars do.

@schtandard Thanks for all your hard work on this and letting us put you thru the ringer to polish this to something that fits nicely in the scope of the core library.  It's a great contribution.

File: test/markup/latex/control_sequences.expect.txt (hunk 12 above)
Comment (joshgoebel) [reply test/markup/latex/control_sequences.expect.txt]: A few more comments here maybe wouldn't hurt for non-latex people, but I won't say they are necessary as I really want to get this merged, not keeping giving you more work to do. :-)  Or perhaps it's a lost cause for the non-latex among us. :-)

File: src/languages/latex.js (hunk 16 above)
Comment (schtandard) [reply src/languages/latex.js:138]: It's any character. This rule is meant to give a zero-length match anywhere (looking ahead for any character or the end of the line).

This is used when looking for optional arguments. The grammar is meant to look for a `[`. If it finds one, it should highlight the entire optional argument and end the parent (i.e. stop looking for optional arguments). If it doesn't find one, it should end the parent anyway, instead of stepping on to the next character and trying again. That is what this mode does: End the parent, no matter what. (Without consuming any characters.)

File: test/markup/latex/control_sequences.txt (hunk 18 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.txt:9]: Done.

File: src/languages/latex.js (hunk 16 above)
Comment (joshgoebel) [reply src/languages/latex.js:138]: Are you sure it works?  `.` inside `[]` is a literal period

```
> "test\nbooger".match(/(?=[.$])/)
null
> "test\nbooger".match(/(?=.|$)/)
[ '', index: 0, input: 'test\nbooger', groups: undefined ]
> "test\nsmith.\nbooger".match(/(?=[.$])/)
[ '', index: 10, input: 'test\nsmith.\nbooger', groups: undefined ]
```

And if I'm correct and it's not even working, is it necessary?  Where is the failing test?

Comment (joshgoebel) [reply src/languages/latex.js:138]: Any FYI our "end immediately" goto regex is `/\B|\b/`

File: test/markup/latex/verbatim.expect.txt (hunk 13 above)
Comment (schtandard) [reply test/markup/latex/verbatim.expect.txt:37]: No, the environments work a bit differently. `\begin{Verbatim}` is ended by `\end{Verbatim}` with the wrinkle that there may be spaces before the `{` following `\begin` (which is the normal behavior) but not before the one following `\end` (which is a special property of verbatim environments). That is, in this case `\begin {Verbatim}` is ended by `\end{Verbatim}`.

File: src/languages/latex.js (hunk 16 above)
Comment (joshgoebel) [reply src/languages/latex.js:138]: I presume something incorrect could get highlighted (if the parent mode continued) but our tests seem to indicate that most often the parent mode is terminating on it's own (making me wonder if we really need this in actuality)... if we do we may need to revisit it later (you could open an issue) since a correct rule is going to run afoul of the fact that rules are not allowed to consume nothing.  I'm not sure it should hold up the merge unless it's a major issue.

File: test/markup/latex/control_sequences.expect.txt (hunk 12 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.expect.txt]: Yeah, I thought about that, but wanted to wait until I was sure the rule wouldn't change anymore. What would be the best place for this? The grammar file or the test file? Or both?

File: src/languages/latex.js (hunk 16 above)
Comment (schtandard) [reply src/languages/latex.js:138]: Hmm, I thought I tested its necessity. Give me a minute..

Comment (schtandard) [reply src/languages/latex.js]: I couldn't produce any problems without that mode, so I removed it. Seems to have been a chimera..

File: test/markup/latex/control_sequences.expect.txt (hunk 12 above)
Comment (joshgoebel) [reply test/markup/latex/control_sequences.expect.txt]: Definitely the grammar though you could add a `(see grammar for details)` hint or something in the test I think.

File: test/markup/latex/verbatim.expect.txt (hunk 13 above)
Comment (joshgoebel) [reply test/markup/latex/verbatim.expect.txt:37]: Ah, right. :)

**Comment by joshgoebel** [comment]
What's your @name on Meta Stackoverflow if you're there... I'll definitely credit you there when I mention the new release (I was planning to respond to a latex thread anyways)...

File: test/markup/latex/control_sequences.expect.txt (hunk 12 above)
Comment (schtandard) [reply test/markup/latex/control_sequences.expect.txt]: Ok, give me a moment, I will add some comments.

**Comment by schtandard** [comment]
@joshgoebel Thanks for coaching me through this, that was really helpful!

I hope to do some more work on this in the future, but may take a little more time now that we got this far. :-)

**Comment by schtandard** [comment]
> 
> 
> What's your @name on Meta Stackoverflow if you're there... I'll definitely credit you there when I mention the new release (I was planning to respond to a latex thread anyways)...

My name there is schtandard, thanks for the thought. I hope, the powers that be will update to 10.3 in a timely manner..

File: src/languages/latex.js (hunk 16 above)
Comment (joshgoebel) [reply src/languages/latex.js]: Modes without an `end` will get the default `end: /\B|\b/` so they are very eager to end themselves UNLESS they continue to match children... so the first time no children can be found at the current cursor position the parent mode terminates.  `end` on the other hand "holds the mode open" and allows for non-matches in-between the children matches.

This makes it hard for us to express:

- mode A followed by a single mode B

Because if there are multiple B's immediately in a row under A, then they will continue to get matched... `endsParent` solves this for single paired items but gets complex when you want to go deeper.

**Comment by joshgoebel** [comment]
I think I'm mostly good.  Let me know when you've gotten any last comments added, etc...

**Comment by schtandard** [comment]
@joshgoebel I think I'm done. Maybe have a look at the comments to check for typos, etc.

I also reordered one of the regexes to make it reflect how I describe the rule more closely (it also got shorter). Did not change the matching behavior, though.

File: src/languages/latex.js [hunk 19]
```diff
@@ -33,7 +33,7 @@ export default function(hljs) {
     ].map(word => word + '(?![a-zA-Z@:_])'));
   const L3_REGEX = new RegExp([
       '(?:__)?[a-zA-Z]{2,}_[a-zA-Z](?:_?[a-zA-Z])+:[a-zA-Z]*',
-      '[lgc]__?[a-zA-Z]+_[a-zA-Z](?:_?[a-zA-Z])*[a-zA-Z]',
+      '[lgc]__?[a-zA-Z](?:_?[a-zA-Z])*_[a-zA-Z]{2,}',
```
Comment (joshgoebel) [inline src/languages/latex.js:42]: Much nicer!

**Comment by JamesTheAwesomeDude** [comment]
Is the attached-screenshotted bug with the highlighting an instance of this issue? Or should it be opened separately?

[image](https://tex.stackexchange.com/a/568006/145273)

**Comment by joshgoebel** [comment]
This has been merged.  Please open a new issue.

**Comment by PhelypeOleinik** [comment]
@JamesTheAwesomeDude That looks like a screenshot from stackexchange: they didn't update yet, so the highlighting you see is from the old version (the one that kickstarted the rewrite in this PR).  That should be highlighted correctly now, see https://tex.meta.stackexchange.com/q/8665/134574 and https://tex.meta.stackexchange.com/q/8688/134574

File: src/languages/latex.js [hunk 20]
```diff
@@ -1,70 +1,248 @@
...
+        contains: [SPACE_GOBBLER],
+        starts: starts_mode
+      };
+  };
+  const BEGIN_ENV = function(envname, starts_mode) {
+    return hljs.inherit(
       {
-        className: 'formula',
-        contains: [COMMAND],
+        begin: '\\\\begin(?=\\s*\\r?\\n?\\s*\\{' + envname + '\\})',
```
Comment (joshgoebel) [inline src/languages/latex.js:175]: We'll need to change this, this can result in a polynomial backtracking. Because the `\s*` will dual with each other since there is no guarantee there will be any content in the middle.

Can this be replaced with a single group? `(\s\r\n)` ?  If not we may need two different paths here to avoid backtracking.

Comment (schtandard) [reply src/languages/latex.js:175]: Yes, I think it can. The real rule is that there may only be one newline, but that's really not so important after `\begin`. I'll try to make a PR shortly.

(Sorry for being so unresponsive lately. It's been difficult to find some time to work on this beside my other obligations.. There will be different times again, though.)

Comment (joshgoebel) [reply src/languages/latex.js:175]: I took a quick pass:

```ts
begin: '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{' + envname + '\\})',
```

Thoughts?

Passes all your tests.

Comment (schtandard) [reply src/languages/latex.js:175]: Yes, that's what it should be. (I think I thought `\s` didn't capture newlines, which seems to also be wrong.) Don't know if there are any (dis)advantages to making the group non-capturing performance-wise..?

Comment (joshgoebel) [reply src/languages/latex.js:175]: > Don't know if there are any (dis)advantages to making the group non-capturing performance-wise..?

I've seen mixed results on this, so typically I don't worry about captures unless I'm using references or one of the few rules that uses reference.
